### ISSUE TITLE
add pallet_version storage API

### ISSUE THREAD

**Issue by pgherveou** [paritytech/subxt#1001]
Hey there, I just used subxt to build some quick data analysis and realized that `pallet_version` is missing from the StorageAPI.
Should we add itI? If so, is there a way to get it from the metadata, or should we add some "manual" code to the StorageApi.

I was able to fetch it using fetch_raw with the following code.
```rs
async fn get_contract_version(
    client: &OnlineClient<PolkadotConfig>,
    block_hash: Option<H256>,
) -> Result<StorageVersion> {
    let key = storage_prefix(b"Contracts", b":__STORAGE_VERSION__:");

    let storage = match block_hash {
        Some(block_hash) => client.storage().at(block_hash),
        None => client.storage().at_latest().await?,
    };

    storage
        .fetch_raw(&key)
        .await?
        .and_then(|v| StorageVersion::decode(&mut v.as_slice()).ok())
        .ok_or_else(|| anyhow::format_err!("failed to decode pallet_version"))
}
```

**Comment by jsdw** [comment]
Ah interesting, thanks for raising the issue! 

It looks like a "special" entry of some sort, so perhaps it's not been made available in the same way as other methods to the codegen. We'll dig into this and find out!

(There's also the special `:code:` entry (or something like that) iirc for fetching the current runtime WASM which we should also look to expose)

**Comment by tadeohepperle** [comment]
Hey @pgherveou we implemented a `storage_version` function in Subxt a while ago: 

https://github.com/paritytech/subxt/blob/a731a92c1f1864ab0f2954a1c5e0ef920a45f2b5/subxt/src/storage/storage_type.rs#L258

Does this solve the issue for you?

We now also have a function to fetch a nodes runtime code:

https://github.com/paritytech/subxt/blob/a731a92c1f1864ab0f2954a1c5e0ef920a45f2b5/subxt/src/storage/storage_type.rs#L284
