### ISSUE TITLE
chain_getBlock extrinsics encoding

### ISSUE THREAD

**Issue by pgherveou** [paritytech/subxt#1010]
When I query the chain_getBlock extrinsics, subxt deserialize the extrinsics bytes with scale

https://github.com/paritytech/subxt/blob/1ad9a20ce2a156fae7c3b3d0fb4d408c5d07c374/subxt/src/rpc/types.rs#L113-L126

As a result if I compare the result of substrate export-blocks command or if I make a raw query to the rpc, I get different values for these extrinsics. If the subxt client is just supposed to return the result of the API call it should not try to interpret the payload.

Instead we should probably use something like this 
```rust
pub struct ChainBlockExtrinsic(#[serde(with = "impl_serde::serialize")] pub Vec<u8>);
```

**Comment by jsdw** [comment]
I think that's a fair comment; all that `Decode::decode` is doing is removing the `Compact(length)` bytes from the beginning anyway and allocating a new vec in the process. Probably we can handle this "down the line" easily enough, avoid an extra allocation and have a slgihtly "purer" RPC call.
