### ISSUE TITLE
How to handle Dispatch error

### ISSUE THREAD

**Issue by koptan** [paritytech/subxt#1027]
I am looking for a way to cast Errors into my own pallet dispatch errors.

Any examples please?

**Comment by jsdw** [comment]
We need to add better docs for this area for sure! We have some tests which show error handling a bit though, so I hope that these will help:

You can match on the `DispatchError` in general:

https://github.com/paritytech/subxt/blob/34f5384650d633be8166e233a844d427c87b13c4/testing/integration-tests/src/full_client/frame/balances.rs#L345

If the error is a `ModuleError` ie emitted from some pallet, you can get details etc for it:

https://github.com/paritytech/subxt/blob/34f5384650d633be8166e233a844d427c87b13c4/testing/integration-tests/src/full_client/frame/staking.rs#L123

If you have a `ModuleError` you can also use `.as_root_error()` to try and decode it into a concrete error type (see https://docs.rs/subxt/latest/subxt/error/struct.ModuleError.html), eg:

https://github.com/paritytech/subxt/blob/34f5384650d633be8166e233a844d427c87b13c4/testing/integration-tests/src/full_client/client/mod.rs#L380

**Comment by jsdw** [comment]
I'll close this given that I opened #1045 to cover adding docs; lemme know if you still have an issue though!
