### ISSUE TITLE
How to connect to Substrate RPC HTTP API?

### ISSUE THREAD

**Issue by f-squirrel** [paritytech/subxt#1033]
I am working against a third-party node provider, which provides Substrate RPC HTTP API and Sidecar but seems to have no web socket or very limited.
So I have two questions:

1. How to send HTTP-RPC via `subxt` (I have no problem with periodic polling)? I have tried to construct the client from an HTTP URL but received an error: `Failed to connect to node: Rpc(ClientError(Transport(Invalid URL: `https` not supported, expects 'ws' or 'wss`
2. The node provider requires their users to add a bearer token for each request. Is it possible to do it in `subxt`, and if not, could you please point me to where I can add this functionality?

**Comment by niklasad1** [comment]
1. The default rpc client in subxt doesn't support HTTP because many APIs around it's based on subscriptions which isn't supported by the substrate HTTP RPC API. You could it yourself by implementing the RpcClient for your favorite HTTP RPC client or add an impl for the jsonrpsee::http_client

2. It's possible but requires some code from you see my answer in https://github.com/paritytech/subxt/issues/1035

**Comment by f-squirrel** [comment]
@niklasad1 it seems that `subxt` is subscription-oriented. Will it be possible to implement a client that would just ignore the subscription part? It seems not trivial, I assume there is no many examples, right?

**Comment by jsdw** [comment]
At the moment, you can use subxt with an HTTP client and just avoid the APIs that call subscriptions (including any of the transaction APIs including the word `watch`, and anything with the word `subscribe` in).

Eventually though, Subxt will target the new RPC interface (see https://github.com/paritytech/json-rpc-interface-spec/), and this relies on subsriptions even more heavily. So, ultimately the third party will basically have to allow WSS requests to be able to properly service most RPC requests as we move towards this nerw interface.

**Comment by f-squirrel** [comment]
Thank you for the reply. Just to clarify: I need to implement `RcpClientT`, right?

**Comment by f-squirrel** [comment]
Ok, so I implemented the traits as follows:

```rust
struct Params(Option<Box<RawValue>>);

impl ToRpcParams for Params {
    fn to_rpc_params(self) -> Result<Option<Box<RawValue>>, Error> {
        Ok(self.0)
    }
}

pub struct PolkadotClient(HttpClient);

impl PolkadotClient {
    pub fn from_http_client(client: HttpClient) -> Self {
        PolkadotClient(client)
    }
}

impl RpcClientT for PolkadotClient {
    fn request_raw<'a>(
        &'a self,
        method: &'a str,
        params: Option<Box<RawValue>>,
    ) -> RpcFuture<'a, Box<RawValue>> {
        log::info!("call {}", method);
        Box::pin(async move {
            let res = self
                .0
                .request(method, Params(params))
                .await
                .map_err(|e| RpcError::ClientError(Box::new(e)))?;
            Ok(res)
        })
    }

    fn subscribe_raw<'a>(
        &'a self,
        _sub: &'a str,
        _params: Option<Box<RawValue>>,
        _unsub: &'a str,
    ) -> RpcFuture<'a, RpcSubscription> {
        panic!("HTTP Client does not support subscription");
    }
}

async fn subxt() {
    let token = format!(
        "Bearer {}",
        "TOKEN"
    );
    let mut headers = HeaderMap::new();
    headers.insert(http::header::AUTHORIZATION, token.parse().unwrap());
    let client = HttpClientBuilder::default()
        .set_headers(headers)
        .build("https://dmoain:433/polkadot/mainnet/native/http-rpc")
        .unwrap();

    log::info!("creating client");
    let polka_client = PolkadotClient(client);
    log::info!("created client");
    let api = OnlineClient::<PolkadotConfig>::from_rpc_client(Arc::new(polka_client))
        .await
        .expect("Failed to connect to node");
    log::info!("created api");
    api.blocks().at_latest().await.unwrap();
    log::info!("received block");

}
```

It compiles like a charm but crashes in runtime on timeout:

```plain
2023-06-28T14:20:06.608028297+00:00 | INFO  | creating client
2023-06-28T14:20:06.608105636+00:00 | INFO  | created client
2023-06-28T14:20:06.608209211+00:00 | INFO  | call chain_getBlockHash
2023-06-28T14:20:06.608662065+00:00 | INFO  | call state_getRuntimeVersion
2023-06-28T14:20:06.608891702+00:00 | INFO  | call state_call
thread 'main' panicked at 'Failed to connect to node: Rpc(ClientError(RequestTimeout))'
```

So I do see that `subxt` does call to my implementation, which transfers them to the inner HTTP client, but for some reason, it never receives a reply.

Important to note that I can make these requests via curl with the same credentials.

**Comment by f-squirrel** [comment]
Oh, I did not put the actual URL only because I cannot share credentials. I wish it was a URL issue. :)))

**Comment by f-squirrel** [comment]
Thank you @niklasad1 !
I can fetch blocks now!!! :)

**Comment by jsdw** [comment]
We can't add/support HTTP-only clients in Subxt, because it depends quite heavily on subscriptions (or "server notifications", and thus websockets) to do many of its core functions. As we migrate to the new V2 interface (https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html), subscriptions will become pretty much mandatory to access _any_ recent block information, and so Subxt won't really be able to do much at all without them (and nor will any other client that doesn't support WebSockets).
