### ISSUE TITLE
How to add a custom header to subxt requests?

### ISSUE THREAD

**Issue by f-squirrel** [paritytech/subxt#1035]
I am working against a 3rd party node provider.
In order to connect to their web socket, I need to add a header with auth token as follows:

```sh
wscat -H "X-Auth-Token: YOUR_AUTH_TOKEN" -c wss://YOUR_ENDPOINT_URL/websocket 
```

How can i configure the client to do it? Shall I build a `jsonrpsee` client and somehow provide it to the `subxt` client?

**Comment by lexnv** [comment]
Hey,

You could use the following method:

https://github.com/paritytech/subxt/blob/a3eedc6651f7702f93e80dd10dc5769dc4331b49/subxt/src/client/online_client.rs#L83-L88

This allows you to provide a custom RPC client layer.

By default, we provide the following to the subxt's `OnlineClient`

https://github.com/paritytech/subxt/blob/a3eedc6651f7702f93e80dd10dc5769dc4331b49/subxt/src/client/online_client.rs#L436-L452 

After you construct the jsonrpsee client, you can pass it to subxt similar to:
https://github.com/paritytech/subxt/blob/a3eedc6651f7702f93e80dd10dc5769dc4331b49/subxt/src/client/online_client.rs#L78-L79

When it comes to the jsonrpsee client, you'd need to provide the extra header info.

The [WsTransportClientBuilder](https://github.com/paritytech/jsonrpsee/blob/35defc54fcc3eacc4140a78423e6e5be14505435/client/transport/src/ws/mod.rs#L63) supports the following method [set_headers](https://github.com/paritytech/jsonrpsee/blob/35defc54fcc3eacc4140a78423e6e5be14505435/client/transport/src/ws/mod.rs#L141).

Let us know if there's anything we could do to help here

**Comment by niklasad1** [comment]
> How can i configure the client to do it? Shall I build a jsonrpsee client and somehow provide it to the subxt client?

Yes, that is the easiest solution to solve it:

```rust
let mut headers = HeaderMap::new();
headers.insert("X-Auth-Token", TOKEN);
let rpc = WsClientBuilder::default().set_headers(headers).build(&uri).await.unwrap();
let api = SubxtClient::from_rpc_client(Arc::new(rpc)).await.unwrap();

// use subxt
```

**Comment by f-squirrel** [comment]
@lexnv and @niklasad1 thank you folks for your prompt reply.
