### ISSUE TITLE
Support `AccountId20` type and Ethereum signatures

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/subxt#1037]
Would it be possible to extend subxt to support AccountId20 and ethereum style signatures? I am working on a chain for the PBA where we would like to use the `AccountId20` type. Of course this would also benefit ecosystem chains like Moonbeam.

**Comment by jsdw** [comment]
Just to note; Subxt does already support all of these things (you can define the account and signature types in the `Config` for a given chain, and you can write your own implementations of `Signer` to handle signing anything you like.

If there's enough demand, we could look into writing signer bits in `subxt-signer` for these things, but at the moment we're focusing on the most common cases (while exposing the relevant traits such that support for other things can be hooked in)

**Comment by JoshOrndorff** [comment]
Okay, this makes sense. I actually did see the `PairSigner` trait when I was looking around.

My ultimate goal is to make cargo contract, which is built on subxt, work with `AccountId20`. So I will continue to follow up in https://github.com/paritytech/cargo-contract/issues/1182

**Comment by bernardoaraujor** [comment]
hey @jsdw I'm on the Delivery Services team and we're working on a client project that is using `AccountId20`

+1 for demand!
