### ISSUE TITLE
Config: Overhaul `ExtrinsicParams`

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#1062]
RIght now, `ExtrinsicParams` is some hardcoded value which knows how to `encode_extra` and `encode_additional` bytes to help build a tx/signer payload. The default implementation provides a "nice" interface for setting mortality/tip on submitting a transaction, but will break if the chain you try and talk to has different/other params (as one example, polkadot and substrate node differ a bit in how tips are given for instance).

Ideas I have here that may or may not be sane:

### Provide composable `signed_extensions` module.

What if we could do something like:

```rust
use subxt::config::signed_extensions;

impl Config {
    // ...

    type ExtrinsicParams = (
        signed_extensions::CheckTxVersion,
        signed_extensions::CheckGenesis,
        signed_extensions::CheckMortality,
        signed_extsnsions::CheckNonce,
        signed_extensions::ChargeTransactionPayment
    )
}
```

ie we initialise the config with the set of signed extensions appropriate for the chain. Each extension on its own implements `ExtrinsicParams` and has some correposnding `OtherParams` which is a pretty interface to set the values for it. Tuples of `ExtrinsicParams` things also implement `ExtrinsicParams`, so you'd have to give a tuple of the corresponding `OtherParams`. (Can we be smart here; some extensions need no `OtherParams` since they get info direct from Subxt, so would be lovely if they could be omitted entirely rather than providing some `()`'s in their place).

### Generate these params automatically based on metadata

The metadata has a list of these params for a chain, and we can see which ones require non-zero values to be provided and which are only used on the node side (ie whose values are just `()` and encode to nothing). We could potentially add another attr to the `subxt` macro to ask it to generate/provide the `ExtrinsicParams`, ie:

```rust
#[subxt(
    runtime_metadata_path = "../artifacts/polkadot_metadata_small.scale",
    with_extrinsic_params
)]
mod runtime {}

// With `with_extrinsic_params`, the macro will generate a tuple of the above
// based on the metadata (it will fail with a nice error if a signed extension in the
// metadata isn't one we know about). 
impl Config {
    // ....
    type ExtrinsicParams = runtime::ExtrinsicParams
}
```

### Allow these params to default to nothing / be dynamic

Currently (but perhaps not forever), it would be possible to use the metadata to know exactly which params are needed. We could provide something like:

```rust
impl Config {
    // ....
    type ExtrinsicParams = subxt::config::DynamicExtrinsicParams;
}
```

This would support any extensions that Subxt knows about, and would either insert default values for each of them if no value is given, or interpret the dynamic `Value` given to pull out and use whatever values are provided. It needs to know abotu the extensions because they tend to encode things in a strange way (eg mortality stuff), and so we want to expose a dynamic but "friendly" interface to allow them being set, and also understand what sensible defaults would be.

We'd want to support an interface like this:

```rust
let params = value!({
    tip: 12345,
    // asset ID to use for tipping; can be omitted:
    tip_asset_id: 0,
    // number of blocks tx is valid for:
    mortality_period: 100,
    // block number it starts; Subxt should be able to populate this automatically if not given:
    mortality_start: 10_000_000 
});

api.tx().sign_and_submit_then_watch(call, signer, params).await
```

And this could work like so:
- It would be handed metadata when constructed.
- `OtherParams = scale_value::Value`.
- When asked to encode extra/additional params, it would look in the metadata to see exactly which extensions exist, and look at the `Value` given to, for each signed extension we know about, pluck out any user provided values and use them to encode the correct format for the signed extension (probably be leaning on the `signed_extensions::*` types mentioned above).

### Interface changes

As part of supporting `DynamicExtrinsicParams` we'll need to change the `ExtrinsicParams` interface a bit. But we can go further I think too, to be more flexible going forwards.

Right now we have:

```rust
pub trait ExtrinsicParams<Index, Hash>: Debug + 'static {
    type OtherParams;

    fn new(
        spec_version: u32,
        tx_version: u32,
        nonce: Index,
        genesis_hash: Hash,
        other_params: Self::OtherParams,
    ) -> Self;

    fn encode_extra_to(&self, v: &mut Vec<u8>);
    fn encode_additional_to(&self, v: &mut Vec<u8>);
}
```

Instead of providing `spec_version`, `tx_version`, and `genesis_hash` we could have a `C: OfflineClient<T>` as a parameter, and then we can ask for all of those things from that, as well as asking for `Metadata` to enable a bunch of dynamic things.

Would it be possible to have a nice interface in which `new()` was async, and the client was `OnlineClient` potentially if the thing the config was used with was an `OnlineClient`? This would enable us to eg retrieve current block number for `mortality` and so default to having mortal transactions for instance. Would also keep the door open for other "smarter" signed extensions.

**Comment by tadeohepperle** [comment]
Here are some of my ideas how the ExtrinsicParams could be restructured. It should satisfy the following needs:
- dynamic creation of ExtrinsicParams from client and scale value
- code generation from metadata possible
```rs
pub trait Param : Encode + Decode {
    const VALUE_KEY : Option<&'static str> = None

    fn decode_from_value(&value: scale_value::Value) -> Result<Self, Error>{
        // look in scale value for key Self::VALUE_KEY and use Self::decode() to decode type
    }
}

// I would probably stick to a very simple interface like this:
pub trait ExtrinsicParams{
    fn decode_from_value(&value: scale_value::Value) -> Result<Self, Error>;

    fn encode_extra_to(&self, v: &mut Vec<u8>);

    fn encode_additional_to(&self, v: &mut Vec<u8>);
}

// each signed extension value is basically a tuple of *extra* and *additional*
impl<A: Param, B: Param> ExtrinsicParams for (A, B) {

    fn decode_from_value(&value: scale_value::Value) -> Result<Self, Error>{
        (A::decode_from_value(value)?, B::decode_from_value(value)?)
    }

    fn encode_extra_to(&self, v: &mut Vec<u8>){
        self.0.encode_to(v);
    }
    fn encode_additional_to(&self, v: &mut Vec<u8>){
        self.1.encode_to(v);
    }
}

// arbitrary tuple implementation (with macros):
impl<T,U,V,...> ExtrinsicParams for (T,U,V,...) 
    where T: ExtrinsicParams, 
          U: ExtrinsicParams, 
          ...
{
    fn decode_from_value(&value: scale_value::Value) -> Self{
        (
           T::decode_from_value(value)?, 
           U::decode_from_value(value)?,
           V::decode_from_value(value)?,
           ...
        )
    }

    fn encode_extra_to(&self, v: &mut Vec<u8>){
        T::encode_extra_to(v);
        U::encode_extra_to(v);
        V::encode_extra_to(v);
        ...
    }
    fn encode_additional_to(&self, v: &mut Vec<u8>){
        T::encode_additional_to(v);
        U::encode_additional_to(v);
        V::encode_additional_to(v);
        ...
    }
}

// we can then provide `SubstrateConfig` like this:
pub type SubstrateConfig = (
    signed_extensions::CheckTxVersion,
    signed_extensions::CheckGenesis,
    signed_extensions::CheckMortality,
    signed_extsnsions::CheckNonce,
    signed_extensions::ChargeTransactionPayment
);

// with this kind of content present in the generated static interface:
type signed_extensions::CheckTxVersion = ((), CheckTxVersionAdditional)

#[derive(Encode, Decode)]
struct CheckTxVersionAdditional(u32)

impl Param for CheckTxVersionAdditional{
    const VALUE_KEY = Some("tx_version")
}

// # Dynamic interface with this approach:

// we can then provide functions that try to create any
// - from the Metadata of an OnlineClient
// - from a scale_value::Value 
// - from a mix of both

pub fn extrinsic_params_from_client<E, C>(client: C, optional_value: Option<scale_value::Value>) -> Result<E, Error>
    where E: ExtrinsicParams, C: OnlineClient
    {
        // 1. OnlineClient create a scale value with some hardcoded set of values:
        // - genesis hash
        // - nonce
        // - block number
        // ...

        // 2. merge the scale value with the optional_value provided by the user.
        // This results in a scale value with hopefully all information we need.

        // 3. call `E::decode_from_value` on the merged scale value
    }

// # Mixing Dynamic and Static interface??
// -> like providing some part of the config as static types, some part as a scale value and some part being fetched by the online client.
//
// I don't know yet how to do that.

```

**Comment by jsdw** [comment]
So, essentially we need a trait that can:

1. Take some parameters in from a user.
2. Combine those with some parameters from Subxt, and be able to encode extra and additional bytes when needed.
3. Is able to take in and encode dynamic parameters too

I think the `ExtrinsicParams` trait encodes these properties fairly well already. The only real issues are:

1. It has no access to metadata at the moment, so it can't achieve (3).
2. The `new()` method is otherwise a little ugly (I'm splitting hairs here though really).

So I think if it looked something like:

```rust
pub trait ExtrinsicParams<T: Config>: Debug + 'static {
    // As before; allows arbitrary params to be provided by user
    // depending on implementation:
    type OtherParams;

    // Take in the entire Client, since it basically needs everything
    // from it anyway, and any changes we need to expose stuff in the
    // OfflineClient trait will automatically make them available here
    fn new<Client: OfflineClientT<T>>(
        nonce: u64,
        client: Client,
        other_params: Self::OtherParams,
        // Return a Result, so that we have the possibility of failure. We'll
        // need this for dynamic use cases where the chain may use signed extensions
        // we don't know about and thus can't work with: Error is prob just a
        // Box<Error + Send + Sync + 'static> cos we don't know what different impls 
        // will want to return.
    ) -> Result<Self, ParamsError>;

    // As before:
    fn encode_extra_to(&self, v: &mut Vec<u8>);
    fn encode_additional_to(&self, v: &mut Vec<u8>);
}
```

Then we can have "signed extensions" in eg a `subxt::config::signed_extensions` mod like:

```rust
// the names should be whatever the names of the signed extensions are:
pub struct CheckGenesis<Hash>(Hash);

impl ExtrinsicParams<T: Config> for CheckGenesis<T::Hash> {
    type OtherParams = ();

    fn new<Client: OfflineClientT<T>>(
        nonce: u64,
        client: Client,
        other_params: Self::OtherParams,
    ) -> Result<Self, ParamsError> {
        Ok(self(client.genesis_hash()))
    }

    fn encode_extra_to(&self, v: &mut Vec<u8>) {
        ()
    }
    fn encode_additional_to(&self, v: &mut Vec<u8>) {
        self.0.encode_to(v);
    }
}

pub struct CheckMortality<Hash> {
    era: Era,
    mortality_checkpoint: Hash
}

// OtherParams for CheckMortality so user can provide what we need:
pub struct Mortality<Hash> {
    era: Era,
    // if user doesn't provide we use genesis hash:
    mortality_checkpoint: Option<Hash>
}

// Give it some nice api:
impl <Hash> Mortality<Hash> {
    fn era(Era) -> Self;
    fn checkpoint(mut self, Hash) -> Self;
    // Maybe this would be nice; you say how long you want to be mortal
    // for (period) and provide the starting block (subxt Block subscription 
    // type) and it ensures details line up. But whatever, can refine!
    fn from_block(period: u64, block: Block) -> Self;
}

impl ExtrinsicParams<T: Config> for CheckMortality<T::Hash> {
    type OtherParams = Mortality<T::Hash>;

    fn new<Client: OfflineClientT<T>>(
        nonce: u64,
        client: Client,
        other_params: Self::OtherParams,
    ) -> Result<Self, ParamsError> {
        Self {
            era: other_params.era,
            mortality: other_params.mortality.unwrap_or(client.genesis_hash())
        }
    }

    fn encode_extra_to(&self, v: &mut Vec<u8>) {
        self.era.encode_to(v)
    }
    fn encode_additional_to(&self, v: &mut Vec<u8>) {
        self.mortality.encode_to(v)
    }
}
```

And we can impl the trait to allow tuples of these things as you did.

The question here is; if we allow tuples of these things, can we avoid the user ending up with an interface like:

```rust
let mortality = Mortality::era(foo).checkpoint(bar);

// ew ugly tuple of OtherParams needed:
api.tx().sign_and_submit_then_watch(call, signer, ((), (), mortality, ...))
```

Because a bunch of signed extensions require no other params, they will have empty tuples like above, which is a bit sucky. I think that's fine though; devs could create wrappers easily enough for their chains like:

```rust
fn params(mortality: Mortality, foo: Foo) -> ((), (), Mortality, (), Foo) {
    ((), (), mortality, (), foo)
}

// and then:
api.tx().sign_and_submit_then_watch(call, signer, other_params(mortality, foo))
```

So if the APIs we provide for each individual signed extension are nice enough, it wouldn't be hard to have some wrapper function/builder-struct which just accepts those and returns the required tuple. (a crazy alternative here would be to have some clever trait that automatically got rid of all empty tuples in `OtherParams`; may be worth an experiment but probably adds too much complexity to be worth it!)

Our own Polkadot and Substrate configs could probably just use a signed extensions tuple, and then our `BaseExtrinsicParamsBuilder` could just have a `build()` function which outputs the tuple as needed, and otherwise provides the same sort of API it does at the moment.

I think this ultimately gives people the flexibility to compose signed extensions to get going easily, while still allowing for totally custom impls and nice wrappers to give nice APIs even for the "off the shelf" tuple combinations.

For dynamic params we are still good; a dynamic impl that would try to use sensible defaults etc would look a bit like:

```rust
pub struct DynamicExtrinsicParams<T> {
    // maybe we can have something like this; see below:
    signed_extensions: Vec<dyn ExtrinsicParams<T>>
}

impl <T: Config> ExtrinsicParams<T> for DynamicExtrinsicParams<T> {
    // accept arbitrary params from the user via a value type:
    type OtherParams = scale_value::Value;

    fn new<Client: OfflineClientT<T>>(
        nonce: u64,
        client: Client,
        other_params: Self::OtherParams,
    ) -> Result<Self, ParamsError> {
        let metadata = client.metadata();
        // use the metadata to see which signed extensions are in use on the chain.
        // With the help of our `signed_extensions` declared above, we can see which
        // values to look for in our `OtherParams`, construct the appropriate signed
        // extension, and then push it to a vec which we'll save:
        let mut signed_extensions = Vec::new();
        Self { signed_extensions }
    }

    // Just iterate the dynamic extensions in use and push out the bytes:
    fn encode_extra_to(&self, v: &mut Vec<u8>) {
        for ext in self.signed_extensions {
            ext.encode_extra_to(v)
        }
    }
    fn encode_additional_to(&self, v: &mut Vec<u8>) {
        for ext in self.signed_extensions {
            ext.encode_additional_to(v)
        }    
    }
}
```

All in all, I think the above trait keeps it fairly simple and gives devs maximum flexibility while still letting us implement everything that we could want :)

> Would it be possible to have a nice interface in which new() was async, and the client was OnlineClient potentially if the thing the config was used with was an OnlineClient?

I had a think about this and I think the answer is "no", or at least, it'd complicate the code somewhat etc. So let's ignore that idea for now!

**Comment by jsdw** [comment]
Another random thing so that I don't forget; it'd be really nice if you could provide an arbitrary tuple of extrinsic params and then have only the ones you actually need be encoded based on the metadata.

For this, something more like the separate `SignedExtension` trait where each extension has a name might be needed actually, so that we have a way to identify each one. Tuples of these would impl `ExtrinsicParams`, but the impl would use metadata to work out which are actually needed and in which order. Then, we could have one default impl which includes all extrinsic params and outputs a big tuple, and then only the ones actually needed are used.

**Comment by jsdw** [comment]
Closed by https://github.com/paritytech/subxt/pull/1107
