### ISSUE TITLE
SCALE VisitorDecodeError while using v.0.29.0

### ISSUE THREAD

**Issue by Retamogordo** [paritytech/subxt#1068]
Hi,
I'm getting a ```VisitorDecodeError``` while trying to parse an event of this structure: 
```rust
JobsAssigned {
	assigned_jobs: Vec<(T::JobId, Vec<T::AccountId>)>
},
```
where ```T::JobId``` is ```u64``` and ```T::AccountId``` is AccountId32 derived from sr25519.
Not sure subxt is responsible for this error, but oddly, the polkadot.org.js displays this event normally.
I use v.0.9.42 of Substrate. 
The event is deposited as a result of unsigned extrinsic with signed payload submitted by an Offchain Worker.
The generated code looks like this: 
```rust
pub struct JobsAssigned { 
    pub assigned_jobs : :: std :: vec :: Vec < (:: core :: primitive :: u64 , :: std :: vec :: Vec < :: subxt :: utils :: AccountId32 > ,) > , 
} 
impl :: subxt :: events :: StaticEvent for JobsAssigned { 
    const PALLET : & 'static str = "TrainingEngineSelection" ; 
    const EVENT : & 'static str = "JobsAssigned" ; 
} 
// snip
# [codec (index = 1)] 
JobsAssigned { 
    assigned_jobs : :: std :: vec :: Vec < (:: core :: primitive :: u64 , :: std :: vec :: Vec < :: subxt :: utils :: AccountId32 > ,) > , 
} , 
//snip
# [derive (:: subxt :: ext :: codec :: Decode , :: subxt :: ext :: codec :: Encode , :: subxt :: ext :: scale_decode :: DecodeAsType , :: subxt :: ext :: scale_encode :: EncodeAsType , Debug)] 
# [decode_as_type (crate_path = ":: subxt :: ext :: scale_decode")] 
# [encode_as_type (crate_path = ":: subxt :: ext :: scale_encode")] 
pub struct JobsAssignedPayload < _0 , _1 , _2 , _3 > { 
    pub block_number : _1 , 
    pub public : _0 , 
    pub assigned_jobs : :: std :: vec :: Vec < (_1 , :: std :: vec :: Vec < _3 > ,) > , 
    # [codec (skip)] 
    pub __subxt_unused_type_params : :: core :: marker :: PhantomData < _2 > 
} 
```

**Comment by tadeohepperle** [comment]
Hey @Retamogordo I was not able to reproduce the issue. What function do you use to decode the event bytes? Could you provide a minimal example project, where the error occurs?

**Comment by Retamogordo** [comment]
@ tadeohepperle, thank you for your reply.
I have just uncommented this code out to try it once again and now it seems to work.
So it's likely a false alarm from my party although the nature of this phenomenon is unclear to me as I'm sure I ran 
´´´subxt metadata -f bytes > metadata.scale´´´
a couple of times to be sure that metadata is up to date.
Closing for now.
