### ISSUE TITLE
How to declare metadata version

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/subxt#1091]
I am getting this error on upgrading from v0.29.0 to v0.30.0. I assume that it defaults to V15 metadata, but the runtimes it is calling do not return this. Can I declare V14 metadata, or does the metadata returned have a way to tell subxt which version it is?
```
error: Could not decode metadata, only V14 and V15 metadata are supported: Could not decode `RuntimeMetadataPrefixed.1`:
           Could not decode `RuntimeMetadata::V15.0`:
               Could not decode `RuntimeMetadataV15::extrinsic`:
                   Could not decode `ExtrinsicMetadata::extra_ty`:
                       Could not decode `UntrackedSymbol::id`:
                           out of range decoding Compact<u32>
 --> src/types.rs:3:1
  |
3 | / #[subxt::subxt(
4 | |     runtime_metadata_url = "wss://kusama-rpc.polkadot.io:443",
5 | |     derive_for_all_types = "PartialEq, Clone"
6 | | )]
  | |__^
  |
  = note: this error originates in the attribute macro `subxt::subxt` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by jsdw** [comment]
Can I check; which feature flags do you compile subxt with?

**Comment by joepetrowski** [comment]
https://github.com/joepetrowski/opengov-cli/pull/12

**Comment by jsdw** [comment]
Ah I think I see the issue; the "fetching from url" code tries to fetch unstable first and then latest stable:

https://github.com/paritytech/subxt/blob/44b1690170cab9a77e920a8bd713e247ddaf6254/codegen/src/api/mod.rs#L98

it should now try to fetch V15 and then V14; it must have been missed when we stabilised V15. We'll fix this tomorrow and put a patch release out!

The workaround (and suggested approach anyway) is to download the metadata you want to use from the node (eg using the subxt cli tool) and then point to that. Nice side effects of this include faster compile times and no network access needed for compiling :)

Thanks for the quick report!!
