### ISSUE TITLE
`SUBSTRATE_NODE_PATH` should default or accept `substrate-node`

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/subxt#1095]
Following the instructions here: https://github.com/paritytech/subxt/tree/master#integration-testing, substrate is actually installed as `substrate-node` rather than `substrate`, so running the examples would just fail. Recommendation would be to accept both `substrate` and `substrate-node` as possible binaries paths or add instructions to rename the binary.

**Comment by jsdw** [comment]
Ooh interesting; perhaps it was recently renamed; thanks for bringing this up!
