### ISSUE TITLE
Dispatch Error example

### ISSUE THREAD

**Issue by amiyatulu** [paritytech/subxt#1099]
Subxt docs provides example to get events,  https://github.com/paritytech/subxt/blob/master/subxt/examples/tx_status_stream.rs but couldn't find how to get error or dispatch error of the transaction. How to get and print dispatch error? 
I tried this code:
```rust
let events = in_block.wait_for_success().await;
     match events{
                Ok(e) => {},
                  Err(e) =>{gloo::console::log!(e.to_string())},
       }
```
but e.to_string() doesn't provide pretty printed dispatch error. 

In javascript we do in this way:
```javascript
     .signAndSend(pair, ({ status, dispatchError }) => {
                    if (dispatchError) {
                        if (dispatchError.isModule) {
                            const decoded = api.registry.findMetaError(dispatchError.asModule);
                            const { docs, name, section } = decoded;
                            log!(`Error ${section}.${name}: ${docs.join(' ')}`);

```

**Comment by lexnv** [comment]
Hey, regarding the `DispatchError` we have a few tests that might be useful for you here:

https://github.com/paritytech/subxt/blob/adad9f8860ada786eb860de68f76803c043956ec/testing/integration-tests/src/full_client/frame/staking.rs#L68-L78

The `wait_for_finalized_success` or `wait_for_success` are similar for the purpose of fetching the module error here.

---
Going one step beyond that, you could also decode the bytes of `DispatchError::Module(bytes)` to the `codegen::Error` type.

```rust
// Step 1. generate the interface
#[subxt::subxt(...)]
pub mod polkadot {}

// Step 2. use `polkadot::Error` to decode `DispatchError::Module(bytes)` into something more usable

```

From our generated interface:
```
    #[doc = r" The outer error enum representing the DispatchError's Module variant."]
    pub type Error = runtime_types::polkadot_runtime::RuntimeError;
```

**Comment by jsdw** [comment]
Linking the issue we have to add docs for errors: #1045 

I'll close this for now but @amiyatulu feel free to re-open if you still have issues here :)
