### ISSUE TITLE
How to know if a block is finalized?

### ISSUE THREAD

**Issue by f-squirrel** [paritytech/subxt#1114]
I receive blocks via `client.blocks().at(block_hash).await?` and need to check if the block is finalized.
I did not find a field that would tell me if the block was finalized.
Unfortunately, I cannot subscribe to the finalized blocks.

**Comment by f-squirrel** [comment]
@jsdw , my node provider does not provide websocket interface https://github.com/paritytech/subxt/issues/1033.

**Comment by jsdw** [comment]
I had a look through the storage entries and runtime API calls on https://polkadot.js.org/apps/#/chainstate and offhand I can't see anything that says whether some block has been finalized, but I may very well be missing something!

My best suggestion is to ask on https://substrate.stackexchange.com/ how to find out via the RPC APIs whether some block is finalized; somebody else may know the answer :)

In general though, as I said on that issue, Subxt relies fairly heavily on being able to use a websocket based interface, and will rely even more heavily on this fact when it migrates over to the new V2 RPC interface being built (see https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html), so you wo't really being able to rely on an HTTP-only RPC provider in the long run for most things.

**Comment by jsdw** [comment]
I'll close this for now as I don't think we can be of more help on this one :)
