### ISSUE TITLE
Subxt-0.31 error on jsonrpsee_helpers

### ISSUE THREAD

**Issue by amiyatulu** [paritytech/subxt#1138]
Subxt 0.31 gives following error on cargo check in wasm

```
error[E0433]: failed to resolve: use of undeclared crate or module `jsonrpsee_helpers`
  --> /home/amiya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/subxt-0.31.0/src/client/online_client.rs:60:18
   |
60 |     let client = jsonrpsee_helpers::client(url.as_ref())
   |                  ^^^^^^^^^^^^^^^^^ use of undeclared crate or module `jsonrpsee_helpers`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `subxt` (lib) due to previous error

```

subxt = { version="0.31.0", default-features = false, features = ["jsonrpsee", "web"], target_arch = "wasm32"}
subxt-signer = { version="0.31.0", default-features = false, features = ["web", "sr25519", "ecdsa", "subxt"] }

**Comment by amiyatulu** [comment]
Error disappears with: 

[build]
target = "wasm32-unknown-unknown"

**Comment by niklasad1** [comment]
yeah, it should but you must either compile at with `cargo check --target wasm32-unknown-unknown` or add the target in your cargo config file as default

It's really jsonrpsee's fault with the `target_arch` stuff which can be tricky to detect...
