### ISSUE TITLE
Strange behavior calling a ink! contract using subxt

### ISSUE THREAD

**Issue by gcp-development** [paritytech/subxt#1140]
I am using this [example](https://github.com/paritytech/subxt/blob/master/testing/integration-tests/src/full_client/frame/contracts.rs#L146) to call a contract.

I am using the below instructions to pass an argument:
(Note:I have try the name of the function also.)
```
 let mut input_data = Vec::<u8>::new();
 input_data.append(&mut (&blake2_256("0x633aa551".as_bytes())[..]).to_vec());
```
My ABI json of the function that I am calling.(This is the [flipper](https://github.com/paritytech/ink-examples/tree/main/flipper) example)

```
    "messages": [
      {
        "args": [],
        "default": false,
        "docs": [
          " Flips the current value of the Flipper's boolean."
        ],
        "label": "flip",
        "mutates": true,
        "payable": false,
        "returnType": {
          "displayName": [
            "ink",
            "MessageResult"
          ],
          "type": 1
        },
        "selector": "0x633aa551"
      }
    ]
```

Probably I am doing something wrong , but I am not able to make a call to that function. 

It gives an error like this:
(this is only the first block)

![image](https://github.com/paritytech/subxt/assets/76512851/793b7c6c-c4a8-4415-b81a-c69a8b8f0d5c)

**Comment by gcp-development** [comment]
Hi, @tadeohepperle 

I have created a repo in[ here](https://github.com/gcp-development/dummy-contract).

I am "cruising" in a ubuntu. 

![image](https://github.com/paritytech/subxt/assets/76512851/6c22f5b3-9f91-4210-865a-b282fb73acb3)


``
rustup show
``

![image](https://github.com/paritytech/subxt/assets/76512851/bb5b0aff-8036-4982-8cd3-12be7c50b715)


Cheers,

**Comment by lexnv** [comment]
Hey,

I'm running into some issues reproducing this. From my side, the failure comes from `let uri = SecretUri::from_str(DEVICE_ACCOUNT_SEEDS).expect("valid URI");`.

Could you provide the complete `ModuleError` in text? (from the issue description)

Thanks,
Alex

**Comment by gcp-development** [comment]
Hi @lexnv ,

could you tell me what is the error that is coming up for you, please ?

The dump of the error is in [here](https://github.com/gcp-development/dummy-contract/blob/main/error.txt)

Cheers,

**Comment by gcp-development** [comment]
Hello, @lexnv, @tadeohepperle, @jsdw 

I hope all is well.

Any update on this ?

Cheers,

**Comment by lexnv** [comment]
Hey, apologies for the delay, the `ModuleError` has two components:
- metadata
- bytes error coming from substrate 

The provided bytes `bytes: [40, 2, 0, 0, 0]`  are broken into:
- first byte: pallet index (40)
- second byte: error index (2)
- last 3 bytes: specific error data (0 0 0 in this case)

Then by looking at the provided metadata, we are able to identify the following:
- `PalletMetadataInner { name: "Contracts", index: 40, .. error_ty: Some(285)}` which is the pallet from which the error is originated
- Inspecting the type from the portable registry we obtain 

```
PortableType {
    id: 285,
    ty: Type { path: Path { segments: ["pallet_contracts", "pallet", "Error"] },
    type_params: [TypeParameter { name: "T", ty: None }],
    type_def: Variant(TypeDefVariant { variants: [
        Variant { name: "InvalidScheduleVersion", fields: [], index: 0, docs: ["A new schedule must have a greater version than the current one."] },
        Variant { name: "InvalidCallFlags", fields: [], index: 1, docs: ["Invalid combination of flags supplied to `seal_call` or `seal_delegate_call`."] },
        Variant { name: "OutOfGas", fields: [], index: 2, docs: ["The executed contract exhausted its gas limit."] },
        Variant { name: "OutputBufferTooSmall", fields: [], index: 3, docs: ["The output buffer supplied to a contract API call was too small."] },
        ..
```

In this case, the error comes from the `Contracts` pallet and is an `OutOfGas` error.

That hints to me that the weight you provided for your contract needs to be increased, let me know if this sets you up on the right path 🙏

**Comment by ascjones** [comment]
See https://github.com/paritytech/subxt/pull/1153 for improved `Debug` output which will resolve the error correctly.

@gcp-development if it says `OutOfGas` then that is what it is. Try increasing it even more!

**Comment by gcp-development** [comment]
Hi @ascjones , @lexnv 

We have increased for 5 times the initial amount and it worked...... :+1:
