### ISSUE TITLE
How to use custom origin in subxt?

### ISSUE THREAD

**Issue by amiyatulu** [paritytech/subxt#1214]
In [referenda](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/referenda/src/lib.rs#L453) pallet it uses custom origin (proposal_origin here)

```rust
                #[pallet::call_index(0)]
		#[pallet::weight(T::WeightInfo::submit())]
		pub fn submit(
			origin: OriginFor<T>,
			proposal_origin: Box<PalletsOriginOf<T>>,
			proposal: BoundedCallOf<T, I>,
			enactment_moment: DispatchTime<BlockNumberFor<T>>,
		) -> DispatchResult {
```

How can I call the function in subxt, using the custom origin proposal_origin, also [proposal](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/referenda/src/mock.rs#L308)?

**Comment by niklasad1** [comment]
Example code

```rust
    let proposal_origin: runtime_types::polkadot_runtime::OriginCaller = runtime_types::polkadot_runtime::OriginCaller::system(
        runtime_types::frame_support::dispatch::RawOrigin::Root,
    );
```

Try our exploring tool for call examples: https://paritytech.github.io/subxt-explorer but it may useful to use the dynamic API if you want to support several chains.

**Comment by jsdw** [comment]
I'm going to assume that this is fixed and close for now; pelase re-open if this is still an issue!
