### ISSUE TITLE
Trying to execute `unstable_light_client_tx_basic`

### ISSUE THREAD

**Issue by Daanvdplas** [paritytech/subxt#1222]
Trying to run `unstable_light_client_tx_basic` with the following command:
```cargo run --features="unstable-light-client jsonrpsee" --example unstable_light_client_tx_basic```

However I get the error: 
<img width="1400" alt="Screenshot 2023-10-23 at 16 01 16" src="https://github.com/paritytech/subxt/assets/93204684/fc67d708-6a90-4094-9682-176b915bc2ce">

**Comment by jsdw** [comment]
Use `cargo run --features=unstable-light-client --example unstable_light_client_tx_basic` instead; the docs aren't quite right there; I'll fix them :)
