### ISSUE TITLE
Can we simplify some of the references to generated types, so it's easier to name them?

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#1242]
See for example this code:

https://github.com/lovelaced/polkadot-locks-report/blob/21845912f785dea014599940820a9dc922c9477a/src/main.rs#L566

Let's have a go at taking this code and seeing how we can simplify the types! Maybe we can simplify them, in which case it might be good to show this in our examples a bit better, or maybe we can't and we can tweak the codegen to expose type aliases for the return types of known queries (@lexnv I know you had this idea at some point)!

**Comment by lexnv** [comment]
Closed by https://github.com/paritytech/subxt/pull/1249
