### ISSUE TITLE
Iterating over StorageDoubleMap with partial keys not working

### ISSUE THREAD

**Issue by 5tan-enj** [paritytech/subxt#1251]
Problem :
Trying to fetch values from a StorageDoubleMap by supplying only a partial key, the result still returns all values in storage

### Example :

Code : 
```
pub async fn calculate_pool_data(pool_id : u32, era: u32) -> Result<(), Box<dyn std::error::Error>> {
	let relay_client = RelayClient::from_url("wss://rpc.relay.blockchain.enjin.io:443").await?;

	// get unbonding members
	let unbonding_members = {
		let query = relay::storage().nomination_pools().unbonding_members_iter1(6u32);
		let mut results = relay_client.storage().at_latest().await?.iter(query).await?;

		let mut unbonding_members = HashMap::new();
		while let Some(Ok((key, prefs))) = results.next().await {
			unbonding_members.insert(key, prefs);
		}
		unbonding_members
	};

	println!("Unbonding members {:?}", unbonding_members.len());

	Ok(())

}
```

Output : 
```
Unbonding members 109
```

Expected Output :
1 (there is only one unbonding member)

<img width="968" alt="Screenshot 2023-11-10 at 9 03 51 AM" src="https://github.com/paritytech/subxt/assets/108918792/868b0f47-f3b1-4169-b3b1-92ee668864e1">

**Comment by jsdw** [comment]
Thankyou for raising this; that is unexpected! We'll look into it!

**Comment by lexnv** [comment]
I was able to reproduce this issue on the following branch: https://github.com/paritytech/subxt/compare/lexnv/repro-case-1251?expand=1. 

Indeed there seems to be a mismatch, most probably due to constructing the query differently.
