### ISSUE TITLE
LightClient: Higher level API for multi-chain usecase

### ISSUE THREAD

**Issue by lexnv** [paritytech/subxt#1253]
We currently have:
- high level API for targeting just one chain
- very low level API for gaining control to the smoldot client

We would like to introduce something in between, that would allow users to easily build a multichain smoldot client without having to understand the low-level API.

For more context:  https://github.com/paritytech/subxt/pull/1238#discussion_r1389402241

> let client: MediumLightClient  = MediumLightClient::builder()
    .add_chain(
         AddChianBuilder::with_identifier( "polkadot" )
             .with_spec( include_str!( "../assets/polkadot_chain_spec.json")
    )
    .add_chain(
         AddChainBuilder::with_identifier( "asset-hub")
            .relay_chain( "polkadot")
            .from_url("ws://127.0.0.1:9944")
     )
    .build().await;
let polkadot_api = client.for_chain( "polkadot");

**Comment by jsdw** [comment]
Closed by #1475 I think :)
