### ISSUE TITLE
Unable to create SessionKeys struct instance to submit pallet_session::set_keys() extrinsic

### ISSUE THREAD

**Issue by akhiln28** [paritytech/subxt#1261]
I have generated the session keys using the `author.rotateKeys()` RPC call. The keys are of type `Vec<u8>` and the length is 128 bytes.

I am trying to call the `set_keys()` method from `pallet_session` to a substrate node. I am using `subxt` for submitting extrinsics and I have generated a `.scale` file for interfacing. Now I am not sure how to create `SessionKeys` struct using the 128 bytes. When I hover over the SessionKeys struct I can see the following

```rs
pub struct SessionKeys {
    pub grandpa: Public,
    pub babe: Public,
    pub im_online: Public,
    pub authority_discovery: Public,
} // size = 128 (0x80), align = 0x1
```
I can't see `Public` struct. How to instantiate it?

Also in runtime, i can see the following

```rs
impl_opaque_keys! {
pub struct SessionKeys {
    pub grandpa: Grandpa,
    pub babe: Babe,
    pub im_online: ImOnline,
    pub authority_discovery: AuthorityDiscovery,
}
}
```

I can submit the extrinsic from polkadot ui as shown below 
![](https://github.com/paritytech/subxt/assets/24193184/35f3f705-fb88-4624-afd6-e03df38108f5)

How to convert a 128 bytes string into a SessionKeys struct?

```rs
let grandpa: substrate::runtime_types::sp_consensus_grandpa::app::Public =
    substrate::runtime_types::sp_consensus_grandpa::app::Public::from(keys[0..32].to_vec());
let babe: substrate::runtime_types::sp_consensus_babe::app::Public =
    substrate::runtime_types::sp_consensus_babe::app::Public::from(keys[32..64].to_vec());
let im_online: substrate::runtime_types::sp_im_online::app::Public =
    substrate::runtime_types::sp_im_online::app::Public::from(keys[64..96].to_vec());
let authority_discovery: substrate::runtime_types::sp_authority_discovery::app::Public =
    substrate::runtime_types::sp_authority_discovery::app::Public::from(keys[96..128].to_vec());
```

```rs
error[E0308]: mismatched types
   --> main/src/substrate.rs:98:75
    |
98  |         substrate::runtime_types::sp_consensus_grandpa::app::Public::from(keys[0..32].to_vec());
    |         ----------------------------------------------------------------- ^^^^^^^^^^^^^^^^^^^^ expected `Public`, found `Vec<u8>`
    |         |
    |         arguments to this function are incorrect
    |
    = note: expected struct `sp_consensus_grandpa::app::Public`
               found struct `Vec<u8>`
```

It is expecting a `Public` struct but I am passing a `Vec<u8>`. But how can I create a `Public` struct from a `Vec<u8>`?

Posted the same questions on [stackexchange](https://substrate.stackexchange.com/questions/10453/subxt-how-to-submit-pallet-sessionset-keys-extrinsic)

```[tasklist]
### Tasks
```

**Comment by niklasad1** [comment]
Have a look https://paritytech.github.io/subxt-explorer/#/pallets/Session/calls?url=wss%3A%2F%2Frpc.polkadot.io how to create the `Public type` that is generated by subxt.

However, it may be easier for you to substitute the `Public type` with the public type from substrate:

```rust
#[subxt::subxt(
    runtime_metadata_path = "metadata.scale",
    substitute_type(
        path = "runtime_types::sp_consensus_grandpa::app::Public",
        with = "Public"
    )
    substitute_type(
        path = "runtime_types::sp_consensus_grandpa::app::Public",
        with = "Public"
    )
)]
pub mod node_runtime {}
```

You need to substitute all params in SessionKeys generated but I'm to lazy to do in the example above.

**Comment by akhiln28** [comment]
Thanks for the quick response, it is working. And subxt explorer looks very helpful.
