### ISSUE TITLE
workflow: Update artifacts automatically

### ISSUE THREAD

**Issue by lexnv** [paritytech/subxt#1296]
Create a workflow that runs the `scripts/artifacts.sh` file to update:
- metadata scale
- polkadot.rs codegen interface from testing
- demo chain specs

The changes should be pushed as a commit for us to review, with weekly frequency.

The advantage of doing this is that we'll never have to worry about manually updating those files.
In the past, we have added features to the `codegen` that were not reflected in the artifacts files. 
Also, the demo `chainSpec` plays a huge role in the synchronization time of the light clients.

This should be done after:
- https://github.com/paritytech/subxt/issues/1263

**Comment by jsdw** [comment]
I like this idea, and also it's another way to spot compatibility issues (updating the polkadot_metadata could break docs/example code etc)
