### ISSUE TITLE
Unstable backend test failure

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#1308]
There appears to be a new unstable backend test failure:

https://github.com/paritytech/subxt/actions/runs/7089806307/job/19295367538

I wonder whether this is the result of https://github.com/paritytech/subxt/pull/1305, or otherwise just another intermittent issue not addressed properly by that.

**Comment by lexnv** [comment]
The test seem to timeout after a very long time, which may happen if:
- tx finalized hash is older than whatever chainHead has reported
- chainHead or backend produces a Finalized event; then a NewBlock event for the same hash (out of order)
- we somehow clear the seen hashes incorrectly, which loses track of the finalized block
https://github.com/paritytech/subxt/blob/cc5c78a921f28ede53284ab56dc9e6b1ade3bcc2/subxt/src/backend/unstable/mod.rs#L469

**Comment by jsdw** [comment]
Yeahh, lemme look into it a bit; I do feel like it's likely to have been introduced by that recent fix!

**Comment by lexnv** [comment]
Other failures possibly related to this:
- https://github.com/paritytech/subxt/actions/runs/7165550289/job/19507726478
- https://github.com/paritytech/subxt/actions/runs/7166080771/job/19509347216

**Comment by jsdw** [comment]
I think we addressed this now so I'll close and we can re-open if more issues :)
