### ISSUE TITLE
v032.1 CheckNonZeroSender is not exported in `signed_extensions`

### ISSUE THREAD

**Issue by kylezs** [paritytech/subxt#1381]
In the book example here `subxt/src/book/setup/config.rs` under `ExtrinsicParams` it uses this `SignedExtra` type as an example:

```rust
//! pub type SignedExtra = (
//!     frame_system::CheckNonZeroSender<Runtime>,
//!     frame_system::CheckSpecVersion<Runtime>,
//!     frame_system::CheckTxVersion<Runtime>,
//!     frame_system::CheckGenesis<Runtime>,
//!     frame_system::CheckEra<Runtime>,
//!     frame_system::CheckNonce<Runtime>,
//!     frame_system::CheckWeight<Runtime>,
//!     pallet_asset_tx_payment::ChargeAssetTxPayment<Runtime>,
//! );
```

However, in the example of what it looks like to write a subxt config for it, `CheckNonZeroSender` is not included, and it's not included in `signed_extension` at all. 

I noticed that the extrinsics submit and validate correctly without this extension (where as they weren't before I created a custom extrinsic params for the config. So I'm wondering why the CheckNonZeroSender is omitted here?

**Comment by jsdw** [comment]
Some signed extensions make no difference to the actual shape of the TX payload or the payload that needs signing to validate a TX. Subxt will happily skip over any such extension (using the metadata to determine which of them add nothing to tx or payload).

As such, a few extensions like `CheckNonZeroSender` are not required by Subxt.

**Comment by kylezs** [comment]
Ok figured as much, thanks!
