### ISSUE TITLE
improve events subscriptions

### ISSUE THREAD

**Issue by 4meta5** [paritytech/subxt#141]
Might be nice to have a higher level api for subscribing to a particular event type and doing the decoding, but no need for this PR

_Originally posted by @ascjones in https://github.com/paritytech/substrate-subxt/pull/126#discussion_r444773385

We need an iterator-like API for subscribing to events for @sunshine-protocol CC @dvc94ch

**Comment by dvc94ch** [comment]
@ascjones any progress on dynamic event decoding using scale-info?

**Comment by ascjones** [comment]
No. It depends on integrating `scale-info` with substrate which I haven't even started yet. I'm busy with `ink! 3.0` work atm but will see if I can block out some time to look into it.

**Comment by dvc94ch** [comment]
Any progress? We need more sophisticated event subscriptions, and without this, they won't work very reliably.

**Comment by ascjones** [comment]
@dvc94ch I've started experimenting with this: I'm part way through implementing SCALE encoding for `scale-info` here: https://github.com/paritytech/scale-info/pull/19.

I'll do some more on it next week and let you know how I progress.

**Comment by jsdw** [comment]
We have this now, and in the not distant future we'll start relyong on `scale_value` and so may provide back Value's for unknown events rather than skipping over the bytes, for more flexibility (but also for more robust/deduplicated decode logic)
