### ISSUE TITLE
cargo install subxt-cli doesn't work

### ISSUE THREAD

**Issue by Daanvdplas** [paritytech/subxt#1462]
`Rustup show`:

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-2023-11-28-aarch64-apple-darwin
nightly-2023-12-11-aarch64-apple-darwin
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

stable-aarch64-apple-darwin (overridden by '/Users/R0GUE/Documents/Pop/pop-node/rust-toolchain.toml')
rustc 1.76.0 (07dca489a 2024-02-04)

![Screenshot 2024-03-01 at 15 15 56](https://github.com/paritytech/subxt/assets/93204684/7c083305-9f33-4437-ae19-ed227a6660be)

**Comment by niklasad1** [comment]
oh, I think we need to set `scale_typegen_description "=0.1.1"` because actually  `scale_typegen_description v0.1.2` is breaking release and bump scale_value?

//cc @tadeohepperle can we yank  `scale_typegen_description v0.1.2` and release ` scale_typegen_description v0.2.0` instead?

**Comment by niklasad1** [comment]
This is fixed by https://github.com/paritytech/scale-typegen/pull/17

Should work again now
