### ISSUE TITLE
Make subxt-codegen and subxt-macro usable in no-std context.

### ISSUE THREAD

**Issue by tadeohepperle** [paritytech/subxt#1479]
Currently the codegen and the macro crate refer to `subxt` for certain type paths, even though all of them should be available in `subxt-core`. It would be nice to demonstrate that the subxt-macro can be used to generate a static interface in a `no-std` context, that can be used to e.g. look up constants.

**Comment by jsdw** [comment]
I think this is all done and working now, but would be nice to verify it! Perhaps have a go at writing a little example crate in subxt/examples which uses `subxt-core`, `subxt-signer` and the `#[subxt]` macro with `#[no_std]`, and can eg construct and sign some transaction?

Then add CI to check that we can compile this in `subxt/.github/rust.yml`.

**Comment by pkhry** [comment]
The macro is usable in no-std contexts and there is a test for it already in place. in the [codebase](https://github.com/paritytech/subxt/blob/pkhry/unstable_backend_tests/testing/no-std-tests/src/main.rs) and CI
