### ISSUE TITLE
Rpc(ClientError(Transport(Failed to load system certs: No valid certificate found)))-[xtensa-esp32s3-espidf]

### ISSUE THREAD

**Issue by blue-freedom-technologies** [paritytech/subxt#1499]
There is any way(or roadmap plan) of using the [webpki-roots](https://github.com/rustls/webpki-roots) instead of the [rustls-native-certs](https://github.com/rustls/rustls-native-certs)  for the code below?

```rust
let connection = OnlineClient::<PolkadotConfig>::from_url("wss://rococo-contracts-rpc.polkadot.io:443").await;
 match connection {
         Ok(_api) => {
                info!("Connection ok");
          }
         Err(err) => {
               info!("Connection error: {:?}", err);
          }
 }
```

cargo.toml
```rust
subxt = { git = "https://github.com/paritytech/subxt.git", branch="master" , default-features = false, features = ["native","unstable-metadata","jsonrpsee"] }
```

native feature
```rust
native = [
    "jsonrpsee?/async-client",
    "jsonrpsee?/client-ws-transport-native-tls",
    "subxt-lightclient?/native",
    "tokio-util"
]
```

Cheers,

**Comment by niklasad1** [comment]
You could actually workaround that easily by creating the rpc client yourself with desired configuration and pass to subxt:

```toml
  [dependencies]
  jsonrpsee-ws-client = { version = "0.22", no-default-features = true, features = ["webpki-tls"]
  subxt = "0.34"
```

```rust
use jsonrpsee_ws_client::WsClientBuilder;
use subxt::{backend::rpc::RpcClient, OnlineClient, PolkadotConfig};

#[tokio::main]
async fn main() {
    // use webpki roots
    let rpc = WsClientBuilder::default()
        .use_webpki_rustls()
        .build("ws://localhost:9944")
        .await
        .unwrap();

    let subxt: OnlineClient<PolkadotConfig> = OnlineClient::from_rpc_client(RpcClient::new(rpc))
        .await
        .unwrap();

    // sub
}
```

**Comment by blue-freedom-technologies** [comment]
Hi @niklasad1,

Yes, that is more or less, the horrible workaround that we are currently using(in our case the Transport have to use the webpki-roots also).

```rust
    let (sender, receiver) = WsTransportClientBuilder::default()
          .use_webpki_rustls()
          .build(Url::parse("wss://rococo-contracts-rpc.polkadot.io:443").unwrap())
          .await.expect("TODO: panic message");

    let ws_client = WsClientBuilder::default()
            .use_webpki_rustls()
            .build_with_transport(sender, receiver);

    let rpc_client = RpcClient::new(ws_client);
    let connection = OnlineClient::<PolkadotConfig>::from_rpc_client(rpc_client.clone()).await;
```

Thanks,

**Comment by jsdw** [comment]
Not having looked into this, I'm wondering: do our defaults (using [rustls-native-certs](https://github.com/rustls/rustls-native-certs)) make sense in general?

If so, then I think the correct approach to customise them is exactly the above; configure your own RPC client exactly as you'd prefer and use that to instantiate an `OnlineClient` (or `Backend` impl if you want to also choose/configure the backend). Then, the "easy path" uses sensible defaults/settings, but each layer (RPC client, backend) can be configured manually as needed.

**Comment by niklasad1** [comment]
> Not having looked into this, I'm wondering: do our defaults (using [rustls-native-certs](https://github.com/rustls/rustls-native-certs)) make sense in general?

I think so https://github.com/rustls/rustls-native-certs?tab=readme-ov-file#should-i-use-this-or-webpki-roots i.e, webpki-roots must be recompiled to handle new certificates etc... It isn't such a big deal but requires to recompile subxt and update webpki roots.

Thus, I think rust-native-certs is a better default than webpki-roots....

**Comment by jsdw** [comment]
Thanks for the very informative reply @blue-freedom-technologies!

Given this, let's close this issue for now since I believe our defaults are OK at the moment, but we can look to re-evaluate these things in the future if other issues crop up!
