### ISSUE TITLE
Example of simple extrinsics Template Module function doSomething()

### ISSUE THREAD

**Issue by AhmedX6** [paritytech/subxt#1516]
Hello everyone,

i'm struggeling, how to send a simple extrinsics to my dev node running locally using subxt

```
let api = OnlineClient::<PolkadotConfig>::from_url("ws://127.0.0.1:9944").await.unwrap();
                println!("Connection with parachain established.");

                let alice: MultiAddress<AccountId32, ()> = dev::alice().public_key().into();
                let alice_pair_signer = dev::alice();

                let balance_transfer_tx = tx("TemplateModule", "do_something", Composite::from(Primitive::from(32)));

                api.tx().sign_and_submit_then_watch_default(&balance_transfer_tx, &alice_pair_signer).await
                    .map(|e| {
                        println!("Collection creation submitted, waiting for transaction to be finalized...");
                        e
                    }).expect("something wrong")
                    .wait_for_finalized_success()
                    .await.expect("no success");
```

I'm able to connect to node dev locally but just how to call the pallet using simple extrinsics..
There is no sample at all for this and I can't understand how it works.

This code is not compiling failing on the Composite parameter.. I don't know how to pass a simple u32 value..

Can someone help ?

Thanks

**Comment by jsdw** [comment]
Hello!

Have you seen the docs yet: https://docs.rs/subxt/latest/subxt/

Specifically the docs on trasnactions might be helpful: https://docs.rs/subxt/latest/subxt/book/usage/transactions/index.html

For your specific case, it appears that you're trying to construct a transaction without using the statically generated interface (ie `tx("TemplateModule", "do_something", Composite::from(Primitive::from(32)));`) though it would help to see what your imports are. To build a valid composite containing just a single integer you can do something like:

```rust
Composite::unnamed([ Value::u128(32 as u128) ])
```

or you can use the macro in `scale-value` to do something like (untested):

```rust
use scale_value::value;

value!{ (32) }
```

**Comment by AhmedX6** [comment]
Hi @jsdw 

thanks for your answer, it seems that you helped me a lot with those few lines.
Yes I saw these documentations, but it's like it uses Builder for preconfigured pallets in the SDK. But if I want to implement my own pallet and call it in a generic way like that:

call("pallet_name", "function_name", params...)

I did not see any example.

Or maybe I missed something but that's my comprehension of the concept.

So now If I add to my node-template-dev a new pallet with a new function name in the runtime, I should be able to call it that way isn't it ?

**Comment by niklasad1** [comment]
> So now If I add to my node-template-dev a new pallet with a new function name in the runtime, I should be able to call it that way isn't it ?

Yes but it's probably worth to double check that you got the naming of your pallet correct when you call in the dynamic API such that is call("MyPallet", "SomeApi", params)

To me it seems easier just to fetch the metadata from your "node-template-dev node" and generated a static codegen interface that you can use in subxt.

```
$ ./run-template-node &
$ subxt metadata --version latest -f bytes > artifacts/metadata.scale
$ cargo clean && cargo build
```

Then you change your code to use the static interface your should be able to find the added pallet in the subxt codegen.

Alternatively, do to inspect the codegen

```bash
 $ subxt codegen --file metadata.scale | rustfmt > code.rs
```

**Comment by AhmedX6** [comment]
Thanks for yo answer guys.
