### ISSUE TITLE
ci: Change auto-updated artifacts secret

### ISSUE THREAD

**Issue by lexnv** [paritytech/subxt#1575]
The secret used to automatically update the artifacts was created a while ago by Tadeo. Because of this, Tadeo is added as a co-author to the PR created by our scripts: https://github.com/paritytech/subxt/pull/1569.

To change this, we'd have to go to Settings > Secrets and recreate the `SUBXT_PR_MAKER_APP_ID`, but I don't have permissions to do so (maybe we need to get in contact with the CI team):

https://github.com/paritytech/subxt/blob/f034ac486cb04667934a5399e564b8e877e96c5d/.github/workflows/update-artifacts.yml#L44-L48

**Comment by jsdw** [comment]
Ooh, yeah I can update the secret ; I guess only to my own key or something like that unless the CI guys can give us a better one :)

**Comment by niklasad1** [comment]
I have opened a request to generate separate access token for subxt to fix this

**Comment by niklasad1** [comment]
Done but I'm the co-author of the PR now.

It seems that someone has to be co-author of the PR, see https://github.com/orgs/community/discussions/47855
