### ISSUE TITLE
`AccountId20` does not implement `Serialize`

### ISSUE THREAD

**Issue by muraca** [paritytech/subxt#1576]
I wanted to use the following legacy method to retrieve nonces from transaction pool, however the `AccountId20` type does not implement Serialize. 

https://github.com/paritytech/subxt/blob/f034ac486cb04667934a5399e564b8e877e96c5d/subxt/src/backend/legacy/rpc_methods.rs#L140-L150

I noticed that the `subxt-signer` crate does not depend on `serde`, and I'm not sure if you want to ever support this, therefore I'm opening this issue rather than a PR. 

In the meantime, for anyone who might incur in the same issue, my solution was to use a custom `AccountId20` type and make it compatible with the `subxt_signer::eth::Signature` type by implementing `From<subxt_signer::eth::AccountId20>`.
```rust
/// A 20-byte cryptographic identifier.
// We need this because subxt's AccountId20 does not implement Serialize.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Encode, Decode, serde::Serialize)]
pub struct AccountId20([u8; 20]);

impl From<subxt_signer::eth::AccountId20> for AccountId20 {
    fn from(value: subxt_signer::eth::AccountId20) -> Self {
        AccountId20(value.0)
    }
}

impl Config for MyConfig {
    // ... 
    type AccountId = AccountId20;
    type Address = AccountId20;
    type Signature = subxt_signer::eth::Signature;
    // ...
}
```

**Comment by niklasad1** [comment]
We should add serialize and de-serialize impls to AccountId20, @jsdw do you remember why we skipped that or just missed?

**Comment by muraca** [comment]
the derived `serde::Deserialize` does not work, it requires a custom implementation:
```rust
impl Serialize for AccountId20 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(&subxt::utils::to_hex(self.0))
    }
}

impl Display for AccountId20 {
    fn fmt(&self, f: &mut Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", subxt::utils::to_hex(self.0))
    }
}
```

**Comment by jsdw** [comment]
> We should add serialize and de-serialize impls to AccountId20, @jsdw do you remember why we skipped that or was it just missed?

The way it works for `AccountId32` is:
- `subxt-signer` has a related type (actually just called `PublicKey`) which doesn't care about anything Subxt related
- `subxt` has an actual `AccountId32` type that impls everything Subxt needs of it
- `subxt-signer` when using the `subxt` feature, impls `From<PublicKey> for AccountId32` and the relevant stuff such that anything that is `From<PublicKey>` will Just Work with that signer.

This keeps the signer stuff sortof separate from Subxt, and means that we don't have any subxt-specific stuff in our signer code (unless the `subxt` feature is enabeld to connect them together)

I'd probably look to do similar with `AccountId20`; have a version of it in `subxt` (well, `subxt_core::utils` actually) that people can make use of in eth Configs in the same way they use AccountId32's in non-eth Configs. Then we can impl whatever Subxt needs on that type, and tweak the `subxt-signer` code to tie in like we do with AccountID32
