### ISSUE TITLE
Signature error batch transactions with payout stakers iff more then 4 calls are in the batch

### ISSUE THREAD

**Issue by clangenb** [paritytech/subxt#1641]
This turned out to be the underlying issue of https://github.com/paritytech/subxt/issues/1639. I am not sure if the error is on the node side or on subxt. Batch transactions of size worked 4 for me before on Kusama, but after the upgrade of runtime v1.2.5. and the corresponding subxt update to 0.37.0 this error started to occur.

Workaround: Simply reduce the batch size to 3.

**Comment by niklasad1** [comment]
Ok, thanks for the update.

Can you provide a small example in subxt how to re-produce this?
Would be interesting to run against kusama-dev node because I assume this doesn't happen on westend?!

**Comment by clangenb** [comment]
I was trying to reproduce this with a small example. However, now I realize that it is only the well-known bug about batch transactions sticking around in the tx-pool for a while until they are eventually removed due to their mortality, see https://github.com/paritytech/polkadot-sdk/issues/6.

The error that is being thrown upon removal is the following:

```
 Subxt(Transaction(Invalid("Transaction is invalid (eg because of a bad nonce, signature etc)")))
```

I guess the error might be a bit unclear, but it is the expected behaviour. I will close the issue.
