### ISSUE TITLE
Support dynamic dispatch on Payload?

### ISSUE THREAD

**Issue by SangyunOck** [paritytech/subxt#1670]
```rust
// https://github.com/paritytech/subxt/blob/v0.37.0/subxt/src/tx/tx_client.rs#L90
pub fn create_partial_signed_offline<Call>(
    &self,
    call: &Call,
    params: <T::ExtrinsicParams as ExtrinsicParams<T>>::Params,
) -> Result<PartialExtrinsic<T, C>, Error>
where
    Call: Payload,
```

create_signed_offline method of TxClient accepts reference of call as generic Call which impls Payload trait.
There might be some use cases building some payloads(including issue #1241), ignoring the actual types and collect them in a vector to sign at once.

for example,
```rust
pub fn payout_stakers() -> Box<dyn Payload> {
    Box::new(tx().staking().payout_stakers())
}
pub fn bond() -> Box<dyn Payload> {
    Box::new(tx().staking().bond())
} 
pub fn sign_payloads(payloads: &[Box<dyn Payload>]) -> Result<Vec<u8>, Error> {
    Ok(payloads
        .into_iter()
        .map(|p| client.create_partial_signed_offline(p)?.into_encoded())
        .collect::<Result<Vec<_>, _>>()?)
}
```

It might be great if some smart pointers implements Payload trait as well as its original type.
```rust
// https://github.com/paritytech/subxt/blob/v0.37.0/core/src/tx/payload.rs#L21
#[auto_impl(&, Box, Rc, Arc)]
pub trait Payload { .. }
``` 

thank you :)

**Comment by jsdw** [comment]
I hesitated with this a bit because IIRC we used to have a way to box payloads, but it had some issues. However, I had a go in #1690 and it all worked out ok so def a nice thing to have :)
