### ISSUE TITLE
Run integration tests against tagged substrate docker image

### ISSUE THREAD

**Issue by ascjones** [paritytech/subxt#169]
For our integration tests which require a running substrate node, we should consider running a tagged docker image of substrate: https://hub.docker.com/r/parity/substrate/tags. Also see https://github.com/paritytech/pallet-contracts-waterfall#using-a-docker-image-of-substrate-for-testing

That way we do not need to maintain all modules in the local test node.

**Comment by jsdw** [comment]
We do a CI run against nightly substrate binaries now. The docker images look like they might be produced more often though. Do you still think there's value in using said docker images or happy enough with the current approach?
