### ISSUE TITLE
Signing bytes payload

### ISSUE THREAD

**Issue by leonardocustodio** [paritytech/subxt#1730]
If I receive the payload from a third-party system, bytes encoded, is it possible to use `sign_and_submit` to sign it?

I mean, I could create a `DynamicPayload` using:
```
    let tx_payload = subxt::dynamic::tx("System", "remark", vec![
        Value::from_bytes("Hello there")
    ]);
```

But isn't the pallet name and call name in the encoded bytes? Do I need to pass those two?

**Comment by jsdw** [comment]
If the payload is just the call data (ie a byte for pallet index, byte for call index and then scale encoded call arguments), then we are missing the signed extension parameters, from address and signature still. In this case, you could implement the `subxt::tx::Payload` trait on some wrapper type and then pass that to subxt, something like this:

```rust
/// wrapper containing call data.
struct Wrapper(Vec<u8>);

impl subxt::tx::Payload for Wrapper {
    fn encode_call_data_to(&self, metadata: &Metadata, out: &mut Vec<u8>) -> Result<(), Error> {
        out.extend_from_slice(&self.0)
    }
}

// Now hand this to Subxt to submit like any other call:
subxt_client
    .tx()
    .sign_and_submit_then_watch(&Wrapper(call_data), signer, extrinsic_params)
    .await?;
```

The only other "entry point" into Subxt is if the payload is already signed and ready to submit, in which case you can instantiate the relevant object with:

```rust
subxt::tx::SubmittableExtrinsic::from_bytes(subxt_client, tx_bytes)
    .submit_and_watch()
    .await?;
```

This then results in the same type as the first example.

**Comment by leonardocustodio** [comment]
You are a legend mate, exactly what I needed, thank you very much
