### ISSUE TITLE
Fetching data from blockchain api in the guest code of risczero

### ISSUE THREAD

**Issue by amiyatulu** [paritytech/subxt#1741]
What if I use inputs from blockchain data with [Risc Zero zero-knowledge proof](https://dev.risczero.com/api/blockchain-integration/bonsai-on-eth)? Can I fetch data and make transactions from a blockchain API using [subxt](https://github.com/paritytech/subxt/blob/master/subxt/examples/light_client_basic.rs) in Substrate, utilizing a light client in my guest code, and then use this data in [my guest code of risc zero](https://dev.risczero.com/api/zkvm/tutorials/hello-world#step-3-guest-read-input-and-commit-output)? Afterward, can I submit the proofs to the blockchain? Will there be any security issues to fetch data from light client?

**Comment by jsdw** [comment]
I don't know about Risk Zero, but if there waqs some Substrate chain that uses it then I would hope that you'd be able to connect Subxt to it to make transactionms and such. Submitting transactions and reading storage etc would work as with any other chain, and if you go via the light clieent, it shouldd provide the same trust guarantees regardless (at the end of the day it's just verifying that the storage retrieved is valid (and building on that afaiu to prove runtime APIs). Doesn't matter what values it contains.

**Comment by jsdw** [comment]
I'll close this for now as I assume it's answered, but please do re-open if still an outstanding issue :)
