### ISSUE TITLE
Subxt gives error when used with risczero

### ISSUE THREAD

**Issue by amiyatulu** [paritytech/subxt#1742]
Subxt gives error when used with [risczero](https://github.com/risc0/risc0).

```
guest_anonymous_account: The following warnings were emitted during compilation:
guest_anonymous_account: 
guest_anonymous_account: warning: ring@0.17.8: riscv32-unknown-elf-gcc: error: unrecognized command-line option '-m64'
guest_anonymous_account: 
guest_anonymous_account: error: failed to run custom build command for `ring v0.17.8`
guest_anonymous_account: 
guest_anonymous_account: Caused by:
guest_anonymous_account:   process didn't exit successfully: `/home/amiya/Documents/workspace/zero-knowledge/anonymous_account/target/riscv-guest/release/build/ring-8e1a6a39262bd209/build-script-build` (exit status: 1)
guest_anonymous_account:   --- stdout
guest_anonymous_account:   cargo:rerun-if-env-changed=RING_PREGENERATE_ASM
guest_anonymous_account:   cargo:rustc-env=RING_CORE_PREFIX=ring_core_0_17_8_
guest_anonymous_account:   OPT_LEVEL = Some(0)
guest_anonymous_account:   TARGET = Some(x86_64-unknown-linux-gnu)
guest_anonymous_account:   OUT_DIR = Some(/home/amiya/Documents/workspace/zero-knowledge/anonymous_account/target/riscv-guest/release/build/ring-6aa5585402d7db96/out)
guest_anonymous_account:   HOST = Some(x86_64-unknown-linux-gnu)
guest_anonymous_account:   cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
guest_anonymous_account:   CC_x86_64-unknown-linux-gnu = None
guest_anonymous_account:   cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
guest_anonymous_account:   CC_x86_64_unknown_linux_gnu = None
guest_anonymous_account:   cargo:rerun-if-env-changed=HOST_CC
guest_anonymous_account:   HOST_CC = None
guest_anonymous_account:   cargo:rerun-if-env-changed=CC
guest_anonymous_account:   CC = Some(/home/amiya/.local/share/cargo-risczero/cpp/bin/riscv32-unknown-elf-gcc)
guest_anonymous_account:   RUSTC_WRAPPER = None
guest_anonymous_account:   cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
guest_anonymous_account:   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
guest_anonymous_account:   CRATE_CC_NO_DEFAULTS = None
guest_anonymous_account:   DEBUG = Some(false)
guest_anonymous_account:   CARGO_CFG_TARGET_FEATURE = Some(fxsr,sse,sse2)
guest_anonymous_account:   cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
guest_anonymous_account:   CFLAGS_x86_64-unknown-linux-gnu = None
guest_anonymous_account:   cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
guest_anonymous_account:   CFLAGS_x86_64_unknown_linux_gnu = None
guest_anonymous_account:   cargo:rerun-if-env-changed=HOST_CFLAGS
guest_anonymous_account:   HOST_CFLAGS = None
guest_anonymous_account:   cargo:rerun-if-env-changed=CFLAGS
guest_anonymous_account:   CFLAGS = None
guest_anonymous_account:   cargo:warning=riscv32-unknown-elf-gcc: error: unrecognized command-line option '-m64'
guest_anonymous_account: 
guest_anonymous_account:   --- stderr
guest_anonymous_account: 
guest_anonymous_account: 
guest_anonymous_account:   error occurred: Command "/home/amiya/.local/share/cargo-risczero/cpp/bin/riscv32-unknown-elf-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-I" "/home/amiya/Documents/workspace/zero-knowledge/anonymous_account/target/riscv-guest/release/build/ring-6aa5585402d7db96/out" "-Wall" "-Wextra" "-fvisibility=hidden" "-std=c1x" "-Wall" "-Wbad-function-cast" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wnested-externs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wstrict-prototypes" "-Wundef" "-Wuninitialized" "-g3" "-DNDEBUG" "-o" "/home/amiya/Documents/workspace/zero-knowledge/anonymous_account/target/riscv-guest/release/build/ring-6aa5585402d7db96/out/fad98b632b8ce3cc-curve25519.o" "-c" "crypto/curve25519/curve25519.c" with args riscv32-unknown-elf-gcc did not execute successfully (status code exit status: 1).
guest_anonymous_account: 
guest_anonymous_account: 
guest_anonymous_account: warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `methods v0.1.0 (/home/amiya/Documents/workspace/zero-knowledge/anonymous_account/methods)`

Caused by:
  process didn't exit successfully: `/home/amiya/Documents/workspace/zero-knowledge/anonymous_account/target/debug/build/methods-d0d32bf95e276aa9/build-script-build` (exit status: 101)
  --- stdout
  Building guest package methods.guest_anonymous_account
  cargo:rerun-if-env-changed=RISC0_SKIP_BUILD
  Using rustc: /home/amiya/.rustup/toolchains/risc0/bin/rustc
  cargo:rerun-if-env-changed=RISC0_RUST_SRC
  Building guest package: cargo build --target riscv32im-risc0-zkvm-elf
  cargo:rerun-if-env-changed=RISC0_BUILD_DEBUG
```

**Comment by niklasad1** [comment]
Hey @amiyatulu 

subxt is using the jsonrpsee-ws-client by default it depends on ring which doesn't compile for risc zero and probably jsonrpsee doesn't as well. So you need to disable the jsonrpsee feature in subxt but it might possible to use jsonrpsee without tls.

What will work is provide some other rpc client that you know compiles risc zero and then implement the subxt::RpcClientT trait [example here](https://github.com/paritytech/subxt/blob/master/subxt/examples/setup_client_custom_rpc.rs)

**Comment by amiyatulu** [comment]
Here is issue on risc v support on ring.

https://github.com/briansmith/ring/issues/1182

**Comment by niklasad1** [comment]
jsonrpsee without any features doesn't enable anything

Try building the following:

```toml
jsonrpsee-ws-client = { version = "0.22", default-features = false }
```

This will disable TLS

**Comment by amiyatulu** [comment]
[Tonic](https://github.com/hyperium/tonic/tree/master/examples/src/helloworld) successfully compiled with risczero. But not sure how to implement `subxt::RpcClientT trait ` with tonic.

Should I have to modify the struct
```rust
struct MyLoggingClient {
    log: Arc<Mutex<String>>,
}
```
Tonic rpc can be good alternative to jsonrpsee, an example file will be a good idea.

**Comment by niklasad1** [comment]
jsonrpsee most likely works as well if you disable TLS and tonic hasn't enabled TLS in the example

**Comment by amiyatulu** [comment]
Will their be security issues if I disable tls ?
Like manipulating data in between while producing zero knowledge proofs.

**Comment by niklasad1** [comment]
> Will there be security issues if I disable tls ?
> Like manipulating data in between (data integrity) while producing zero knowledge proofs.

It's something you have to decide i.e, whether you can have it running on localhost or something that you trust but it's not recommended obviously (I don't know how to workaround that in risc-v)

Anyway I have created an example how to get you started with subxt without tls, https://github.com/niklasad1/subxt-riscv-example but it's nothing really that on our roadmap to support but it's quite cool...

**Comment by amiyatulu** [comment]
Not localhost but using [lightclient](https://github.com/paritytech/subxt/blob/master/subxt/examples/light_client_basic.rs). 

If I can fetch data from the light client without any security issues, then I don't have any problem. 

However, to offload computations off-chain, RiscZero support is required. Using Subxt and risczero I can securely fetch data from the blockchain, make intermediate transactions, perform off-chain computations, and store the proof of computation on the blockchain.

For instance, to calculate the standard deviation of millions of values, I can fetch the data from the blockchain using RiscZero and Subxt, perform the calculation, and then submit the proof containing the output value, i.e., the standard deviation. One can be sure that output value is the actual standard deviation without manipulation. Importantly, the duration of the computation does not matter - even if it takes an hour, as only proof is still stored on the blockchain.

https://github.com/paritytech/subxt/issues/1741

**Comment by amiyatulu** [comment]
Also the dependancies don't work in risczero. It still gives ring error:
```toml
serde = "1.0.209"
serde_json = "1.0.127"
subxt = { version = "0.37.0", default-features = false, features = ["native"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros", "time"] }
jsonrpsee-ws-client = { version = "0.24.5", default-features = false }
jsonrpsee-core = { version = "0.24.5", features = ["client"] }
futures = "0.3"
```
Error:
```
guest_anonymous_account: The following warnings were emitted during compilation:
guest_anonymous_account: 
guest_anonymous_account: warning: ring@0.17.8: riscv32-unknown-elf-gcc: error: unrecognized command-line option '-m64'
guest_anonymous_account: 
guest_anonymous_account: error: failed to run custom build command for `ring v0.17.8`
guest_anonymous_account: 
guest_anonymous_account: Caused by:
guest_anonymous_account:   process didn't exit successfully: `/home/amiya/Documents/workspace/zero-knowledge/anonymous_account/target/riscv-guest/release/build/ring-03b100417c8058ad/build-script-build` (exit status: 1)
guest_anonymous_account:   --- stdout
guest_anonymous_account:   cargo:rerun-if-env-changed=RING_PREGENERATE_ASM
guest_anonymous_account:   cargo:rustc-env=RING_CORE_PREFIX=ring_core_0_17_8_
guest_anonymous_account:   OPT_LEVEL = Some(0)
guest_anonymous_account:   TARGET = Some(x86_64-unknown-linux-gnu)
guest_anonymous_account:   OUT_DIR = Some(/home/amiya/Documents/workspace/zero-knowledge/anonymous_account/target/riscv-guest/release/build/ring-8eb799c10db90681/out)
guest_anonymous_account:   HOST = Some(x86_64-unknown-linux-gnu)
guest_anonymous_account:   cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
guest_anonymous_account:   CC_x86_64-unknown-linux-gnu = None
guest_anonymous_account:   cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
guest_anonymous_account:   CC_x86_64_unknown_linux_gnu = None
guest_anonymous_account:   cargo:rerun-if-env-changed=HOST_CC
guest_anonymous_account:   HOST_CC = None
guest_anonymous_account:   cargo:rerun-if-env-changed=CC
guest_anonymous_account:   CC = Some(/home/amiya/.local/share/cargo-risczero/cpp/bin/riscv32-unknown-elf-gcc)
guest_anonymous_account:   RUSTC_WRAPPER = None
```

**Comment by niklasad1** [comment]
Ok, subxt seems to leak that feature from the reconnecting-client. I pushed a fix but I was to lazy to install the toolchain.


I'll test it later today... or may you could test it again.

**Comment by amiyatulu** [comment]
Just discussing in risczero forum

```
I would imagine typically you might use subxt on the host to interact with the chain. Then, perform any verifications inside of the guest, which you could do without subxt dependencies.
```

As host subxt successfully compiles, but it doesn't compile in guest.

**Comment by niklasad1** [comment]
Ok, I have raised https://github.com/paritytech/subxt/issues/1812 which is subxt issue that we should fix.
Sorry didn't realize that risczero didn't have an OS or socket support then it becomes hard to support 

I would rather copy-paste this in to a discussion thread because I don't regard it as subxt issue because subxt has:
- subxt-core (compiles for no-std)
- offline-client
- online-client (that requires std, socket and tls support)

Thus, the way forward for you is most likely to keep interacting with the chain via RPC as host and do the zk-stuff as guest. You may be able to use IPC or something else to interact between guest/host but I don't know that stuff...

Hopefully that will help to engineer something around it.

**Comment by amiyatulu** [comment]
> Sorry didn't realize that risczero didn't have an OS or socket support then it becomes hard to support

Yes, currently I am trying to just compare input data string and journal data in blockchain, to have offchain computing. One can also use hash of input data for comparision. It would cheaper to do, and solves most use cases.
