### ISSUE TITLE
Keep a branch that always matches what is on-chain

### ISSUE THREAD

**Issue by DemiMarie** [paritytech/subxt#177]
The current git master is not compatible with what is on-chain right now.

**Comment by ascjones** [comment]
I'm guessing because the substrate 2.0 upgrade has not been deployed on chain yet. 

Now we have proper versioned releases (not pre-releases) of substrate we can make sure we have compatible releases of `subxt`. 

Certainly there are no guarantees that what is on `master` is currently compatible with what is running on chain. We will need to add something to the readme which explicitly describes what version of substrate it is compatible with.

**Comment by dvdplm** [comment]
> Certainly there are no guarantees that what is on `master` is currently compatible with what is running on chain. We will need to add something to the readme which explicitly describes what version of substrate it is compatible with.

This is a pretty pesky problem, especially if you consider tens or even hundreds of parachains/parathreads that might be running heterogeneous versions of substrate.

We definitely need a table in the docs matching subxt versions to chain&runtime versions; not sure what we should advise people to do though: vendor `subxt` in their projects? or should we maintain `n` versions of subxt so people can use crates.io (brr, backports...)? 
Whatever we do, I fear that as the ecosystem diversify it will become unwieldy fast. :/

**Comment by ascjones** [comment]
I think it's good enough to show which version of substrate it is compatible with. 

In the ideal world future we would like to be able to generate everything directly from the metadata (like polkadot-js), but that is a few months off at least.

**Comment by DemiMarie** [comment]
@dvdplm My suggestion would be to make subxt part of Substrate itself, so that it can be kept in sync.  Failing that, I would like to establish a policy that version N of subxt matches version N of Substrate.

**Comment by dvdplm** [comment]
> make subxt part of Substrate itself, so that it can be kept in sync.

That might make sense. Not sure that would have helped here though: Polkadot&Kusama are not yet on substrate 2.0.

> a policy that version N of subxt matches version N of Substrate

The trouble with that is that it brings with it plenty of maintenance work; we'd need to decide on a certain number of "supported releases" and keep them updated with backports from master. Doable for sure, but not super pretty. If we go down that route I'd advocate for supporting two versions: "latest" and "whatever is deployed".

**Comment by DemiMarie** [comment]
@dvdplm another option (which is what Ledgeracio actually needs) is to have *one* version of subxt support *multiple* versions of Substrate, and determine the correct version at runtime.

**Comment by jsdw** [comment]
Given that we have codegen via metadata now, hopefully a lot of this is sortof resolved?

I do think we should put more effort into keeping track of something like which versions of subxt are compatible with which versions of.... Substrate? Polkadot? But we do now have a nightly CI check against substrate which helps us catch things when they crop up (fortunately not so much lately it feels like), and with V14 metadata and codegen we automatically keep up with pallet changes (beyond needing to fix our tests at least if used APIs change), so we're definitely in a better place than we used to be.

Given the age of this issue and how much has changed in the meantime, I'll close this for now, but feel free to open a new issue if it's still something that's needed.
