### ISSUE TITLE
Create new crates.io release of subxt

### ISSUE THREAD

**Issue by tbraun96** [paritytech/subxt#1783]
PR of relevance: https://github.com/paritytech/subxt/pull/1777

**Comment by niklasad1** [comment]
Hey, we got a couple of other blockers that we want fix before releasing a new version, mainly:

- Stabilizing the reconnecting client
- Fix a trimming metadata issue
- Stabilizing the unstable backend (optional)

 I don't expect it not happen this week but in hopefully in the a couple of weeks, is that okay for you guys?

/cc @pkhry @jsdw is that reasonable?

**Comment by niklasad1** [comment]
Sorry delay but another release is out now, https://github.com/paritytech/subxt/releases/tag/v0.38.0
