### ISSUE TITLE
Deriving Serialize for more types inside subxt/backend defs

### ISSUE THREAD

**Issue by pkhry** [paritytech/subxt#1787]
Currently most types used in subxt/backend do not derive Serialize for  most of their type defs, but this could end up being useful to the end user. 

see https://github.com/paritytech/subxt/pull/1765#pullrequestreview-2325864867

**Comment by jsdw** [comment]
@pkhry I geuss this is finished now and can be closed, or anything else you think should be done?

**Comment by pkhry** [comment]
> @pkhry I geuss this is finished now and can be closed, or anything else you think should be done?

Yup
