### ISSUE TITLE
Bad things happen when querying an empty storage map

### ISSUE THREAD

**Issue by dvc94ch** [paritytech/subxt#1805]
Either an incompatible metadata error is raised or it just hangs. Currently working around this by either initializing the storage map or adding a runtime api to query it.

**Comment by niklasad1** [comment]
Hey, thanks for raising the issue but from subxt's point-of-view what you describing could be two different things and can you double-check whether storage you actually query is in the metadata that you using?

The expectation from subxt should as follows:
1. Storage key that is not part of the metadata -> Incompat metadata error
2. Empty storage -> Return `None`  (i.e, not hang)

Even better would be if you can provide a minimal example how re-produce this issue

**Comment by dvc94ch** [comment]
you can reproduce it by trying to query it using `subxt explore`. it always fails no matter if it's an OptionQuery or a ValueQuery. it may even be a substrate bug since usually the first try returns an error, but subsequent calls hang. As soon as you insert at least one element there are no issues.

```
	#[pallet::storage]
	pub type ShardNetwork<T: Config> =
		StorageMap<_, Blake2_128Concat, u64, u16, OptionQuery>;

```
```
subxt explore pallet Shards storage ShardNetwork --execute 0
```

**Comment by dvc94ch** [comment]
mmh, might have opened the issue prematurely.

**Comment by lexnv** [comment]
@dvc94ch No worries! Glad to hear everything is sorted here!

Would love to hear what the issue was in the end, maybe this can help us answer these questions more promptly in the future, thanks 🙏
