### ISSUE TITLE
example for lightclient

### ISSUE THREAD

**Issue by hitchhooker** [paritytech/subxt#1813]
it's quite tricky/time-consuming now to get started with lightclient on subxt. 
one working example in use, would be helpful to get started.

**Comment by niklasad1** [comment]
Hey @hitchhooker 

Have tested/looked at these light-client examples:
- https://github.com/paritytech/subxt/blob/master/subxt/examples/light_client_local_node.rs
- https://github.com/paritytech/subxt/blob/master/subxt/examples/light_client_basic.rs

Can you explain what is not working or what you think to simplify that?

**Comment by hitchhooker** [comment]
aight, those did the trick. 
not sure if gh supports any soft links but examples/subxt -> subxt/examples would have done it for me :1234:
