### ISSUE TITLE
Could this repo make a list of projects using it?

### ISSUE THREAD

**Issue by clearloop** [paritytech/subxt#182]
## Desc

I've got some query `Store` error in our project [bridger][0], like

```
 Subxt("Scale codec error: Error decoding field EthereumHeaderThing.header")  
```

Even I import the struct from the chain directly, It would be nice to list some complete projects using this repo.

[0]: https://github.com/darwinia-network/bridge-primitives

**Comment by dvc94ch** [comment]
So you want to use the list of complete projects as examples of how to use subxt?

**Comment by clearloop** [comment]
The `types` in our project are definitely correct, it hard to find out why it runs into error.

> So you want to use the list of complete projects as examples of how to use subxt?

Yep, and I'm reading the source code of [sunshine-protocol/sunshine-keybase][0]  now~


[0]: https://github.com/sunshine-protocol/sunshine-keybase/blob/7875caf75877865d719661fe9ff82556b592db6f/identity/client/src/subxt.rs

**Comment by clearloop** [comment]
It seems I've written the wrong types...
