### ISSUE TITLE
Event received again after restart

### ISSUE THREAD

**Issue by sander2** [paritytech/subxt#190]
I have a client that always listens to events, and reacts to them. If I restart the client shortly after receiving an event, the same event is received again after startup. In my case, this results in a payment being made twice, which is not good.. Is there anything that can be done about it?

**Comment by ascjones** [comment]
Sounds as if you are resubscribing at the same block, therefore receiving the same block events. You could keep track of the block for which events have been received, and then only subscribe from the next one. Or just keep track of the block hash of received events and ignore any events for an already processed block.

**Comment by sander2** [comment]
Right, that would certainly work. But wouldn't it make sense for events to only fire when a new block is coming in, and not for the latest block that is already in the chain?

**Comment by kirushik** [comment]
@sander2 what's your approach to handling potentially missed events in case of your client code crashing?
For me it would make more sense to have events from subxt to be uniquely-identified (we provide everything you might need to do that in a meaningful way) and treated _idempotently_ in your codebase.

**Comment by sander2** [comment]
At startup we use rpc calls to get all the relevant state for the client. You have to do something like that anyway, in case new blocks arrived before the client starts again. We can make the event handling idempotent by keeping track of which events we already handled, but why shift this burden to the users of this lib? In my opinion, it's not unreasonable to expect events to be received at most once.

**Comment by ascjones** [comment]
>  why shift this burden to the users of this lib? In my opinion, it's not unreasonable to expect events to be received at most once.

Do you mean across client restarts? If so that would require persisting some state which would be outside the scope of this library. 

If within a live subscription then we probably could provide the at most once guarantee.

**Comment by jsdw** [comment]
Going to close this as it's been open for ages and a lot has changed since. Please create a new issue (for visibility) if the new subscription API is still a problem
