### ISSUE TITLE
Dynamically derive default mortality from System::Constants::BlockHashCount

### ISSUE THREAD

**Issue by emostov** [paritytech/subxt#206]
`BlockHashCount` is defined by the runtime and thus we cannot know for sure what an ok `mortal_period` is. Ideally we could fetch the `BlockHashCount` from the runtime and do something like find the next greatest power of two and use that as the default `mortal_period`

_Originally posted by @niklasad1 in https://github.com/paritytech/substrate-subxt/pull/204#discussion_r543404026_

**Comment by dvdplm** [comment]
Possibly related to #331. At the very least we should make it possible to specify the mortality.

**Comment by jsdw** [comment]
We can now specify the mortality. transactions default to immortal if you don't provide any params.

I could see an argument for transacitons defaulting to being mortal though, since it's a much safer default, so I guess this is still worth looking into!
