### ISSUE TITLE
Why convert name to_camel_case?

### ISSUE THREAD

**Issue by wuminzhe** [paritytech/subxt#211]
Take storage as an example:
[https://github.com/paritytech/substrate-subxt/blob/0a926ef4c45eb86e39c036480180577d609fd776/proc-macro/src/store.rs#L74](https://github.com/paritytech/substrate-subxt/blob/0a926ef4c45eb86e39c036480180577d609fd776/proc-macro/src/store.rs#L74)

If a storage name is `MMRRoots`, which will be converted to `MmrRoots`. 
But, the name from metadata stays `MMRRoots`. That will cause a `MetadataError::StorageNotFound` error.

**Comment by jsdw** [comment]
I'll close this now as I believe we've addressed this a fairly long time ago now, but if you do run into any issues then please do let me know!
