### ISSUE TITLE
author_submitAndWatchExtrinsic execute the contract deployed in Ink?

### ISSUE THREAD

**Issue by qqliaoxin** [paritytech/subxt#213]
How to implement author_submitAndWatchExtrinsic with substrate-subxt and execute the contract deployed in Ink?

**Comment by ascjones** [comment]
See WIP here: https://github.com/paritytech/cargo-contract/blob/f070a4091ac7fcec9c1f5303b34f2a3adb0fa1bf/src/cmd/extrinsics/call.rs#L98

**Comment by qqliaoxin** [comment]
git checkout aj-contract-call  cargo run project,  but error:
 --> src/util.rs:88:51
   |
88 | pub fn decode_hex(input: &str) -> Result<Vec<u8>, hex::FromHexError> {
   |                                                   ^^^ use of undeclared crate or module `hex`

**Comment by qqliaoxin** [comment]
I can’t understand how to make async fn call(&self, data: Vec<u8>) independent if the user rust changes it. Rewrite a web Api interface to use it. I originally copied one based on go-substrate-rpc-client Go version. But the data format is wrong. Can you guide me
