### ISSUE TITLE
Multiple possible events within function

### ISSUE THREAD

**Issue by sander2** [paritytech/subxt#224]
I have a function which, depending on the code path, emits 0 or more events, possibly of different types. In my rpc call, I am not interested in these events, I just want to make sure that the call was successful. However, if one of the events fires, I get a TypeSizeUnavailable error. Is there a way to prevent this error from occurring without refactoring my parachain code?

**Comment by ascjones** [comment]
This could be resolved via #227 by correctly registering all types for your runtime. Alternatively we could add an alternative to `submit_and_watch_extrinsic` which does not attempt to decode the events.

**Comment by ascjones** [comment]
Closed by #294
