### ISSUE TITLE
Consider adding rococo-v1 branch

### ISSUE THREAD

**Issue by gregdhill** [paritytech/subxt#228]
- [paritytech/polkadot/rococo-v1](https://github.com/paritytech/polkadot/tree/rococo-v1)
- [paritytech/substrate/rococo-v1](https://github.com/paritytech/substrate/tree/rococo-v1)
- [paritytech/cumulus/rococo-v1](https://github.com/paritytech/cumulus/tree/rococo-v1)

Currently we require a [fork](https://github.com/interlay/substrate-subxt/tree/2e07b0a4dfa38513ff5fe8e3fe149c8ead952f31) of `substrate-subxt` with fixed dependencies.

**Comment by ascjones** [comment]
Should be solved by #294
