### ISSUE TITLE
How to Create an Extrinsic for any Module （E.g write proof on chain and retrive it back for POE dapp）

### ISSUE THREAD

**Issue by maxmetagravity** [paritytech/subxt#258]
How to Create an Extrinsic for any Module， Hope someone of the community can give a detailed example?, E.g write proof on chain and retrive it back for POE dapp( https://substrate.dev/docs/en/tutorials/build-a-dapp/), I read somedocs, but did not figure it out using subxt ,   Subxt lacks examples in this regard, which is actually very important to promote the application of substrate

thanks very much

**Comment by jsdw** [comment]
I'm working on a proper guide for Subxt which should cover this so will close this and address in #898
