### ISSUE TITLE
Multiple metadata versions

### ISSUE THREAD

**Issue by ascjones** [paritytech/subxt#26]
Consider supporting multiple versions of substrate [metadata](https://github.com/paritytech/substrate/blob/ac11c330a95827211e1999781b5f691e72387c9e/srml/metadata/src/lib.rs#L351) (currently on v8). 

This would allow the library to be used against chains running different versions of substrate. 

Rel #25

**Comment by lucgerrits** [comment]
Have the same issue.
Rel to C++ implementation https://github.com/usetech-llc/polkadot_api_cpp/issues/32

Too bad I'm not good enough in C++ to make metadata V12 work.

**Comment by jsdw** [comment]
Going to close this since we're on V14 now and currently have no plans to support older versions than that.
