### ISSUE TITLE
Add option to enable off-chain worker in SubxtClientConfig

### ISSUE THREAD

**Issue by sander2** [paritytech/subxt#275]
To enable off-chain workers in integration tests, you need to manually edit the parachain config, as such:

```
let mut service_config = config.into_service_config();
service_config.offchain_worker.enabled = true;
let (task_manager, rpc_handlers) = btc_parachain_service::new_full(service_config).unwrap();
SubxtClient::new(task_manager, rpc_handlers);
```

It would be convenient if `SubxtClientConfig` contained an option to enable off-chain workers, so that you can use the normal `SubxtClient::from_config` instead of the above. It's honestly not a super big deal, but it'd help a lot in discoverability.

**Comment by ascjones** [comment]
`client` has been removed as part of #294
