### ISSUE TITLE
`Phase::Finalization` and `Phase::Initialization` events silently ignored

### ISSUE THREAD

**Issue by kylezs** [paritytech/subxt#288]
In `subscription.rs` there is this line:
```rust
if let Phase::ApplyExtrinsic(i) = phase {
```
And then there is no `else`. for the other event phases.

Took me a while to work out why I wasn't seeing some events being read from our chain, and it's because of this line.

Why are the `Phase::Finalized` and `Phase::Initialization` events ignored?

**Comment by kylezs** [comment]
Just noticed there's this PR open: https://github.com/paritytech/substrate-subxt/pull/283
Though doesn't look the diff actually does anything to solve the issue

**Comment by jsdw** [comment]
I believe that this is now closed by https://github.com/paritytech/subxt/pull/321, so I'll close this for now (please feel free to re-open if I'm mistaken)
