### ISSUE TITLE
About `polkadot_metadata.scale`

### ISSUE THREAD

**Issue by Cupnfish** [paritytech/subxt#314]
I don't know how to generate such a file for my own chain, is there a special document for it?

**Comment by insipx** [comment]
Hey @Cupnfish ,

you can get the polkadot_metadata.scale file, or really any .scale file from a running node with this unix command:

```
curl -sX POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"state_getMetadata", "id": 1}' localhost:9933 \
                    | jq .result \
                    | cut -d '"' -f 2 \
                    | xxd -r -p > ./tests/node_runtime.scale
```

**Comment by Cupnfish** [comment]
Thanks 😊

**Comment by ascjones** [comment]
Also you can use `subxt-cli` now, `cargo run -p subxt-cli -- metadata -f bytes > metadata.scale`.

Just opened a PR https://github.com/paritytech/subxt/pull/319 with that
