### ISSUE TITLE
Use example balance-transfer compiler occur error in location.

### ISSUE THREAD

**Issue by DaviRain-Su** [paritytech/subxt#338]
This is  my test repo: https://github.com/DaviRain-Su/example-subxt.git

```
warning: unused import: `EventSubscription`
 --> src/main.rs:4:5
  |
4 |     EventSubscription,
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `example-subxt` (bin "example-subxt") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.78s
     Running `target/debug/example-subxt`
Error: Rpc(Request("{\"jsonrpc\":\"2.0\",\"error\":{\"code\":1010,\"message\":\"Invalid Transaction\",\"data\":\"Transaction has a bad signature\"},\"id\":5}"))
```

**Comment by DaviRain-Su** [comment]
This is  my test repo: https://github.com/DaviRain-Su/example-subxt.git

**Comment by jsdw** [comment]
Offhand I'm not certain what this is about! The only thought I can offer is to make sure that the metadata you used to generate the subxt types is from exactly the Polkadot binary that you are connecting to for your test.

@ascjones may well have a much better idea than me on the matter :)

**Comment by ascjones** [comment]
It's probably because of https://github.com/paritytech/subxt/pull/330.

You can try the commit before that PR to confirm. The fix we need to have it work for different versions of signed extensions is https://github.com/paritytech/subxt/issues/331

**Comment by DaviRain-Su** [comment]
> Offhand I'm not certain what this is about! The only thought I can offer is to make sure that the metadata you used to generate the subxt types is from exactly the Polkadot binary that you are connecting to for your test.
> 
> @ascjones may well have a much better idea than me on the matter :)

Yes, I regenerated the scale file.

**Comment by DaviRain-Su** [comment]
> It's probably because of #330.
> 
> You can try the commit before that PR to confirm. The fix we need to have it work for different versions of signed extensions is #331

Thx, for you help, This is the reason.
