### ISSUE TITLE
Retain Rust code items from `mod` decorated with `subxt` attribute

### ISSUE THREAD

**Issue by ascjones** [paritytech/subxt#346]
At the moment any Rust code items inside the decorated `mod` will be erased. 

e.g.

```
#[subxt::subxt(runtime_metadata_path = "metadata.scale")]
pub mod node_runtime { 
  pub struct MyStruct {} // this will be erased
}
```
See https://github.com/paritytech/subxt/commit/6306b9fc073b59133566cfabf9502c99d2703161

From #309

**Comment by jsdw** [comment]
This shouldn't be super hard to do, and I don't see why not; will label as such!
