### ISSUE TITLE
Codegen assumes presence of `frame_system::AccountData`

### ISSUE THREAD

**Issue by ascjones** [paritytech/subxt#348]
Currently the `AccountData` storage type is hardcoded:

https://github.com/paritytech/subxt/blob/ca5345c47eb987febb3b424355c352b467ae31fc/codegen/src/api/mod.rs#L228-L237

which is required for fetching the nonce for constructing the `Extra` data for an Extrinsic. It assumes the presence of the system pallet and that the `AccountData` type has a nonce field. So we should consider whether this should be made configurable, or at least detect if the `system` pallet is not present with that `Storage` entry. Currently we are assuming it is always there. https://github.com/paritytech/subxt

From #309

**Comment by Xanewok** [comment]
I understand that https://github.com/paritytech/subxt/pull/409 fixed this; let's reopen this it's still relevant.
