### ISSUE TITLE
Dynamic call indices for sudo and utility batch 

### ISSUE THREAD

**Issue by ascjones** [paritytech/subxt#356]
Currently the `Sudo::sudo` and `Utility::batch` dispatchables generate code which accepts statically constructed instances of the top level `Call` enum. This means that if there is a mismatch of pallet/dispatchable composition between the static metadata used to generate API, and the target node runtime, then the node will fail to decode the calls.

When making a `Call` directly, the API will use the metadata of the running node to prepend the pallet index and the call index. We should consider making this available when constructing these composite dispatchables.

Extracted from #309

**Comment by wischli** [comment]
Any update on this matter? I am trying to execute dynamic batch calls and assume it not to be working in 0.25.0 due to this issue?

**Comment by ascjones** [comment]
See the latest thinking in https://github.com/paritytech/subxt/issues/716.

I think pure dynamic calls might be working, e.g. see the multisig example: https://github.com/paritytech/subxt/blob/master/examples/examples/dynamic_multisig.rs#L61.

Note if you are running e.g. one off scripts where you can guarantee the metadata is synced with the target node you can use the statically generated types e.g. https://github.com/ascjones/seeding/blob/main/src/main.rs#L47

**Comment by jsdw** [comment]
This is something that `scale-encode` aims to solve, once it's integrated into Subxt. I'm off until Jan though so unless somebody else picks that up, it'll happen next month :)

**Comment by jsdw** [comment]
This is resolved now on `master` (soon to be released as 0.28); the `RuntimeCall` types will now be encoded with the help of metadata and matched on variant names, not indexes, however nested they are.
