### ISSUE TITLE
Subxt parse kilt metadata failed. response: expected `u32`, found `u64`

### ISSUE THREAD

**Issue by atenjin** [paritytech/subxt#369]
env:
test repo:
git repo: `https://github.com/atenjin/kilt-client`   (`https://github.com/atenjin/kilt-client/tree/try/subxt`)
branch: `try/subxt`

metadata: from endpoint `wss://peregrine.kilt.io/`  directly, it's version is V14.
> when call system_version it return v1.1.1, so I guess the runtime source code is related to this `https://github.com/KILTprotocol/mashnet-node/commit/ba08a359936846cbfee4b7ebce3af1b0f884f321`

and the metadata I get from the endpoint throught subxt-cli is in : `https://github.com/atenjin/kilt-client/blob/try%2Fsubxt/res/metadata.scale`

subxt version: `78626eb5eef60b52fd199adb26a724e68c4fdb55`
substrate version: `b9cafba3d0e7a5950ac78d81e4ab7f2074938666`

replay method:
```bash
git clone https://github.com/atenjin/kilt-client
git checkout -b try/subxt try/subxt
```

Then compile it, I get an error:
```bash
error[E0308]: mismatched types
  --> src/main.rs:12:1
   |
12 | #[subxt::subxt(runtime_metadata_path = "res/metadata.scale")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | |
   | expected `u32`, found `u64`
   | expected `u32` because of return type
   |
   = note: this error originates in the attribute macro `subxt::subxt` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
   |
12 | #[subxt::subxt(runtime_metadata_path = "res/metadata.scale")].try_into().unwrap()
   |

For more information about this error, try `rustc --explain E0308`.
error: could not compile `kilt-client` due to previous error

```

It seems not a custom type error, like not finding the right type path or else. So I'm confused for the converting type error.

**Comment by trusch** [comment]
+1 on this, I'm running into the same problem.

**Comment by ascjones** [comment]
The problem here appears to be that the `Index` type for the `DefaultConfig` is `u32` whereas it looks to be configured to be a `u64` in the kilt runtime.

The way I figure this out was to use `subxt-cli` like so to generate the code that is normally generated by the macro, and then compile it directly: 
```
subxt-cli -- codegen -f /home/andrew/code/kilt-client/res/metadata.scale | rustfmt --edition=2018 --emit=stdout > kilt.rs
```

There is an upcoming PR which should allow you to use your own predefined type configuration for your runtime: https://github.com/paritytech/subxt/pull/373. This likely won't be merged until next year since there is nobody around to review it, but you can try it out with that branch, and supply your own `Config` impl with `type Index = u64`.

**Comment by trusch** [comment]
@ascjones could your provide an example on how to use the code generation with a custom config in a programatic way?

**Comment by jsdw** [comment]
I had a go at giving you the example code that I thought would suffice, but I wasn't able to make it work offhand and so I've filed https://github.com/paritytech/subxt/issues/391.

Alas @ascjones is unavailabel for a couple of weeks. I'll probably get the chance to dig into it more in the ocming days but at present it's not obvious what the best solution is!

**Comment by ascjones** [comment]
#409

**Comment by jsdw** [comment]
I believe that this has been addressed so I'll close the issue now, but please re-open if I was wrong! :)
