### ISSUE TITLE
Subxt extrinsic submission with fails with error `Could not decode 'Call'`

### ISSUE THREAD

**Issue by Wizdave97** [paritytech/subxt#372]
When submitting an extrinsic, the submission fails with the error below

I'm sure i'm using an updated runtime to submit these extrinsics. I only have this issue when submitting extrinsics, reading runtime storage values works fine.

``` Error: Rpc(Request("{\"jsonrpc\":\"2.0\",\"error\":{\"code\":1002,\"message\":\"Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: \\\"validate_transaction\\\", parameter: \\\"tx\\\", error: Error { cause: Some(Error { cause: None, desc: \\\"Could not decode `Call`, variant doesn't exist\\\" }), desc: \\\"Could not decode `Call::System.0`\\\" } })\",\"data\":\"RuntimeApi(\\\"Execution failed: ApiError(FailedToConvertParameter { function: \\\\\\\"validate_transaction\\\\\\\", parameter: \\\\\\\"tx\\\\\\\", error: Error { cause: Some(Error { cause: None, desc: \\\\\\\"Could not decode `Call`, variant doesn't exist\\\\\\\" }), desc: \\\\\\\"Could not decode `Call::System.0`\\\\\\\" } })\\\")\"},\"id\":5}")) ```

You can run the code in this repo to reproduce the issue  https://github.com/Wizdave97/subxt-issue

**Comment by Wizdave97** [comment]
@justinFrevert here's the issue as you suggested on element

**Comment by justinFrevert** [comment]
Hey @Wizdave97, I'm noting the version you're using here. The issue is likely due to recent metadata updates to do with `scale-info`. I would suggest trying the `master` branch for now.

**Comment by Wizdave97** [comment]
> Hey @Wizdave97, I'm noting the version you're using here. The issue is likely due to recent metadata updates to do with `scale-info`. I would suggest trying the `master` branch for now.

The branch I’m using is on par with the master branch , the only difference is I turned on default features in some substrate  packages, it was causing the master branch not to compile when added as a dependency, other than that, there’s no other change to any of the package versions

**Comment by Wizdave97** [comment]
> Hey @Wizdave97, I'm noting the version you're using here. The issue is likely due to recent metadata updates to do with `scale-info`. I would suggest trying the `master` branch for now.

I've switched to the master branch of subxt, still no luck with it.

**Comment by justinFrevert** [comment]
Do you see the same issue on commits predating 793c945? I believe this introduced the scale-info changes that could be relevant.

Also noting that I've been having issues using the binary included, but am able to get by by commenting out the code that starts up the node.

**Comment by Wizdave97** [comment]
> Do you see the same issue on commits predating [793c945](https://github.com/paritytech/subxt/commit/793c945fbd2de022f523c39a84ee02609ba423a9)? I believe this introduced the scale-info changes that could be relevant.
> 
> Also noting that I've been having issues using the binary included, but am able to get past it by commenting out the code that starts up the node.

Ohh, the binary was built for linux with an intel processor,
