### ISSUE TITLE
How to call pallet functions using subxt?

### ISSUE THREAD

**Issue by kebab-mai-haddi** [paritytech/subxt#374]
Hi!
I want to get the total balance from any Substrate based parachain. I learned about `TotalIssuance` that exists in Substrate and was wondering how can I call the API to get the total tokens issued in a parachain.

The code for TotalIssuance is [here](https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L496):
```
/// The total units issued in the system.
	#[pallet::storage]
	#[pallet::getter(fn total_issuance)]
	pub type TotalIssuance<T: Config<I>, I: 'static = ()> = StorageValue<_, T::Balance, ValueQuery>;
```

Currently, I am calling the APIs for getting all the accounts as follows:
```
let api = ClientBuilder::new()
        .set_client(client)
        .build()
        .await?
        .to_runtime_api::<polkadot::RuntimeApi<polkadot::DefaultConfig>>();

    let mut iter = api.storage().system().account_iter(None).await?;
```
but have no clue how I can leverage `subxt` to get aforementioned `TotalIssuance`.

**Comment by lemarier** [comment]
You can get the total issuance from the balance pallet with;
```rust
api
  .storage()
  .balances()
  .total_issuance(None)
  .await?;
```

**Comment by ascjones** [comment]
Thankyou @lemarier, that is correct. All calls and storage items are available via the api. 

Disovery is slightly difficult, need to either look at the target pallet, or generate rust docs in order to view all available storage items etc.
