### ISSUE TITLE
error: failed to run custom build command for `wabt-sys v0.8.0`

### ISSUE THREAD

**Issue by raojianli** [paritytech/subxt#377]
run  examples polkadot_banance_transfer.rs   err

**Comment by jsdw** [comment]
Probably you need some system libraries to be installed, but without any information or log output we really can't provide any help on this.

**Comment by jsdw** [comment]
I'm going to close this issue as it appears to relate to `wabt-sys` and not `subxt`. If you still have an issue @raojianli I'd suggest posting an issue at https://github.com/pepyakin/wabt-rs :)
