### ISSUE TITLE
Events at Initialization phase are silently being ignored if `ImOnline::SomeOffline` event is present

### ISSUE THREAD

**Issue by paulormart** [paritytech/subxt#383]
Hi @ascjones,

I have been using and testing your latest branch [aj-config](https://github.com/paritytech/subxt/tree/aj-config) on my tools.

When subscribing to `Session::NewSession` events i have notice that these are currently being ignored if `offences.Offence` event is present.

My temporary workaround is to enforce `decode_raw::<Compact<u128>>(input, output)` if type matches `Type { path: Path { segments: [] }, type_params: [], type_def: Compact(TypeDefCompact { type_param: UntrackedSymbol { id: 6, marker: PhantomData } }), docs: [] }`, probably not the best approach but it's working fine so far.

The workaround is implemented [here](https://github.com/turboflakes/subxt/blob/e7d58bc93da2a479234ca2f6eb96f48a0ee5a297/src/events.rs#L319). 

I find it tricky to present a test so that this could be easier replicated.  But when inspecting Kusama block [10819134](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/10819134) and hardcoding this block when subscribing the latest block made my life easier to troubleshoot this issue :)

This branch with the hardcoded block [10819134](https://github.com/turboflakes/subxt/blob/ade33a5f817c2f0e3def28ea1483c086f5ee2d41/src/subscription.rs#L224)  can easily replicate the problem [pm-test-inspect-specific-block](https://github.com/turboflakes/subxt/blob/pm-test-inspect-specific-block/examples/fetch_block.rs) when running the example `RUST_LOG=subxt=debug cargo watch -x 'run --example fetch_block'`.

If anyone could have a look at this issue and confirm the best solution to solve it would be great.

**Comment by paulormart** [comment]
The problematic event is the `offences.Offence` and not the `ImOnline::SomeOffline` as previously stated. The event `offences.Offence` shows up frequently on Kusama every new session and not that much on Westend.

**Comment by ascjones** [comment]
Can you have a go with https://github.com/paritytech/subxt/pull/384? I discovered that while doing something else and it could be the cause here. It would make sense if it was `ImOnline::SomeOffline`, because that does contain some compact fields.

**Comment by paulormart** [comment]
Your PR #384 fixes this issue! 

Thank you
