### ISSUE TITLE
Generate API for pallet constants

### ISSUE THREAD

**Issue by gregdhill** [paritytech/subxt#396]
https://github.com/paritytech/subxt/pull/207 introduced a getter for `PalletMetadata` but as the strings are not validated at compile-time they may eventually fall out-of-sync. It would be better it add a `ConstantsApi` in the codegen crate.

**Comment by jsdw** [comment]
I wonder how much work it would be to avoid needing runtime metadata at all, since in theory everything metadata related should be doable at compile time. It's something that's crossed my mind a bit anyway, but I haven't yet looked into it!

**Comment by gregdhill** [comment]
We'll likely still need runtime metadata to validate the current API (https://github.com/paritytech/subxt/issues/398).
