### ISSUE TITLE
Expose transaction::TransactionProgress as public

### ISSUE THREAD

**Issue by boyswan** [paritytech/subxt#400]
Currently there's no `submit_then_watch` to work with offline signed Tx's - using `sign_and_submit_then_watch` requires the use of a signer. 

By exposing `transaction::TransactionProgress` I can have my own implementation of `submit_then_watch` without being bound to signing in subxt.

```rust
async fn submit_then_watch<'client>(
    client: &'client Client<DefaultConfig>,
    ext_hash: H256,
    signed_tx: Bytes,
) -> Result<TransactionProgress<'client, DefaultConfig>, parity_scale_codec::Error> {
    let sub = client.rpc().watch_extrinsic(signed_tx).await.unwrap();
    Ok(TransactionProgress::new(sub, client, ext_hash))
}

let events = submit_then_watch(&api, ext_hash, signed_tx)
      .await
      .unwrap()
      .wait_for_finalized_success()
      .await
      .unwrap();
```

**Comment by jsdw** [comment]
Sounds good to me! Happy to accept a PR to expose this, otherwise I'll get around to it quite soon :)

**Comment by boyswan** [comment]
https://github.com/paritytech/subxt/pull/401
