### ISSUE TITLE
Generate pallet RPC calls

### ISSUE THREAD

**Issue by ascjones** [paritytech/subxt#416]
It would be nice to generate methods for calling pallet RPC endpoints e.g. [contracts_instantiate](https://github.com/paritytech/cargo-contract/blob/922a7bc1ffd32b7de65ace6dd77bfdd804d3398c/src/cmd/extrinsics/instantiate.rs#L306.)

This is to avoid having to write code such as [this](https://github.com/paritytech/cargo-contract/blob/922a7bc1ffd32b7de65ace6dd77bfdd804d3398c/src/cmd/extrinsics/instantiate.rs#L306), which at present requires importing or copying the definitions of the request and response types.

In order to do this we would require some metadata to be generated for these calls on the Substrate side.

Once the metadata is available it should be relatively straightforward to generate the rpc calls. Could look something like:

`api.rpc().contracts().instantiate(request)`

**Comment by ascjones** [comment]
@athei has pointed out that this should not be restricted to pallet RPCs, that if we have RPC metadata then we can also generate the client code for any "core" rpc methods (see [`Rpc`]( https://github.com/paritytech/subxt/blob/master/subxt/src/rpc.rs#L323)).

One key distinction is that some "core" rpcs need to be defined up front, particularly `author_submitExtrinsic` so would need to handle that.

**Comment by athei** [comment]
The generated type can implement some traits that provide the RPCs that are required for `subxt`.

**Comment by ascjones** [comment]
Once we have https://github.com/paritytech/substrate/issues/11648 this can then be all done via `state_call`. Related https://github.com/paritytech/cargo-contract/pull/701

**Comment by niklasad1** [comment]
Right, I opened #631 for that not sure if I should close that and rely on this issue.

If you rename it to `runtime API calls` or something then I'm happy closing #631

**Comment by ascjones** [comment]
Yours is more detailed/up to date. 

Superseded by #631
