### ISSUE TITLE
Export RuntimeError for RPC calls

### ISSUE THREAD

**Issue by gregdhill** [paritytech/subxt#426]
This [RPC](https://github.com/interlay/interbtc/blob/28f135d2826d75c0d40d464c6156f4ed35048ad0/crates/btc-relay/rpc/src/lib.rs#L63) returns `Result<(), DispatchError>` in the response body. I don't think it is currently possible to cast the generated `DispatchError` to `RuntimeError` because it is not exported.

**Comment by gregdhill** [comment]
Related: `Deserialize` is not implemented for `DispatchError` @jsdw do you know how to add this?

**Comment by jsdw** [comment]
#427 Seems perfectly reasonable to me and would enable you to create an instance of the `Error<E>` type!

Merging that issue closed this; is there anything else you needed?

Hmm `Deserialize` not being implemented; that's a bit more tricky. At the mo, `DispatchError` is generated and given the same bounds as other generated types. You could try something like this:

```
#[subxt::subxt(
    runtime_metadata_path = "path/to/metadata.scale",
    generated_type_derives = "Deserialize"
)]
```

Which adds Deserialize to add types, but I somehow suspect it wouldn't work!

If you know the shape of your DispatchError, I suppose you could manually write a deserialize function or wrapping type to do so; it depends on what your aim is really?

**Comment by gregdhill** [comment]
@jsdw please see my approach [here](https://github.com/interlay/interbtc-clients/pull/220#discussion_r798772748), although it is not particularly elegant...
