### ISSUE TITLE
Unsupported metadata version 

### ISSUE THREAD

**Issue by PhillyWebGuy** [paritytech/subxt#432]
I run the following, after installing subxt-cli:

`subxt metadata -f bytes > metadata.scale`

My substrate node is up and running on the default port so the file is generated and the command is executed without any issues.

Then I execute:

`subxt codegen | rustfmt --edition=2018 --emit=stdout`

I then get this:

`The application panicked (crashed).
Message:  Unsupported metadata version V13(OpaqueMetadata([24, 83, 121, 115, 116, 101, 109, 1, 24, 83, 121, 115, 116]))
Location: /my/path/.cargo/registry/src/github.com-1ecc6299db9ec823/subxt-codegen-0.16.0/src/api/mod.rs:113`

I initially got an "Unsupported metadata version" when trying to compile some code with a function accompanied by the decorator. At first, I thought I had the path to the metadata wrong or something, but realized that wasn't the case, once I actually read the error and tried the above additional commands, to simplify my troubleshooting.

The "Unsupported metadata version" error: is that the metadata of the substrate node that is the problem? If so, anything we can do about this so that we may be able to use this tool?

**Comment by niklasad1** [comment]
Hey @PhillyWebGuy,

subxt relies on `metadata v14` to decode/generate the codegen, you need to update the substrate node with metadata v14 for it to work unfortunately.

**Comment by PhillyWebGuy** [comment]
Thanks for the info.
