### ISSUE TITLE
Does our CI doc check pass when it should be failing?

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#433]
Working through the release process, @lexnv spotted some doc warnings that I think should be errors, eg:

```
warning: public documentation for `RuntimeError` links to private item `GenericError`
   --> subxt/src/error.rs:142:47
    |
142 | /// This is used in the place of the `E` in [`GenericError<E>`] when we may have a
    |                                               ^^^^^^^^^^^^^^^ this item is private
    |
    = note: `#[warn(rustdoc::private_intra_doc_links)]` on by default
    = note: this link resolves only because you passed `--document-private-items`, but will break without

warning: `subxt` (lib doc) generated 1 warning
```

Our current CI command is `RUSTDOCFLAGS="--deny rustdoc::broken_intra_doc_links" cargo doc -vv --workspace --no-deps --document-private-items`. Even without `--document-private-items` that still leads to a pass (albeit with warnings).

Perhaps we need to make the `--deny` cover more cases.

**Comment by niklasad1** [comment]
@jsdw it's a separate lint, https://doc.rust-lang.org/rustdoc/lints.html#private_intra_doc_links

we need to add both I guess :)

**Comment by jsdw** [comment]
I think Alex added this in a recent PR so I'll close this issue now :)
