### ISSUE TITLE
Automate PR selection for changelog during release

### ISSUE THREAD

**Issue by lexnv** [paritytech/subxt#436]
One task of the releasing [activities](https://github.com/paritytech/subxt/blob/master/RELEASING.md) is to obtain the list of closed PRs, to update the [changelog](https://github.com/paritytech/subxt/blob/master/CHANGELOG.md) file.
This manual task introduces a delay in the release procedure.
Automate this step via a script / one-liner to obtain the required PRs in format
`- {pr-name} [{pr-number}]({pr-link})`

- #465 (Get committed PRs)
- Option to select a custom release range
- Verifiable tags (signed and included in the latest release)
- Group PRs into sections (Blocked by substrate labels reform)

**Comment by jsdw** [comment]
We have the nice script now, so I'll close this since it's good enough for now :)
