### ISSUE TITLE
Dynamic `DispatchError::Module` details

### ISSUE THREAD

**Issue by ascjones** [paritytech/subxt#443]
https://github.com/paritytech/subxt/pull/394 [removes](https://github.com/paritytech/subxt/pull/394/files#diff-97e25e2a0e41c578875856e97b659be2719a65227c104b992e3144efa000c35eL127) the lookup for error details from metadata at runtime, instead using the static metadata. 

This will only work if the configuration of the target runtime modules is identical to that of the compile time metadata. So for tools which target a single pallet that might be present across many versions of many chains (e.g. `cargo-contract`, or `xcm-cli`) then the error resolution might not work.

This was one of the original design goals for this library, and indeed the resolution of indices for constructing extrinsics and decoding events is still dynamic. So there should also be a similar mechanism for resolving runtime error details.

**Comment by jsdw** [comment]
I guess the best option is to reinstate the dynamic error information fetching code that was removed in that PR. We could then ponder either removing the statically generated stuff and tweaking the API to obtain details from the dynamic again, or keep both.
