### ISSUE TITLE
Issue querying storage with tuple key

### ISSUE THREAD

**Issue by wzli** [paritytech/subxt#446]
I'm on subxt release 0.17, generated metadata on the same version, my runtime is based on node-template 4.0.0
The storage is defined as:
```
#[pallet::storage]
#[pallet::getter(fn my_storage_map)]
pub(super) type MyStorageMap<T: Config> =
        StorageMap<_, Twox64Concat, (T::AccountId, T::Index), MyStruct<T>, OptionQuery>;
```
In the substrate unit tests, inserting and retrieving from the same tuple key there is no problems, but in subxt the same query returns None, even though the insert is successful when I check by iterating all storage entries.
```
let entry = api
        .storage()
        .my_pallet()
        .my_storage_map(acc_id, idx, None)
        .await?;
println!("{entry:?}"); // -> None
``` 

Anything else I can provide to help debug?

**Comment by jsdw** [comment]
Hey, thanks for raising an issue!

Would it be possible for you to provide some steps for us to be able to reproduce this issue ourselves?

**Comment by wzli** [comment]
Okay so here is simple substrate pallet with a storage map that takes a tuple for key. I also wrote unit tests that ensure insert and retrieval works as expected.

https://github.com/wzli/substrate-node-template/commit/aa9e5f615440682c9730a3b855a0ae67c3e294a5

on the subxt side, using v0.17, here's the code
```rust
use sp_keyring::AccountKeyring;
use subxt::{ClientBuilder, DefaultConfig, DefaultExtra, PairSigner};

#[subxt::subxt(runtime_metadata_path = "metadata.scale")]
pub mod runtime {}

#[async_std::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    env_logger::init();

    let signer = PairSigner::<DefaultConfig, DefaultExtra<DefaultConfig>, _>::new(
        AccountKeyring::Alice.pair(),
    );
    let api = ClientBuilder::new()
        .set_url("ws://localhost:9944")
        .build()
        .await?
        .to_runtime_api::<runtime::RuntimeApi<DefaultConfig, DefaultExtra<DefaultConfig>>>();

    let test_val = 500;
    let tx_result = api
        .tx()
        .template_module()
        .insert(test_val)
        .sign_and_submit_then_watch(&signer)
        .await?
        .wait_for_finalized_success()
        .await;

    let inserted_event = tx_result?
        .find_first_event::<runtime::template_module::events::SomethingInserted>()?
        .unwrap();
    let runtime::template_module::events::SomethingInserted((acc_id, nonce), _) = inserted_event;
    let val = api
        .storage()
        .template_module()
        .tuple_map(acc_id, nonce, None)
        .await?;

    println!("sent {test_val:?} got {val:?}");

    let mut map = api.storage().template_module().tuple_map_iter(None).await?;
    while let Some(x) = map.next().await? {
        println!("{x:?}");
    }
    
    Ok(())
}  
```

Think you guys can pick up from here. In the example code, the print saids "sent 500 got None", even though iterating the map proves insert was successful.

**Comment by ascjones** [comment]
The bug is because it is incorrectly assuming that a tuple key belongs to a `StorageNMap` entry: https://github.com/paritytech/substrate/blob/27b8806ed82844bb5283a4dadf853ee518fd042f/frame/support/src/storage/types/nmap.rs#L455.

What it should do is check how many hashers there are, if there is 1 then it is a regular `StorageMap` so hash the whole key (as in this case). If hashers_count == tuple_field_count then hash each individual field with their respective hashers.

This is the kind of thing that will need a test, as demonstrated by this bug...

**Comment by jsdw** [comment]
@wzli hopefully this will resolve your bug, if you'd like to point to that branch for now until it merges: https://github.com/paritytech/subxt/pull/458
