### ISSUE TITLE
 message: Unsupported metadata version V13

### ISSUE THREAD

**Issue by nuel77** [paritytech/subxt#452]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/50878033/154242737-a79eec64-8fce-41a5-819b-3b0858ecc5bd.png">
cant connect to local node , is metadata v13 depricated?

**Comment by jsdw** [comment]
Subxt only supports V14 metadata and onwards I'm afraid, as that is the version at which the type information was added that allowed us to do reliable codegen :)
