### ISSUE TITLE
outdated instructions for integration testing

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/subxt#480]
I'm trying to build `subxt` from source so that I can work on a potential contribution.

While trying to compile, I run into:
```
$ cargo build
...
error: failed to run custom build command for `test-runtime v0.18.1 (/home/bear/develop/subxt/test-runtime)`

Caused by:
  process didn't exit successfully: `/home/bear/develop/subxt/target/debug/build/test-runtime-92f2fc1489822e0a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'A substrate binary should be installed on your path for testing purposes. See https://github.com/paritytech/subxt/tree/master#integration-testing', test-runtime/build.rs:62:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The [integration testing](https://github.com/paritytech/subxt/tree/master#integration-testing) instructions also seem outdated, leading into:
```
$ cargo install --git https://github.com/paritytech/substrate node-cli --tag=polkadot-v0.9.10 --force
    Updating git repository `https://github.com/paritytech/substrate`
error: failed to find tag `polkadot-v0.9.10`

Caused by:
  reference 'refs/remotes/origin/tags/polkadot-v0.9.10' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by jsdw** [comment]
Thanks for letting us know! Yep, those docs don't seem to be correct any more.

In general, master on substrate will be fine, so you  can just `cargo install --git https://github.com/paritytech/substrate node-cli --force`. Every now and then, there is a breaking change in Substrate w.r.t subxt, whic his highlighted by our nightly CI runs on Subxt and is normally addressed reasonably prompty.

**Comment by jsdw** [comment]
This also relates to #351, which would hide the integration tests behind a feature flag so that you wouldn't require a substrate binary on your path in order to run the basic `cargo test`.
