### ISSUE TITLE
Support for offline/no_std use cases.

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#484]
I wonder whether we can work towards supporting both the usecases described in #159 and #208 (supporting no_std environments and supporting offline transactions) by:

1. Making sure it's possible to use subxt entirely offline (by providing the runtime metadata manually/relying on compiled metadata entirely as an option, allowing transactions to be built and signed without submitting them, and allowing responses to be interpreted without assuming that they are coming back from the network). Some of this could be echieved by exposing the correct methods in our API to let users follow a more manual workflow, getting and handing bits to subxt code as needed rather than letting subxt handle the network bit too.
2. Supporting `#[no_std]` on those parts of subxt that are separate from the networking side (see https://docs.rust-embedded.org/book/intro/no-std.html on how to use collections and allocation). I'd assume that an allocator could be provided; without this I suspect the work involved would be to great.
3. We'd need to also rely on `no_std` support in supporting crates, such as `frame_metadata`, `scale-info` and such.

I suspect that there is quite a lot of work involved in this, and so I think a first step would be assessing the feasibility of it and having a go at getting some small subset of subxt working in `#[no_std]` and/or supporting crates as needed in separate branches, and if we're happy with how it looks, gradually building out more support from there.

**Comment by gilescope** [comment]
I had a quick see if it would compile to `wasm32-unknown-unknown`.

It's not so bad to get most of the code building to wasm32, though Client::new doesn't which I suspect reduces the functionality somewhat. Also not sure what one would do for this on wasm32:
```
TypeDef::Primitive(TypeDefPrimitive::U64) => {
    consume_type::<BitVec<u64, Lsb0>>(input)
```

Add a few:
`#[cfg(not(target_arch = "wasm32"))]`
or
`#[cfg(target_arch = "wasm32")]`

```
[features]
no_std = ["getrandom/js"] (and add getrandom as a dep)
```
undefault "jsonrpsee/client-ws-transport" feature.

**Comment by jsdw** [comment]
#649 covers certain aspects of this issue. Getting Subxt compiling to WASM feels like one step in the right direction at least.

**Comment by jsdw** [comment]
So, we can now compile to WASM and run Subxt entirely Offline. The remaining thing not addressed here is `#[no_std]`, which is a somewhat bigger hurdle potentially.

I'll close this and let #159 cover that remaining bit.
