### ISSUE TITLE
TransactionError::BlockHashNotFound

### ISSUE THREAD

**Issue by sander2** [paritytech/subxt#487]
We are running into a case where `TransactionError::BlockHashNotFound` is being thrown [here](https://github.com/paritytech/subxt/blob/d9415735c4e04f973fe9ca82a0eaaa93a693478a/subxt/src/transaction.rs#L416-L444). The error message suggest that this probably has to do with fork handling ("The block containing the transaction can no longer be found (perhaps it was on a non-finalized fork?"). My question is, when this occurs, can we be sure that the transaction will never be included? We just want to make sure that if we retry, it is not possible for the original transaction to get included after all.

**Comment by jsdw** [comment]
I think that on the whole, you can't know for sure that a transaction won't make it into the block without giving it a mortality, and waiting for that to expire. That said, you can re-use the same nonce when you retry it to make sure that the retried transaction won't make it into a block if the original one ends up also finding its way into a new block.

**Comment by jsdw** [comment]
I'll close this for now, hoping that the above answered your question, but please reopen if you'd like to continue the discussion :)
