### ISSUE TITLE
Test failing when having a `polkadot` binary started

### ISSUE THREAD

**Issue by lexnv** [paritytech/subxt#497]
The testing framework utilizes the `substrate` binary.
However, when having a `polkadot` binary started (version 4542a603cc) the `cargo test` is failing.

```
> cargo test
...
test frame::balances::constant_existential_deposit ... FAILED

failures:

---- frame::balances::constant_existential_deposit stdout ----
thread 'frame::balances::constant_existential_deposit' panicked at 'assertion failed: `(left == right)`
  left: `10000000000`,
 right: `100000000000000`', subxt/tests/integration/frame/balances.rs:272:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by jsdw** [comment]
Personally I think it would be lovely to do something more like what telemetry does (though it is a little more lines of code):

Here we start the thing listening on port 0:

https://github.com/paritytech/substrate-telemetry/blob/d6ed878cb41a97f7b7b546e996f46ac5dd6215aa/backend/test_utils/src/server/server.rs#L212

And then we take the stdout from that and pass it to a function which waits for the line contianing the actual port it started on and returns it:

https://github.com/paritytech/substrate-telemetry/blob/d6ed878cb41a97f7b7b546e996f46ac5dd6215aa/backend/test_utils/src/server/utils.rs#L26

But it is a bunch more LOC than the current approach, so I'd only really consider it if the current approach def isn't working properly and can't be easily fixed :)

**Comment by lexnv** [comment]
The problem is indeed binding to `0.0.0.0` instead of the local host `127.0.0.1` as in the first example link.

The idea of reading the stdout seems like a great one but indeed adds more LOC and complexity.

Another approach is to reutilize the kernel functionality and ask for port "0".
