### ISSUE TITLE
Rethink (or clarify) approach to metadata

### ISSUE THREAD

**Issue by gregdhill** [paritytech/subxt#500]
Our [clients](https://github.com/interlay/interbtc-clients) use the static metadata as the source of truth, but I've noticed more recently that some aspects of subxt (constants and errors) prefer to dynamically fetch the metadata. This feels weird to me as we lose some compile-time guarantees, for example in explicitly matching error variants.

I'm not sure if this is standard, but on the [interbtc](https://github.com/interlay/interbtc) parachain any change we make that affects the metadata incurs a `spec_version` increment and we reject any client connection from a build with the wrong version (see [here](https://github.com/interlay/interbtc-clients/blob/99b0d4c9f7677230914a3f2f46e0b1cb7c89cbd6/runtime/src/rpc.rs#L71-L79)). Once [validation](https://github.com/paritytech/subxt/pull/478) is implemented, we would then likely validate the full metadata as well.

**Comment by ascjones** [comment]
The philosophy comes from the idea that we can build tooling which can target different chains with compatible pallets. For example, `cargo-contract` was the original use case, to interact with any chain with a compatible `pallet-contracts`.

However as James says we would like to be able to offer a best of both worlds in the API where you can choose the "mode" of operation.

Regarding constants, it was the case before this big refactor that they were fetched from the runtime loaded metadata. I believe that makes sense. e.g. some constants like `RuntimeBlockWeights` might be different between a standalone node and a testnet and a production parachain. But you might want the same tool to operate against all 3 which have the same types but different values.

**Comment by jsdw** [comment]
I'll close this for now, but please re-open if more discussion would be useful :)

**Comment by gregdhill** [comment]
No problem, thanks for the clarification!
