### ISSUE TITLE
Message signature generated from polkadotjs connot be verified through subxt

### ISSUE THREAD

**Issue by alannotnerd** [paritytech/subxt#519]
When trying to submit transaction to moonbeam, It throws a `Bad Signature` error.  Then I found the message connot be verified by subxt. 
```
        let pair = ecdsa::Pair::from_seed_slice(&hex::decode(key).unwrap()[..]).unwrap();
        let sig1 = ecdsa::Signature::from_slice(&hex::decode("0xe1a059d634f6f974042a0e723c6b92f70b497d1e413da0342376aef58e4f2b9232f857cf411bda65925563bdf37286bef4945fae84accd1989485fd357a23ece01").unwrap()[..]).unwrap();
        assert!(ecdsa::Pair::verify(&sig1, b"hello", &pair.public()));
```

**Comment by niklasad1** [comment]
Hi @alannotnerd 

Can you give some more information how you generate the metadata and what extrinsic format are you using i.e, such as [PolkadotExtrinsicParams](https://docs.rs/subxt/latest/subxt/type.PolkadotExtrinsicParams.html?

**Comment by alannotnerd** [comment]
Here is my step:
1. subxt metadata --url https://rpc.api.moonbeam.network  -f bytes > moonbeam.scale
2. generate the custom config
```
impl Config for MoonbeamConfig {
    type Index = u32;
    type BlockNumber = u32;
    type Hash = subxt::sp_core::H256;
    type Hashing = BlakeTwo256;
    type AccountId = AccountId20;
    type Address = AccountId20;
    type Header = subxt::sp_runtime::generic::Header<Self::BlockNumber, BlakeTwo256>;
    type Signature = EthereumSignature;
    type Extrinsic = subxt::sp_runtime::OpaqueExtrinsic;
}
```
refer: https://github.com/PureStake/moonbeam/blob/master/core-primitives/src/lib.rs
3. create pairsigner with that:
```
        let pair = ecdsa::Pair::from_seed_slice(&hex::decode(key).unwrap()[..]).unwrap();
        let signer = MoonbeamPairSigner::new(pair);
```
4. generate the signature of "hello" via polkadotjs in the `sign and verify` page
5. verify the signature with the signer created.
