### ISSUE TITLE
Iterating StorageDoubleMap

### ISSUE THREAD

**Issue by trusch** [paritytech/subxt#526]
Hello,

I'd like to iterate over parts of the content of a StorageDoubleMap. By now subxt generates me two different functions for accessing a double map: 1) Get one element by specifying the primary and the secondary key and 2) Iterate over all the elements in the map.

What I would actually want to do is to only specify the primary key and then iterate over all the entries that belong to this top level key.

Is there any other way of doing this, or am I missing something obvious?

Thanks in advance!

**Comment by jsdw** [comment]
Have a look at the example in #537: https://github.com/paritytech/subxt/pull/537/files#diff-433d49e107326a73dda6220d4f74a4a59b7f5dc745ae54eff523629424db75ed

Hopefully that PR/example addresses this issue, so I'll close it now :)
