### ISSUE TITLE
[Readme] Broken link to substrate binary

### ISSUE THREAD

**Issue by savudani8** [paritytech/subxt#553]
The Readme has become outdated with respect to downloading the substrate binary. Tagged releases are no longer there in the substrate repo.
https://github.com/paritytech/subxt#integration-testing

**Comment by niklasad1** [comment]
The example is just wrong, tags have never been published by substrate per polkadot release.

Either `monthly tags` or `--branch polkadot-v0.9.x`

**Comment by Xanewok** [comment]
https://github.com/paritytech/subxt/pull/546 removed the tag altogether, closing.
