### ISSUE TITLE
futures::join! two Futures from api

### ISSUE THREAD

**Issue by lx38** [paritytech/subxt#558]
Trying to understand how to make parallel calls , just like I can do via polkadotjs/api via Promises.all()

```
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>>{

    let api = ClientBuilder::new()
        .set_url("wss://rpc.polkadot.io:443")
        .build()
        .await?
        .to_runtime_api::<polkadot::api::RuntimeApi<DefaultConfig, SubstrateExtrinsicParams<DefaultConfig>>>();


    let addr = AccountId32::from_str("13Ybj8CPEArUee78DxUAP9yX3ABmFNVQME1ZH4w8HVncHGzc").unwrap();

    let controller = api.storage().staking().bonded(&addr, None);
    let ledger = api.storage().staking().ledger(&addr, None);

    let (a, b) = join!(controller, ledger);

    Ok(())
}
```

What I get is the following:

```
22 |     let controller = api.storage().staking().bonded(&addr, None);
   |                      ^^^^^^^^^^^^^^^^^^^^^^^                    - temporary value is freed at the end of this statement
   |                      |
   |                      creates a temporary which is freed while still in use
...
25 |     let (a, b) = join!(controller, ledger);
   |                        ---------- borrow later used here
```

I can extract staking and ledger as variables, but maybe I do something wrong? probably I do not understand the concept.

**Comment by lx38** [comment]
PS. extracting vars does not help too much. I doing lotsa requests for multiple accounts and Rust code operates 2 times slower than equivalent Nodejs code..

**Comment by jsdw** [comment]
The above PR should make what you originally tried to do work (although note that you should use `PolkadotExtrinsicParams`, not `SubstrateExtrinsicParams` really if you're connecting to a polkadot node (for accessing storage items it makes no difference, but you'd run into issues trying to submit transactions)

**Comment by lx38** [comment]
@jsdw thanks for clarification/example on usage. I can use features w/o any issues now. Thanks for spotting incorrect struct usage. This was taken from `README.md`, where it uses `SubstrateExtrinsicParams` instead of `PolkadotExtrinsicParams`, so I think you shall amend it too..

**Comment by jsdw** [comment]
Ah you're right; I'll tweak the README to fix that error :)
