### ISSUE TITLE
Watch submitted transaction

### ISSUE THREAD

**Issue by gregdhill** [paritytech/subxt#559]
Perhaps this is a feature request for Substrate upstream - since there is no `author_watchExtrinsic` - but it seems like there is no way to monitor the `TransactionProgress` for an extrinsic created using `sign_and_submit`. My goal is to implement a service that submits an extrinsic and returns the hash which the client can watch for inclusion / finalization. What is the recommended approach?

**Comment by jsdw** [comment]
Given that that issue has been open for 2 years, I suspect it'll be a while until it is something we can make use of here I'm afraid! As you've noted, I'm not aware of a way to do this at the moment, though it would be nice to be able to dissociate submitting an extrinsic from tracking its state! 

Please do chime in on the linked issue if you have a use case for it, but in the meantime I'm liable to closing this as there isn't much we can do here.

**Comment by polariseye** [comment]
hi, there is a way to Watch submitted transaction by use the third http api. such as subscan. or you can monitor all block in server side

**Comment by jsdw** [comment]
If you submitted a transaction, you can monitor the transaction progress that is fed back via the socket (this is what subxt does). if you lose that connection or submitted a transaction in the past, there's no way to know which block it appeared in without using a third party tool as you suggest, but this is definitely out of scope for what subxt can do.

I'll close this now as there's nothing obvious that we can do on this side at the mo.
