### ISSUE TITLE
ld.exe: error: export ordinal too large: 69899

### ISSUE THREAD

**Issue by polariseye** [paritytech/subxt#562]
there is my test code.but build errror:
````
use subxt::*;

#[tokio::main]
async fn main() {
    get_balance_test().await
}

#[subxt::subxt(runtime_metadata_path = "artifacts/polkadot_metadata.scale")]
mod polkadot {}

async fn get_balance_test(){
    let api=ClientBuilder::new()
        .set_url("wss://rpc.polkadot.io:443")
        .build()
        .await.unwrap()
        .to_runtime_api::<polkadot::RuntimeApi<DefaultConfig, PolkadotExtrinsicParams<DefaultConfig>>>();

    let total_issuance = api
        .storage()
        .balances()
        .total_issuance(None)
        .await
        .unwrap();
}

````
error detail is:
````
/lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: export ordinal too large: 69899
````
the environment i build is: windows 10, rust 1.61.0 

i have search some issues like this https://github.com/PointCloudLibrary/pcl/issues/3672. but i do not know how to fix this. could you help me

**Comment by niklasad1** [comment]
Hey, can you report which rust toolchain and version you are using?

You are sure that your hard drive isn't full? 

This project hasn't been tested against Windows and it might reach the shared library limit in Windows.

https://github.com/gakonst/ethers-rs/issues/880
https://www.reddit.com/r/rust/comments/gle181/suddenly_compile_errors_on_windows/

**Comment by jsdw** [comment]
Also https://users.rust-lang.org/t/export-ordinal-too-large-error-while-linking/74547/2 suggests a solution which may be worth trying?

**Comment by polariseye** [comment]
> 

yeah,my hard drive isn't full. it's the limit of windows.i have skip this error by build in linux
