### ISSUE TITLE
Failed to load system certs: No valid certificate found

### ISSUE THREAD

**Issue by buraktabn** [paritytech/subxt#563]
I'm using subxt to get signed extrinsics so I can call call `submit_extrinsic` from native Dart/Flutter. (I'm working on a Substrate Dart library that wip and basically I need subxt for encoding.) I've encountered this issue on Android. Only happens on `wss`, localhost works fine.

```
 cargo ndk -t x86_64 -t arm64-v8a
```

```rust
pub async fn create<T: Into<String>>(url: T) -> anyhow::Result<Client<DefaultConfig>> {
    Ok(ClientBuilder::new()
        .set_url(url)
        .build::<DefaultConfig>()
        .await?)
}

pub async fn create_xt(client: &Client<DefaultConfig>) -> anyhow::Result<Vec<u8>> {
    let bob = AccountKeyring::Bob.public();
    // TransactionApi created from codegen
    let api = TransactionApi::<
        _,
        SubstrateExtrinsicParams<DefaultConfig>,
    >::new(&client);
    let transfer_xt = api.transfer(MultiAddress::Address32(bob.0), 12345641)?;
    let signer = subxt::PairSigner::new(AccountKeyring::Alice.pair());
    let signed = transfer_xt
        .create_signed(&signer, Default::default())
        .await?
        .0;
    Ok(signed)
}
```
```
Rpc error: Networking or low-level protocol error: Failed to load system certs: No valid certificate found
```

Test passes and works fine in Linux. Since I'm using FFI debugging is limited from Flutter side.

Error thrown in [here](https://github.com/paritytech/jsonrpsee/blob/master/client/transport/src/ws/mod.rs#L513).

maybe related to https://github.com/paritytech/jsonrpsee/pull/321

**Comment by niklasad1** [comment]
hey @buraktabn 

This error is because [rustls-native-certs](https://github.com/rustls/rustls-native-certs) doesn't support android.

You could try configuring the ws-client yourself and change the [certification store](https://docs.rs/jsonrpsee-ws-client/latest/jsonrpsee_ws_client/struct.WsClientBuilder.html#method.certificate_store) to `webpki` but I'm not sure whether it works

**Comment by buraktabn** [comment]
Changing the [certification store](https://docs.rs/jsonrpsee-ws-client/latest/jsonrpsee_ws_client/struct.WsClientBuilder.html#method.certificate_store) to `webpki` solved the issue.
