### ISSUE TITLE
question: Change the dependency can support polkadot-v0.9.18?

### ISSUE THREAD

**Issue by DaviRain-Su** [paritytech/subxt#564]
I added some git dependencies to make subxt support polkadot-v0.9.18, but I ran into some problems if this version of subxt doesn't support v0.9.18.
Here are some errors.
```
Error: Rpc(Call(Custom(ErrorObject { code: ServerError(1002), message: "Verification Error: Runtime error: Execution failed: Error calling api function: Failed to convert parameter `tx` from node to runtime of validate_transaction", data: Some(RawValue("Runtime error: Execution failed: Error calling api function: Failed to convert parameter `tx` from node to runtime of validate_transaction")) })))
```

**Comment by niklasad1** [comment]
Just to ask, did you fetch the metadata from the node (polkadot-v0.9.18)?

It's a bit tricky I suppose you have to patch all substrate dependencies in subxt.

**Comment by jsdw** [comment]
I would expect subxt to work with 0.9.18 I think, but as Niklas says, you do need to obtain metadata from the node you're running and then point subxt at that metadata so that it can generate the correct interface.

**Comment by DaviRain-Su** [comment]
> 

Yes, I have fix all dependencies

**Comment by DaviRain-Su** [comment]
> I would expect subxt to work with 0.9.18 I think, but as Niklas says, you do need to obtain metadata from the node you're running and then point subxt at that metadata so that it can generate the correct interface.

OK, thank man, I have try it.

**Comment by DaviRain-Su** [comment]
Is there a use case for `BaseExtrinsicParams` customization?
```
/// An implementation of [`ExtrinsicParams`] that is suitable for constructing
/// extrinsics that can be sent to a node with the same signed extra and additional
/// parameters as a Polkadot/Substrate node. The way that tip payments are specified
/// differs between Substrate and Polkadot nodes, and so we are generic over that in
/// order to support both here with relative ease.
///
/// If your node differs in the "signed extra" and "additional" parameters expected
/// to be sent/signed with a transaction, then you can define your own type which
/// implements the [`ExtrinsicParams`] trait.
#[derive(Debug)]
pub struct BaseExtrinsicParams<T: Config, Tip: Debug> {
    era: Era,
    nonce: T::Index,
    tip: Tip,
    spec_version: u32,
    transaction_version: u32,
    genesis_hash: T::Hash,
    mortality_checkpoint: T::Hash,
    marker: std::marker::PhantomData<T>,
}
```

**Comment by DaviRain-Su** [comment]
Hi, what is the difference between AssetTip and PlainTip, can you explain it?

**Comment by DaviRain-Su** [comment]
> I added some git dependencies to make subxt support polkadot-v0.9.18, but I ran into some problems if this version of subxt doesn't support v0.9.18. Here are some errors.
> 
> ```
> Error: Rpc(Call(Custom(ErrorObject { code: ServerError(1002), message: "Verification Error: Runtime error: Execution failed: Error calling api function: Failed to convert parameter `tx` from node to runtime of validate_transaction", data: Some(RawValue("Runtime error: Execution failed: Error calling api function: Failed to convert parameter `tx` from node to runtime of validate_transaction")) })))
> ```

I found out that I was using SubstrateExtrinsicParams for this problem, so I switched to PolkadotExtrinsicParams and it worked.
