### ISSUE TITLE
`PairSigner` owns `Pair`, while it doesn't need to

### ISSUE THREAD

**Issue by armyhaylenko** [paritytech/subxt#589]
Hey guys! I've been working with `subxt` a bit and found out that whenever I create a `PairSigner` from any `Pair` type, the `PairSigner` takes ownership of the `Pair`, and I'm not able to reuse it after. Consider a use case:

```rust
pub async fn run(
	api: node_metadata::RuntimeApi<
		DefaultConfig,
		PolkadotExtrinsicParams<DefaultConfig>,
	>,
	pair: sp_core::sr25519::Pair,
) {
	let interval = tokio::time::interval(Duration::from_secs(6));
	let start = tokio::time::Instant::now();

	tokio_stream::wrappers::IntervalStream::new(interval)
		.for_each(|now| {
			let elapsed = now.duration_since(start).as_secs_f32();
			async move {
				let signer = PairSigner::new(pair); // takes ownership of pair within the async function, compile error
				let amount = elapsed.trunc() as u64 % 10;
				let tx_hash = api
					.tx()
					.balances()
					.transfer(BOB, amount)
					.unwrap()
					.sign_and_submit_default(&signer)
					.await
					.unwrap();
				log::info!(target: "runtime::client", "Transferred {} UNITs to BOB, tx hash: {:?}", amount, tx_hash);
			}
		})
		.await
}

```

As you can see, we can't use PairSigner in async iterations - they take ownership of everything referenced. The reason for the creation of the extrinsic in the `async move {...}` block is that we dynamically change the transferred amount.
Now, here's how I'd want to use it:

```rust
pub async fn run(
	api: node_metadata::RuntimeApi<
		DefaultConfig,
		PolkadotExtrinsicParams<DefaultConfig>,
	>,
	pair: sp_core::sr25519::Pair,
) {
	let api = Arc::new(api);
	let pair = Arc::new(pair);

	let interval = tokio::time::interval(Duration::from_secs(6));
	let start = tokio::time::Instant::now();

	tokio_stream::wrappers::IntervalStream::new(interval)
		.for_each(|now| {
			let api = api.clone();
			let pair = pair.clone();
			let elapsed = now.duration_since(start).as_secs_f32();
			async move {
				let signer = PairSigner::new(pair); // takes ownership of the cloned Arc, compiles fine
				let amount = elapsed.trunc() as u64 % 10;
				let tx_hash = api
					.tx()
					.balances()
					.transfer(BOB, amount)
					.unwrap()
					.sign_and_submit_default(&signer)
					.await
					.unwrap();
				log::info!(target: "runtime::client", "Transferred {} UNITs to BOB, tx hash: {:?}", amount, tx_hash);
			}
		})
		.await
}
```

Unfortunately, this is not possible due to the definition [here](https://github.com/paritytech/subxt/blob/a90697ca2926dd698f5f26f62837b9d966be2ad8/subxt/src/extrinsic/signer.rs#L53). All functions within the `Signer` trait do not take ownership of `self`, consequently not taking ownership of the `Pair` contained inside. Is there any way `subxt` can be refactored to accept references (borrows, `Rc`s, `Arc`s, etc.) in `PairSigner::new()`, and hold them as such in the `pair` field? Or is it too much hassle to add? Thanks :)

**Comment by jsdw** [comment]
I'll add this to our Tidy and Polish milestone and we can have a look and see whether it makes sense or not when we get to looking at it :)

**Comment by armyhaylenko** [comment]
Beautiful! Thanks, closing.

**Comment by armyhaylenko** [comment]
Whoops, guess it might be useful to see as open in the Milestones, sry, reopening

**Comment by jsdw** [comment]
So, I had a look and since `PairSigner` accepts an arbitrary `P: Pair`, the only reason you can't pass a reference is because `sp_core::sr25519::Pair` (the concrete type) doesn't impl `Pair` for `&Self`.

(in other words, the Subxt specific code I thin already _does_ accept a reference there; we just don't have a reference type that meets the trait bounds).

You may have some success writing something like:

```
struct PairRef<'a>(&'a sp_core::sr25519::Pair);

impl <'a> sp_core::Pair for PairRef<'a> {
    // .... functions just delegate to self.0
} 
```

I'd suggest that if that works, it would be the best way to approach your usecase if you would rather pass a reference.

Having a look at the concrete `Pair` type though, I wouldn't worry too much about cloning it (everything looks to be stack allocated so it should be cheap anyway).

I'm going to close this for now, because I think that the above should resolve/address the concern, but do re-open if you'd like to discuss further, or think that there is still something subxt is lacking in the area.

**Comment by armyhaylenko** [comment]
Nope, that's fine, definitely not worth moving forward with regards to what you mentioned. Using newtype is perfectly fine in that case. Thx :)
