### ISSUE TITLE
Light client support / generalizing over RPC provider

### ISSUE THREAD

**Issue by rphmeier** [paritytech/subxt#596]
I'm playing around with [smoldot](https://github.com/paritytech/smoldot) and trying to combine it with subxt. The smoldot light-base library gives access to RPCs against the node.

In principle, this should work fine with subxt except for the fact that subxt directly uses the `jsonrpsee::Client` and `ClientBuilder` which has some deeply-baked assumption about using websockets (as seen in the [`TransportSenderT`](https://docs.rs/jsonrpsee-core/latest/jsonrpsee_core/client/trait.TransportSenderT.html)).

If not for that, it would be relatively straightforward to build the `jsonrpsee::Client` with custom transport types. However, I think this may be better addressed at the `subxt` level by having the `subxt::rpc::RpcClient` be generic over an `R: jsonrpsee::ClientT + jsonrpsee::SubscriptionClientT` which would allow us to implement a shim over a smoldot light-client.

This unfortunately does need to add a generic parameter instead of a trait object because the `ClientT` traits aren't object-safe as they contain generic functions. There is a possibility to do an upstream contribution to `jsonrpsee` to introduce `UntypedClientT` and `UntypedSubscriptionClientT` traits which are object-safe and over which you can build a decoding wrapper. That would avoid the extra generic parameter at the cost of virtual calls, which would be dominated by network utilization anyway.

**Comment by niklasad1** [comment]
> In principle, this should work fine with subxt except for the fact that subxt directly uses the jsonrpsee::Client and ClientBuilder which has some deeply-baked assumption about using websockets (as seen in the [TransportSenderT](https://docs.rs/jsonrpsee-core/latest/jsonrpsee_core/client/trait.TransportSenderT.html)).

Fair point,  `send_ping` and `close` is intended to be optional we probably missed that during some recent refactoring.
Ideally those should be moved to an extension trait and just have `send` in the `TransportSenderT`.

**Comment by arrudagates** [comment]
> I'm playing around with [smoldot](https://github.com/paritytech/smoldot) and trying to combine it with subxt. The smoldot light-base library gives access to RPCs against the node.
> 
> In principle, this should work fine with subxt except for the fact that subxt directly uses the `jsonrpsee::Client` and `ClientBuilder` which has some deeply-baked assumption about using websockets (as seen in the [`TransportSenderT`](https://docs.rs/jsonrpsee-core/latest/jsonrpsee_core/client/trait.TransportSenderT.html)).
> 
> If not for that, it would be relatively straightforward to build the `jsonrpsee::Client` with custom transport types. However, I think this may be better addressed at the `subxt` level by having the `subxt::rpc::RpcClient` be generic over an `R: jsonrpsee::ClientT + jsonrpsee::SubscriptionClientT` which would allow us to implement a shim over a smoldot light-client.
> 
> This unfortunately does need to add a generic parameter instead of a trait object because the `ClientT` traits aren't object-safe as they contain generic functions. There is a possibility to do an upstream contribution to `jsonrpsee` to introduce `UntypedClientT` and `UntypedSubscriptionClientT` traits which are object-safe and over which you can build a decoding wrapper. That would avoid the extra generic parameter at the cost of virtual calls, which would be dominated by network utilization anyway.

Would you mind sharing what you have written already? There isn't any complete Rust implementation, since the only current implementation of the light client is a combination of Rust/Wasm with JavaScript, but if you got to the point of trying to connect subxt to it (assuming you're not just running the JavaScript version on the side), that code would be a massive help to me!

**Comment by rphmeier** [comment]
@arrudagates I didn't write anything concrete because I could tell from reading the code of the [smoldot `light_base`](https://github.com/paritytech/smoldot/blob/main/bin/light-base/src/lib.rs), which should work on native as well, and the docs of subxt that this would be an issue.

**Comment by jsdw** [comment]
Just FYi how I'd like to approach this issue is to create a new `RpcClientT` trait (or something) in `subxt` and then implement that for the jsonrpsee Rpc client; this'll allow us to fine tune the trait to exactly what we need and hopefully make it a little more straightforward for `subxt` users than going the other way around and implementing the required jsonrpsee traits.

**Comment by rphmeier** [comment]
That sounds like a reasonable approach; it's usually better to generalize within the library and decouple from specific backends.
