### ISSUE TITLE
Should we reuse the generated RPC API definitions from Substrate?

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#605]
Instead of implementing our own RPC methods, would/should we be able to reuse the definitions from substrate?

See https://github.com/paritytech/substrate/pull/11939#pullrequestreview-1056291425 for context.

We'd need to feature-gate bits in substrate to let us get at what we want (see the comment)

Pros: 
- A load of substrate RPC's would be available by default.

Downsides: 
- We'd need to publish another substrate crate (or crates; I haven't looked at the tree) to access the definitions
- Definitions may not have the types we'd prefer.
- Updating definitions to match involves publishing substrate crates (a pain).

**Comment by jsdw** [comment]
Actually, since we'd like to generalise over RPC provider (see https://github.com/paritytech/subxt/issues/596), let's not tie ourselves to jsonrpsee more with a change like this.

**Comment by niklasad1** [comment]
Makes sense, also subxt is using some customized types such as `RuntimeVersion` which might also be quite awkward to workaround.

**Comment by seunlanlege** [comment]
Is there any support in subxt right now for generating the node's rpc interface?

**Comment by niklasad1** [comment]
> Is there any support in subxt right now for generating the node's rpc interface?

No, the RPC's used by subxt is handwritten.
I assume you want runtime and chain custom RPCs as well then?
That would indeed be cool but I think that is quite hard with all the generics (i.e, not necessarily scale encoded), one would need to call `rpc_methods` and generate the RPC interface from that.

Maybe a reason to look into https://github.com/paritytech/jsonrpsee/issues/737 :)
