### ISSUE TITLE
Support more types in Storage entry constructors

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#610]
Basically, for any types needed in storage entries, we allow `impl Borrow<#ty>` for it. We have some custom logic so that if the type is `Vec<T>` we allow `impl Borrow<[T]>` for more flexibility. Can we do the same for types like `String` (prefer `str`) and `Box<T>` (prefer `T`) and so on?

See https://github.com/paritytech/subxt/pull/593#discussion_r938598968

**Comment by tadeohepperle** [comment]
Closing this, as it was fixed by #1105.
