### ISSUE TITLE
Anyhow does not allow subxt to be used on stable Rust

### ISSUE THREAD

**Issue by lx38** [paritytech/subxt#615]
When I try to build a simple app which use subxt, it reports
```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.60/src/lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(backtrace))]
    |                                ^^^^^^^^^
```

It seems that some package depends on anyhow which uses nightly features. 

Can we fix that?

Its a plain simple package with only Cargo.toml
```
[package]
name = "subxt-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
subxt ="0.22.0"
```

**Comment by niklasad1** [comment]
hey @lx38 

Can you report which rustc version you are using?
It indeed looks weird and should work

**Comment by lx38** [comment]
So far in order to solve this problem I went to remove/reinstall my toolchains and deleted ./target folder . Now seems to be I do not get this error anymore. So there was some edge case probably with anyhow lib.

While trying to find the solution I met similar report re anyhow yesterday in Issues on GitHub, but unfortunately cannot recall in this crate it was.  

Thanks for looking into.
