### ISSUE TITLE
CLI Tool: Support accessing constants

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#621]
As the title suggests. See #583 for a rough idea with transactions and #620 for accessing storage items. We'll want a similar thing to access constants.

**Comment by tadeohepperle** [comment]
@jsdw @lexnv @niklasad1 
I want to use the following command structure to unify exploring constants, calls, storage and maybe events. 
The key idea is to structure the explore command like a tree where each internal node gives the user feedback to explore it's children or take further action directly (e.g. querying storage, constructing extrinsics, etc...).

![subxt explore proposal](https://github.com/paritytech/subxt/assets/62739623/8a097ea3-d5ff-4473-a8fa-cd968dfd51fa)

Please let me know any feedback.

**Comment by jsdw** [comment]
I know I said already in the morning chat but looks awesome to me :) 

To put my only thoughts into writing here:

- `subxt explore Balances storage holds_root ()`: I'd probably ditch the `()` and just output the final result immediately if no arguments are needed.
- (another random thought; can we allow any case for pallet names; "balances" should work too I think)
- `subxt explore <pallet_name>` should probably just tell the user that they can look at `storage` or `calls` or `constants` and not list them all because there will be a lot of them :)

**Comment by lexnv** [comment]
We might want to extend the `explore` command in the future to contain some different
information than exploring the pallets.

One thing that comes to mind is that it would be useful for users to explore some custom
type from the type registry of the metadata: for example, exploring what the extrinsic type
contains, or iterating and describing the signed extensions.

We could probably in this case make the pallet exploration explicit by prefixing:

```
# List the available options as in: storage calls constants 
explore --pallet System

# Explore the type ID 102 of the type registry
explore --type-id 102

# Explore the information contained by the ExtrinsicMetadata from frame-metadata
explore --extrinsic-type 
```

Although, it is a good first step to implement the explore for exclusive access to the pallets and
we could then have another pass-over (and if we have enough depend) to add the other things
(I personally had to look quite a bit in the metadata json format of extrinsics and type IDs 
for decoding the extrinsics)

As another crazy idea, the CLI also supports the `compatibility` command which checks if a list of nodes
are compatible in terms of metadata hashing. It might also be worth exploring in the future a way to
describe the differences in a more human-readable format which makes a diff of the pallets / types 
that changed / were added / or removed
