### ISSUE TITLE
provide `finalized headers abstraction` that fetches "skipped" blocks when subscribing to `chain_finalizedHeads`

### ISSUE THREAD

**Issue by niklasad1** [paritytech/subxt#630]
> Currently, follow-chain executes only these blocks, that come from subscription for finalizedHeads. Although this works as expected in Polkadot, for some chains some blocks may lack justification (although their successor have). Such block will be ignored, which might lead to a corrupted local state. This is the case that happens at e.g. AlephZero-based chains and possibly other.

I reckon that useful for many users of subxt to not have to implement this themselves

See https://github.com/paritytech/substrate/pull/12048/files for more informatuon

**Comment by jsdw** [comment]
I don't quite follow; we already have an `api.events().subscribe_finalized()` thing which uses `chain_subscribeFinalizedHeads` under the hood and already fills in any gaps owing to that thing sometimes missing blocks. Is that what you have in mind, or something else?

**Comment by niklasad1** [comment]
> Is that what you have in mind, or something else?

Yes, AFAIU `rpc().subscribe_finalized_heads()` just performs a pure subscriptions to `chain_subscribeFinalizedHeads` which might have gaps. 

Thus, I would want to have something similar for that or am I missing something?

**Comment by lexnv** [comment]
The [subscribe_finalized](https://github.com/paritytech/subxt/blob/4722028ce709caed30625ee6779240141390ad74/subxt/src/events/events_client.rs#L165) function will fill in the gaps using [subscribe_to_block_headers_filling_in_gaps](https://github.com/paritytech/subxt/blob/4722028ce709caed30625ee6779240141390ad74/subxt/src/events/events_client.rs#L196) for events only.

We also have a test scenario for filling in the gaps [here](https://github.com/paritytech/subxt/blob/4722028ce709caed30625ee6779240141390ad74/testing/integration-tests/src/events/mod.rs#L173).

I think we could have something similar to `rpc().subscribe_finalized_heads_with_gaps()` that returns directly the `BlockT::Header`, filling in all the gaps as above 😄
