### ISSUE TITLE
Expose type aliases for extrinsic parameters

### ISSUE THREAD

**Issue by lexnv** [paritytech/subxt#632]
Consider the following generated code:

```rust
pub struct Enter {
    pub data: runtime_types::polkadot_primitives::v2::InherentData<
        runtime_types::sp_runtime::generic::header::Header<
            ::core::primitive::u32,
            runtime_types::sp_runtime::traits::BlakeTwo256,
        >,
    >,
}
pub struct TransactionApi;
impl TransactionApi {
    #[doc = "Enter the paras inherent. This will process bitfields and backed candidates."]
    pub fn enter(
        &self,
        data: runtime_types::polkadot_primitives::v2::InherentData<
            runtime_types::sp_runtime::generic::header::Header<
                ::core::primitive::u32,
                runtime_types::sp_runtime::traits::BlakeTwo256,
            >,
        >,
    ) -> ::subxt::tx::StaticTxPayload<Enter> {
```

The `enter` extrinsic contains a data of type `InherentData<Header<u32,  BlakeTwo256>>`.

Add the ability to name this type directly from subxt

```rust
type InherentData = runtime_types::polkadot_primitives::v2::InherentData<Header<u32,  BlakeTwo256>>;

pub struct Enter {
    pub data: InherentData,
}

pub fn enter(&self, data: InherentData) -> ... 
```

This could improve the code maintainability of subxt' users that rely on the static code: https://github.com/paritytech/polkadot-introspector/pull/90/files#diff-baf94f8f2daab6784f9d016ebd42f06d62eeb5961c59f2320af7ce411b41dd82R49

**Comment by jsdw** [comment]
I think the question I have is; how far do we go here?

We name the types passed to transaciton calls and such, but how many other types should we try to name, and what is the risk of naming collisions from doing so?

**Comment by jsdw** [comment]
@lexnv I think we did this in the end didn't we (and actually exposed type aliases for a load of things) so I'll close this now, but feel free to re-open or comment if I'm wrong :)
