### ISSUE TITLE
Add option for automatic metadata download to macro

### ISSUE THREAD

**Issue by cmichi** [paritytech/subxt#640]
## Problem Statement

For compile-time generated types `subxt` currently requires having the metadata as a fixture locally:

```rust
#[subxt::subxt(runtime_metadata_path = "metadata/contracts-node.scale")]
pub mod api {}
```

We are using `subxt` as part of [an E2E testing framework](https://github.com/paritytech/ink/issues/1234) that we'll ship with the next major ink! release. Developers can then write tests for their contracts in the usual `#[test]` style, with an E2E test being executed in the background.

As ink! needs to support all kind of Substrate runtimes this would currently require us to make `subxt-cli` a dep of ink!, and devs would have to execute `subxt metadata > contracts-node.scale` before running their E2E tests.

## Solution Ideas

Could we make the `runtime_metadata_path` optional and if omitted download the metadata from the node for each macro invocation?

**Comment by niklasad1** [comment]
or have something else like:

```
#[subxt::subxt(fetch_metadata_url = "http://myurl.com", name = "chain_foo")]
pub mod api {}
```

`name` would store the metadata as `chain_foo.scale`, not exactly sure how to deal with duplicate metadata files and to avoid downloading already fetched metadata

**Comment by cmichi** [comment]
> I guess there's no reason it'd need to store the metadata either; just download it and pass it straight into the codegen stuff. it would mean you'd have to have a node available to download from, but there's precedent in things like sqlx which requires compile time access to a running DB for instance (well, by default).

This is the solution that would work best for us.

The context is that having a fixed file path typically leads to all kinds of problems if the contract is built from a different folder or in a CI setup, where the target dir is usually dependent on the environment variables.

**Comment by jsdw** [comment]
That makes sense!

So I guess since we already have:

```rust
#[subxt::subxt(runtime_metadata_path = "metadata/contracts-node.scale")]
pub mod api {}
```

I'd propose we also support something like:

```rust
#[subxt::subxt(runtime_metadata_url = "ws://localhost:9944")]
pub mod api {}
```

(supporting http, ws, and probably also https and wss to maximise the locations you can acquire it from)

**Comment by cmichi** [comment]
That would be perfect!

**Comment by ascjones** [comment]
This option should also be available in the `subxt-codegen` api https://github.com/paritytech/subxt/blob/e48f0e3b1de130779abb3dd092c86b845de81116/codegen/src/api/mod.rs#L54. Both the macro and the CLI call in to this, and possibly could just move some of the code from the CLI which already fetches the remove metadata into the codegen.
