### ISSUE TITLE
Cached metadata location management

### ISSUE THREAD

**Issue by lexnv** [paritytech/subxt#641]
Let's add a cached managed location for metadata.

This improves the `subxt` macro by allowing users to omit the `runtime_metadata_path`.
The metadata can be downloaded internally by the subxt macro, only once if the file's system cache is not populated.
This feature will greatly improve user ergonomics and metadata maintanance, as well as the https://github.com/paritytech/subxt/issues/640 request because the metadata is downloaded once. 

# Implementation Details

This can be of course a silent breaking change between "cached" metadata and runtime node's metadata, therefore I suggest this to be an opt-in feature.

## Cache Keyword

Introduce the `cache` keyword for the `subxt` macro.

When the `subxt` macro receives the `cache` keyword, it will utilize the metadata provided at the default cache location.
However, if the metadata is not found at the cache location, `subxt` will fetch the runtime metadata from the chain and persist it to the cached location for further usage.

The implementation of `cache` feature requires:
- Cached directory (the path for all metadatas - This is intrinsically provided)
- The name of the chain (the name for the metadata).
- URL of the chain (from where to download the metadata if not already cached).

### Macro anatomy

The full format of the `cache` feature can take in the `chain`'s name and the URL from which to fetch the metadata:

```rust
#[subxt::subxt(cache(chain = "polkadot", url = "wss://rpc.polkadot.io:443")]
pub mod polkadot {}
```

The minimum requirement for the `cache` feature is the `url` location, whereas the `chain`'s name can be derived from the `pub mod [chain]` name.

```rust
#[subxt::subxt(cache(url = "wss://rpc.polkadot.io:443")]
pub mod polkadot {}
```

### Cached Directory

The cache directory is located at `~/.subxt/metadata/[chain].scale`, for organizational simplicity.
This gives us future flexibility for other file system features, without being a breaking change for users.
(ie, we might not want to store metadata at `~/.subxt/[chain.scale]` indefinitely).

To ensure concurrent access to the cached directory, a file lock can be introduced at `~/.subxt/.lock` with `flock` primitives.

# Limitations

## Metadata Rotation

The cached managed location has shifted the responsibility of keeping the metadata in sync from the user to the subxt.

With rapid development, chains can quickly go out of sync. For those use-cases, we recommend managing the metadata manually `#[subxt::subxt(runtime_metadata_path = "../artifacts/polkadot_metadata.scale")]` or to fetch it always as described here https://github.com/paritytech/subxt/issues/640.

For more stable chains, chains that don't update the metadata often or perform fewer runtime updates, we can mitigate the rotation limitation by fetching the metadata periodically. If the cached metadata is older than 1 week, which is less than the 2-week deployment cycle of polkadot, we update the metadata.

This mitigates the rotation of the metadata for short-medium lived subxt instances but does not mitigate a potential desynchronization for subxt processes that live more than 2 weeks. For those use cases, the dynamic API can be a more appropriate way of handling node communication.

**Comment by jsdw** [comment]
The value of adding caching is avoiding that metadata download, but the disadvantage is that you should still check the runtime version etc to make sure the node metadata/chain hasn't changed. Any issues with the cache being stale/invalid would be hard to debug.

I think I basically prefer that we keep things explicit for now; if people want metadata from a URL, let's support that, and if people want to download and point to metadata offline, we support that too, and there's no magic or caching there so it's relatively easy to debug and hard to run into staleness things :)

If people point mainly to localhost nodes, the caching would be somewhat irrelevant I think, but if it turns out that people are using the URL feature pointed at nodes on the internet, then maybe this becomes more valuable/useful! Let's see what happens :)

**Comment by jsdw** [comment]
I'm tempted to close this for now; I think we should focus on #640, and only consider adding caching of the downloaded metadata if we have a strong reason to do so, since it'll introduce its own complexities and hurdles :)
