### ISSUE TITLE
Support compiling Subxt to WASM

### ISSUE THREAD

**Issue by amiyatulu** [paritytech/subxt#649]
subxt is not supported in [yew](https://yew.rs/). It gives error on `trunk serve`

```
error[E0583]: file not found for module `sys`
   --> /home/amiya/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/lib.rs:124:1
    |
124 | mod sys;
    | ^^^^^^^^
    |
    = help: to create the module `sys`, create file "/home/amiya/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/sys.rs" or "/home/amiya/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/sys/mod.rs"

error: Socket2 doesn't support the compile target
   --> /home/amiya/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.7/src/lib.rs:127:1
    |
127 | compile_error!("Socket2 doesn't support the compile target");

```

**Comment by niklasad1** [comment]
Yeah, it doesn't work at the moment.

You would have to disable to `jsonrpsee` feature and provide your own `JSON-RPC transport` for now to compile down to WASM.
It might be other things along the way too, I should look into that

**Comment by niklasad1** [comment]
Blocked on https://github.com/paritytech/scale-decode/issues/4 for now

**Comment by jsdw** [comment]
And now blocked on getting the right features etc enabled to make the substrate based crates play nicely.

**Comment by Xanewok** [comment]
FYI I started working on it, hopefully this will not be blocked by any version releases upstream.

**Comment by niklasad1** [comment]
@Xanewok I forgot to mention that I already have a branch for that https://github.com/paritytech/subxt/compare/na-wasm-support?expand=1

Perhaps your stuff is better but feel free to use anything from there :P

**Comment by niklasad1** [comment]
My stuff is using a special jsonrpsee branch to have `async-wasm-feature` but it should work on the latest release with a bunch of replace `jsonrpsee` with `jsonrpsee-wasm-client` instead of that feature I used.

**Comment by Xanewok** [comment]
Oh, that's great, thanks!

**Comment by amiyatulu** [comment]
Hi 
subxt = "0.25.0"

still gives the same error  `compile_error!("Socket2 doesn't support the compile target");`
