### ISSUE TITLE
runtime upgrades API: provide low-level API

### ISSUE THREAD

**Issue by niklasad1** [paritytech/subxt#652]
Currently, it's only possible perform runtime upgrades as follows:

```rust
tokio::spawn(async move {
	let update_client = api2.subscribe_to_updates();

	// This will run runtime updates in a loop which only returns if the RPC subscription is terminated.
	if let Err(e) = match update_client.perform_runtime_updates().await {
	    log::error!(target: LOG_TARGET, "Runtime update failed with result: {:?}", e);
		let _ = tx_runtime.send(e);
	}
});
```

subxt spawns a loop performs upgrades under the hood but I would want to know when a runtime upgrade occurred to provide some kind of metrics for it.

I think the current API is good but having a low-level API or some `impl Stream` wrapper that fires every time a runtime upgrade occurs.

**Comment by jsdw** [comment]
Makes sense to me to have a Stream that maybe has the version info in and that `perform_runtime_updates` can be a super simple wrapper around!
