### ISSUE TITLE
Introduce path prefix for generated `::subxt` code

### ISSUE THREAD

**Issue by cmichi** [paritytech/subxt#655]
I'm running into a problem using `subxt-codegen`:

- `subxt-codegen` generates code like this for certain code paths: `::subxt::tx::StaticTxPayload::new`.
- If `subxt` is not a root dependency of the invoking crate this results  in a compiler error `could not find 'subxt' in the list of imported crates`.

I suggest to introduce an optional prefix which can be passed to `subxt-codegen`.

**Comment by jsdw** [comment]
That makes sense, and it's the same sort of thing other proc macro crates in the ecosystem do to tackle the issue :)
