### ISSUE TITLE
Subscriptions: add timeout if no more messages received?

### ISSUE THREAD

**Issue by ascjones** [paritytech/subxt#66]
Since converting to `jsonrpsee`, subscriptions are handled with `while let msg = sub.next().await` which is an infinite loop (see https://github.com/paritytech/jsonrpsee/issues/86).

What if no more messages are received on a subscription (e.g. because connection has closed), or if the specific message we are waiting for doesn't arrive? Should we add a timeout? Otherwise we will wait indefinitely e.g. https://github.com/paritytech/substrate-subxt/blob/253a7d8b0b4ff33744aafc2f4aea6a6d14647681/src/rpc.rs#L286.

**Comment by ascjones** [comment]
To repro just close substrate node while waiting for a response. and then we get this on a loop:

```
[2020-04-15T07:28:33Z ERROR jsonrpsee::client] Client Error: Inner(Ws(Closed))
[2020-04-15T07:28:33Z ERROR jsonrpsee::client] Client Error: Inner(Ws(Closed))
[2020-04-15T07:28:33Z ERROR jsonrpsee::client] Client Error: Inner(Ws(Closed))
[2020-04-15T07:28:33Z ERROR jsonrpsee::client] Client Error: Inner(Ws(Closed))
[2020-04-15T07:28:33Z ERROR jsnrpsee::client] Client Error: Inner(Ws(Closed))
```

**Comment by jsdw** [comment]
@niklasad1 Is this an issue still?

**Comment by niklasad1** [comment]
The subscriptions will run indefinitely until the server has closed the connection.

Also, it's possible to that some subscriptions such as `submitAndWatch` would send events such as `Finalized` before the server closes the subscription but after that "no close message" is sent from substrate, thus up to user that handle those correctly or use the subxt helpers for that.

However, the bug that Andrew reported is fixed for a long time ago.

@jsdw I'm quite certain that you refactored all the `subscription polling` to the stream impl where users can add their own timeouts and/or stream combinators to fit a specific usecase. Thus, I would consider this issue as resolved

**Comment by jsdw** [comment]
Ah ok yeah, that makes sense! One can add their own timeouts etc pretty trivially since we impl Stream now :) I'll close this!
