### ISSUE TITLE
runtime_updates  blocks  thread when next using  subxt::dynamic::tx  

### ISSUE THREAD

**Issue by jerry-yu** [paritytech/subxt#684]
like this :

`  let client = OnlineClient::<PolkadotConfig>::new().await.unwrap();
 
  let update_task = client.subscribe_to_updates();
  tokio::spawn(async move {
      update_task.perform_runtime_updates().await;
  });

  let signer = PairSigner::<PolkadotConfig,Pair>::new(AccountKeyring::Alice.pair());
  let dest = AccountKeyring::Bob.to_account_id();

loop {  
    let tx = subxt::dynamic::tx(
        "Balances",
        "transfer",
        vec![
            Value::unnamed_variant("Id", [Value::from_bytes(&dest)]),
            Value::u128(1_256_789_012_345_000_000),
        ],
    );

    let hash = client.tx().sign_and_submit_default(&tx, &signer).await?;
    println!("Balance transfer extrinsic submitted: {}", hash);

    sleep(Duration::from_secs(4)).await;
}`

bloking when runtime code upgrade

**Comment by niklasad1** [comment]
hey @jerry-yu 

Can you provide a full example what your are running, so we can reproduce this issue? 
It's hard to reproduce what you are doing i.e, if you are using `tokio::time::sleep` or something else

Personally, I have used the `runtime update API` without any issues FWIW.

**Comment by jerry-yu** [comment]
Sorry it is my program's bug.  At the moment runtime code upgrading,  I didn't deal with the error just return out

`Balance transfer extrinsic submitted: Err(Rpc(RpcError("RPC call failed: ErrorObject { code: ServerError(1010), message: \"Invalid Transaction\", data: Some(RawValue(\"Transaction has a bad signature\")) }")))`

so leave the thread.
