### ISSUE TITLE
Make RpcError generic

### ISSUE THREAD

**Issue by gregdhill** [paritytech/subxt#692]
I am unable to upgrade from `0.23.0` to `0.24.0` because we lost the `RpcError` type ([here](https://github.com/paritytech/subxt/commit/599107b4322d2b959e26d9cf5269bc1ed4375a8c#diff-10b6cfdc40206da284713a1b63cb97c62e45a6018d456d32078b128712f8ea91L39)) propagated from `jsonrpsee`. We use this to specifically match custom errors for transaction invalidity and for when the background service needs to be restarted. Instead of converting this error into a string the `RpcClientT` trait should have a generic parameter for the error.

**Comment by jsdw** [comment]
We'll have to have a think about that; I do agree that we lose some detail, but adding a generic parameter would propagate through the entire codebase again, so it'd definitely be preferably to avoid that if we can!

Perhaps we should box the error if possible into a `Box<dyn Error>` type thing, so at least you can recover the underlying error by a cast, and we can avoid the generic proliferation; what do you reckon?

**Comment by lexnv** [comment]
To quickly unblock the transition to `0.24.0` one could try to match those strings.
The error string should contain enough information, and if it doesn't we should point that for a jsonrpsee update.
It might not be ideal, but just a temporary fix until we roll a `Box<dyn Err>` as James mentioned.

**Comment by gregdhill** [comment]
I want to avoid comparing strings for obvious reasons, but we also need to parse the JsonRPC error object in some cases. The approach you have suggested @jsdw makes sense to me!

**Comment by jsdw** [comment]
@gregdhill would you be able to check out #694 and confirm that it addresses your needs?

**Comment by gregdhill** [comment]
LGTM, thanks @lexnv @jsdw!
