### ISSUE TITLE
Rpc Error handling

### ISSUE THREAD

**Issue by sander2** [paritytech/subxt#724]
https://github.com/paritytech/subxt/pull/634 generalized the code over rpc implementations. This PR changed the `subxt::Error::Rpc` error to a generalized one. First to a string, later to a `dyn std::Error`:

https://github.com/paritytech/subxt/blob/15ffbb6c4b8be1dace182ff9b16c0b2f8cbd29f5/subxt/src/error.rs#L111-L118

The problem is that this removes our ability to react to different rpc errors. For some errors we can recover, such as the `POOL_TOO_LOW_PRIORITY` error that we get when two connections use the same nonce at the same time. Other errors are unrecoverable, such as `JsonRpseeError::RestartNeeded`. Would it be possible to make `subxt::Error` generic over the rpc error type so that we can use proper pattern matching in our client?

**Comment by niklasad1** [comment]
@sander2 

The current approach is that you have to downcast the `ClientError(Box<dyn std::error::Error + Send + Sync + 'static>` to `jsonrpsee::Error` [such as this](https://github.com/paritytech/staking-miner-v2/blob/main/src/monitor.rs#L113-#L157) which is not super nice but that's intention IIRC.

otherwise I don't understand what the issue is

**Comment by jsdw** [comment]
Yeah

> Currently using a [fork](https://github.com/interlay/subxt/commit/50dee0eed3c9202a60276d18d880cb1f0f2acd43) that makes the error concrete again. Obviously this will be a problem for non-jsonrpc transport implementations though. Ideally, the `ClientT` should take an associated `Error` type, and the global `subxt::Error` struct should be generic over the `TransportError`. That's quite a refactor, though..

Yeah; It was so nice to be able to remove a generic param from the error type (which infests and complicates everything else) that I'd be somewhat reluctant to put it back!

**Comment by sander2** [comment]
I wasn't aware of the `downcast` function - that'll solve my issue. Sorry for the noise!
