### ISSUE TITLE
API for fetching events in `dynamic context`

### ISSUE THREAD

**Issue by niklasad1** [paritytech/subxt#726]
Let the example where I'm using the `dynamic API` to `submit_and_watch` such as:

```rust
    let tx = create_dynamic_tx();

    let mut status_sub = api
        .tx()
        .sign_and_submit_then_watch_default(&tx, &*signer)
        .await
        .unwrap();

    loop {
        let status = status_sub.next_item().await.unwrap().unwrap();

        match status {
            TxStatus::InBlock(details) => {
                let events = details.fetch_events().await.expect("events should exist");

                // TODO fetch events somehow?!...
            }
            _ => panic!("Not important for this example"),
        }
    }
```

I can't find any API except https://docs.rs/subxt/latest/subxt/blocks/struct.ExtrinsicEvents.html#method.iter to find the events.
Thus, it's this the way to do this or any other API to do this?

I guess I would have to iterator over the events and try to decode it as `scale::Value` or something then deserialize it as my event...

**Comment by lexnv** [comment]
After fetching the events from the extrinsic with `details.fetch_events()`, 
iterating over the `events.iter()` would list all the events associated with
the transaction. 

However, if we want to iterate all the events from that block, we could
use `events.all_events_in_block()`. 

When we call `events.iter()` or `events.all_events_in_block().iter()` the provided
result would be of type `events::EventDetails`. This `events::EventDetails` could
then be cast to a static type if need be using `as_event`, or use the `EventDetails`
directly with associated methods.
