### ISSUE TITLE
How to log substrate types in wasm?

### ISSUE THREAD

**Issue by amiyatulu** [paritytech/subxt#730]
Here is my code:

```rust
use gloo::console::log;
#[subxt::subxt(runtime_metadata_path = "./artifacts/metadata.scale")]
pub mod polkadot {}

let client = subxt::client::OnlineClient::<PolkadotConfig>::from_url("ws://127.0.0.1:9944")
                        .await
                        .unwrap();
let key = polkadot::runtime_types::sortition_sum_game::types::SumTreeName::UniqueIdenfier1 {
                    citizen_id: 0,
                    name: "challengeprofile".as_bytes().to_vec(),
                };
let period_storage = polkadot::storage().template_module().period_name(&key);
let period = client.storage().fetch(&period_storage, None).await.unwrap();
log!(serde_json::to_string_pretty(&period).unwrap());
```
It gives error:
```
log!(serde_json::to_string_pretty(&period).unwrap())
     |                      ---------------------------- ^^^^^^^ the trait `Serialize` is not implemented for `pallet_template::types::Period`
     |                      |
     |                      required by a bound introduced by this call
```

**Comment by niklasad1** [comment]
Hey,

You can try to derive `Debug` for the generated types [example here](https://github.com/paritytech/subxt/blob/master/examples/examples/custom_type_derives.rs#L14)

If that doesn't work you can always substitute the generated types with types from substrate [example here](https://github.com/paritytech/staking-miner-v2/blob/main/src/prelude.rs#L82-#L83)

**Comment by amiyatulu** [comment]
Debug didn't worked, I implemented Display to make it work:

```
use std::fmt;
impl fmt::Display for polkadot::runtime_types::pallet_template::types::Period {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

log!(period.unwrap().to_string());
```

**Comment by niklasad1** [comment]
@amiyatulu 

I'm no expert on `wasm logging` but we are using `tracing` to log stuff in jsonrpsee and subxt so it would be better to use https://crates.io/crates/tracing-wasm that. Another benefit is that you don't have to convert it to a string you can just do `trace::info!("{:?}", x)`

Otherwise, you will only get your own logs.

**Comment by niklasad1** [comment]
I regard this issue as closed, feel free to re-open if doesn't work
