### ISSUE TITLE
Runtime panicked: Bad input data provided to validate_transaction: Invalid length prefix

### ISSUE THREAD

**Issue by metmirr** [paritytech/subxt#738]
Hello, I am using subxt to read data and submit transactions. I have the latest `substrate-node-template` running and I am using this example as a starter [examples/balance_transfer.rs](https://github.com/paritytech/subxt/blob/master/examples/examples/balance_transfer.rs).

Error details:

`Error: Rpc(ClientError(Call(Custom(ErrorObject { code: ServerError(1002), message: "Verification Error: Runtime error: Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Invalid length prefix", data: Some(RawValue("RuntimeApi(\"Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Invalid length prefix\")")) }))))`

Additional notes: I can read storage without any issues. Also, submit transactions from the polkadot.js.org/apps

**Comment by niklasad1** [comment]
hey @metmirr 

Can you please specify which substrate `rev` your using and the code use in [examples/balance_transfer.rs](https://github.com/paritytech/subxt/blob/master/examples/examples/balance_transfer.rs)?

I tried running the balance transfer against  [substrate b1396f](https://github.com/paritytech/substrate/commit/b1396f708b2001593d5589dd1bd3f832821fb208) and it worked fine.

Please not that the `substrate node template` runtime is a bit different compared to polkadot and our integration tests are executed against polkadot (every day) so it might not work reliable in all cases.

**Comment by niklasad1** [comment]
alright, "subxt master" is only tested against the polkadot "master" so we don't really keep track of backwards compatibility with older polkadot/substrate versions.

you can find more info about that here: https://github.com/paritytech/subxt/issues/626

Perhaps try some older version of subxt such as `v0.25` or `v0.24` might good for subxt to have such compatibility matrix, it's quite hard to get that.

**Comment by metmirr** [comment]
I see, thank you. I will close the issue then. Perhaps would it make sense to add that info to the readme. As you can guess most of the starters use node template which is pointed to some stable version of the substrate.
