### ISSUE TITLE
Support decoding pallet errors

### ISSUE THREAD

**Issue by deuszx** [paritytech/subxt#781]
Each pallet can define its own error enum which may be returned as as event in the following (not exactly) form:
```
Event {
  method: "ExtrinsicFailed",
  section: "Contracts",
  index: "0x0200"
}
```
In order to find what the errors means, client has to find the proper pallet and then the error enum inside it. Finally, count the enum variants (0-indexed) to find the error in question.

It should be possible (if not, please correct me) to generate the decoding code when deriving the client. Similar thing is already being done for pallet events.

**Comment by ascjones** [comment]
This is already possible with https://github.com/paritytech/subxt/blob/c100b0b2ba05ab86a08f129a43f8845385ca8cbd/subxt/src/metadata/metadata_type.rs#L127, used from https://github.com/paritytech/subxt/blob/389f20ff94ae85491a48eabf7d71dec7a71b5257/subxt/src/error.rs#L138

**Comment by deuszx** [comment]
Thanks @ascjones 👍 I'll dig deeper then :)
