### ISSUE TITLE
When is the next release scheduled?

### ISSUE THREAD

**Issue by kylezs** [paritytech/subxt#790]
There are a few fixes in main that would be very helpful to have in a release, in particular this one: https://github.com/paritytech/subxt/pull/727/files for me. Was wondering when the next release is scheduled?

**Comment by jsdw** [comment]
Thanks for letting me know you're keen. I have had in mind the last week or so to do a release; we've a couple of other outstanding PRs I'd like to merge but possibly in the next few days we can get one out :)

I'll close this as presumably that has answered your question!

**Comment by kylezs** [comment]
That's be great if something's out in next few days, cheers.
