### ISSUE TITLE
Strange dynamic storage query behaviour

### ISSUE THREAD

**Issue by Haider-Ali-DS** [paritytech/subxt#799]
I am trying to dynamically query EraStakers storage from [staking pallet](https://github.com/paritytech/substrate/blob/911c9ab067d3cf487cfef61906ed2525cb87a5c9/frame/staking/src/pallet/mod.rs#L408):

it takes two keys 
* EraIndex, 
* AccountID.

The type received from the metadata for this specific storage is:
```Type { path: Path { segments: [] }, type_params: [], type_def: Tuple(TypeDefTuple { fields: [UntrackedSymbol { id: 4, marker: PhantomData }, UntrackedSymbol { id: 0, marker: PhantomData }] }), docs: [] }```

So according to it tuple contains two types. which type_id: 4 and type_id: 0 i.e. u32 and [u8; 32]

since `dynamic::tx()` takes a `fields: impl Into<Composite<()>>` with pallet and storage name
we pass it a vec![] containing  `scale_value::Value`

I have somehow to map types automatically into scale_value::Value types using runtime metadata at runtime. now since scale_value's `tuple` is decoded in composite type [reference](https://github.com/paritytech/scale-value/blob/main/src/scale_impls/decode.rs#L156). so I must wrap the type in `Value::unnamed_composite(vec_of_value)` so i converted `EraIndex` and `AccountID` into scale_value's `value` and added them into `Value::unnamed_composite(vec_of_value)` code looks something like below

```
let params = Value::unnamed_composite(Vector of values requied by storage key);
let storage_address = subxt::dynamic::storage(pallet, storage, vec![params]);
```

now the length of params is 1 which is an Unnamed Composite. but in subxt's [Storage Address](https://github.com/paritytech/subxt/blob/master/subxt/src/storage/storage_address.rs#L249) it checks the length of type_id fields which is 2 and my `vec![params]` which is 1 so condition becomes false and returns error. 

I know i can get this thing done by changing params to something like this
```
let first_param = scale_value::value(u32);
let second_param = scale_value::from_bytes([u8;32]);
let storage_address = subxt::dynamic::storage("Staking", "EraStacker", vec![first_param, second_param]);
```
 
But this should not be the case since the type returned by metadata is tuple and tuple must be wrapped into unnamed_composite([values]);

if i don't do conversion to unnamed_composite it will work fine but then other wrappers fails which i am using for `subxt::dynamic::tx` which expects tuples to be wrapped in unnamed_composite.

**Comment by jsdw** [comment]
Storage entries that are maps basically require 1 or more keys to be provided as you've observed. We decided to model that in scale-info by saying that if a map needs just one key, the key type will not be a tuple, but will be whatever type is expected for that ket, and if the map needs N keys, the key type will be a tuple of N keys. I believe that this is somewhat arbitrary; we just picked some way to represent the keys needed via sacle-info types.

The Subxt API irons out this "provide a tuple for N keys or a plain value for 1 key" way or describing it in scale-info, and just asks for a vec of whichever keys are needed (a vec of one item for one key, two items for two keys and so on).

So how you've ended up doing it, ie:

```rust
let first_param = scale_value::value(u32);
let second_param = scale_value::from_bytes([u8;32]);
let storage_address = subxt::dynamic::storage("Staking", "EraStacker", vec![first_param, second_param]);
```

Is absolutely the expected approach, and by the sounds of it this is working OK for you :)
