### ISSUE TITLE
Support sending of extrinsics and returning the result from the function

### ISSUE THREAD

**Issue by MrishoLukamba** [paritytech/subxt#800]
At the moment we only return the hash of the extrinsic submitted. However we should support returning what's the function is returning as this can be important.

**Comment by jsdw** [comment]
The two functions that are useful for submitting extrinsics are `author_submitExtrinsic`, which returns a the extrinsic hash, and `author_submitAndWatchExtrinsic`, which is available on WS connections and returns the status of the extrinsic's inclusion into a block. The Subxt interface mirrors this, so it is already returning the vailabel information :)

More generally, submitting an extrinsic doesn't _have_ a return value; once the extrinsic is in a block, the act of executing that block will (potentially) lead to changes in state (and probably some events being emitted to signal what's happened, though that is mostly up to the extrinsic). Subxt then provides you the facilities to query storage and query the extrinsic events to see the effects.

I hope that makes this clearer for you. I'll close this now.

**Comment by MrishoLukamba** [comment]
It is clear, Although getter functions behave differently
