### ISSUE TITLE
 unresolved import `subxt::tx::PairSigner` on wasm

### ISSUE THREAD

**Issue by amiyatulu** [paritytech/subxt#828]
On version upgrade PairSigner gives error on wasm. 
subxt = { version="0.27.1", default-features = false, features = ["jsonrpsee-web"] }

The issue seems related to https://github.com/paritytech/subxt/issues/772

```
error[E0432]: unresolved import `subxt::tx::PairSigner`
 --> src/components/accounts/sign_tx_hook.rs:6:5
  |
6 |     tx::PairSigner,
  |     ^^^^^^^^^^^^^^ no `PairSigner` in `tx`
```

**Comment by niklasad1** [comment]
Hey,

`PairSigner` is not supported anymore on WASM unfortunately because of https://github.com/paritytech/substrate/issues/5547 before we had a hack that worked around that but doesn't work anymore.

So closing as duplicate of #772
