### ISSUE TITLE
How about using workspace inheritance for this repo?

### ISSUE THREAD

**Issue by koushiro** [paritytech/subxt#831]
Rust 1.64.0 feature: https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds
RFC: https://github.com/rust-lang/rfcs/blob/master/text/2906-cargo-workspace-deduplicate.md

**Comment by niklasad1** [comment]
It could be useful to share `version number` and `url` between the crates, so why not.

/cc @jsdw thoughts?

**Comment by koushiro** [comment]
I'll open two PRs to use workspace inheritance for package info and dependencies separately

**Comment by jsdw** [comment]
Sounds good to me; let's avoid copy-paste of duplicated fields where possible!

**Comment by jsdw** [comment]
Since that PR is merged I'll close this now since I think this is done :)
