### ISSUE TITLE
How can we sign things via a browser?

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#836]
At the moment, we can pass in a `Signer` implementation to eg `TxClient::create_signed_with_nonce` to sign the tx for us.

In order for that `Signer` implementation to call out to a browser and let it sign things, it would need to be `async`.

Alternately, perhaps we can tweak the interface such that one can do something like get hold of the pre-signed transaciton details (signer payload and tx or some struct representing this) and then once we have a signature, turn this into a `SubmittableExtrinsic` by providing it and finishing the construction of the tx.

Let's figure something out here, and in the process try to come up with a simple example of making use of it (possibly via a browser wasm thing) so that we know we can do this.

**Comment by ascjones** [comment]
Yes please! This would be needed in any CLI tool which utilizes `subxt`.

This discussion took place somewhere else, possibly in the old subxt chat. But IIRC the idea was to launch a simple web server hosting a page which can accept the tx payload via the url or `POST`, which could then be wired up to communicate with the user's browser signing extension of choice. Can't remember how to get the signed data back, could possibly query the server again for the signed tx.

**Comment by amiyatulu** [comment]
I tried to sign through polkadot extension using wasm-bindgen, but failed to get  { signer: injector.signer } from javascript to rust. Can signing through polkadot extension be build native to subxt? https://github.com/amiyatulu/polkadot-extension-on-yew

**Comment by boyswan** [comment]
Just commenting to say I would be very happy to be able to use subxt in the browser as a replacement for the JS api!

**Comment by jsdw** [comment]
@bernardoaraujor asked for the ability to get hold of a signer payload + unsigned tx separately, and so I think whatever is done here should also expose that (probably pushing us towards exposing functions rather than making Signer async)
