### ISSUE TITLE
Does wait_for_finalized hang indefinitely if the tx dropped or usurped

### ISSUE THREAD

**Issue by furoxr** [paritytech/subxt#889]
https://github.com/paritytech/subxt/blob/42bcddeecb39db98e711075b44331d24a8fbeb4d/subxt/src/tx/tx_progress.rs#L102-L116

I have a question regarding a scenario where I send a transaction and invoke this method to wait for its finalization. Is there a risk that the program may hang indefinitely? This is because the status of the transaction may be usurped or dropped, causing the method to continue waiting without returning an error in such cases.

**Comment by niklasad1** [comment]
>    /// **Note:** transaction statuses like `Invalid` and `Usurped` are ignored, because while they
>    /// may well indicate with some probability that the transaction will not make it into a block,
>    /// there is no guarantee that this is true. Thus, we prefer to "play it safe" here. Use the lower
>    /// level [`TxProgress::next_item()`] API if you'd like to handle these statuses yourself.

This documentation is a bit tricky to understand I reckon but if you take a look at https://github.com/paritytech/substrate/blob/master/client/transaction-pool/api/src/lib.rs#L59-#L104, 

> The stream is considered finished only when either `Finalized` or `FinalityTimeout`

It will wait up to 512 blocks until the `FinalityTimeout` is triggered so not indefinitely but based on your usecase you can maybe regard `Usurped, Dropped and other events` as failed up to you.

**Comment by furoxr** [comment]
Thank you for your help. However, based on the documentation, I understand that the FinalityTimeout only applies to transactions that are included in a block.  If a transaction is usurped or dropped and not included in any block, would the method still trigger a FinalityTimeout?
https://github.com/paritytech/subxt/blob/42bcddeecb39db98e711075b44331d24a8fbeb4d/subxt/src/tx/tx_progress.rs#L244-L246

**Comment by niklasad1** [comment]
The extrinsic can be kicked out from the pool (dropped, invalid etc) and then later be re-entered in the pool again (Retracted) but I'm not sure whether that can happen on `Usurped (i.e, replaced probably not)`

/cc @jsdw do you know? :)

**Comment by jsdw** [comment]
I'll close this now, and if we learn something interesting from the StackExchange answer that leads to tweaking Subxt then I'll open a new issue for that. Otherwise, You currently have the option to handle transaction status updates however you'd like if the built-in `wait_for_finalized*` methods aren't suitable :)

**Comment by furoxr** [comment]
I have made an investigation, and find something interesting. The Stream trait implemented for TxProgress will end only when the event FinalityTimeout or Finalized received.  But I found the RPC server of substrate will remove subscribers when the usurped,  invalid, dropped, finalized or finality_timeout received. So I'm curious whether TxProgress would drop the connection and stop waiting for new events?

Please find below some relevant code snippets:

https://github.com/paritytech/subxt/blob/a2b8dde5e6d0a6e9c81a6b3d4bebe5177dc7899a/subxt/src/tx/tx_progress.rs#L137-L181


This is Listener, the server side corresponding to the client of subscribition. It will fire a event when the transaction status changed, and it will close the connection if `h.is_done()` returns true. You could find the code [here](https://github.com/paritytech/substrate/blob/75dee3c6fc72f6399a43f498e0e42f94fb82a7bd/client/transaction-pool/src/graph/listener.rs#L44-L59)
```
impl<H: hash::Hash + traits::Member + Serialize, C: ChainApi> Listener<H, C> {
	fn fire<F>(&mut self, hash: &H, fun: F)
	where
		F: FnOnce(&mut watcher::Sender<H, ExtrinsicHash<C>>),
	{
		let clean = if let Some(h) = self.watchers.get_mut(hash) {
			fun(h);
			h.is_done()
		} else {
			false
		};


		if clean {
			self.watchers.remove(hash);
		}
	}
```

And `h` is a instance of [Sender](https://github.com/paritytech/substrate/blob/75dee3c6fc72f6399a43f498e0e42f94fb82a7bd/client/transaction-pool/src/graph/watcher.rs#L51-L54). It's method `is_done` returns true if `is_finalized` is true, or it's subscribers is empty.
```
pub fn is_done(&self) -> bool {
        self.is_finalized || self.receivers.is_empty()
}
```

And you could find relevent codes [here](https://github.com/paritytech/substrate/blob/75dee3c6fc72f6399a43f498e0e42f94fb82a7bd/client/transaction-pool/src/graph/watcher.rs#L81), the Sender will change `is_finalized` to true, if the event is usurped, finalized, finality_timeout, invalid or dropped.

**Comment by niklasad1** [comment]
> So I'm curious whether TxProgress would drop the connection and stop waiting for new events?

I assume that you are referring to the substrate RPC server, it will just drop the subscription and no more message will be sent on the subscription. Then no the connection will not be dropped in that scenario.

To conclude, subxt will wait "forever/until the connection closed" on `wait_for_finalized` if any of the events `usurped, invalid, dropped, finalized` occurred.

**Comment by jsdw** [comment]
Ah very intersting; based on that code then we should probably tweak Subxt to do the same; if the subscription is dropped after those messages then we should also be ending it. I'll re-open this as reminder to do so
