### ISSUE TITLE
Test-runtime: Run Substrate node on port 0 for more reliable execution

### ISSUE THREAD

**Issue by jsdw** [paritytech/subxt#909]
We've ran into issues a couple of times now (eg #908) where a nightly build fails because it tried to connect to a Substrate node 6 times without success.

The way that we start said Substrate node up is by selecting a port to use like so:

```rust
fn next_open_port() -> Option<u16> {
    match TcpListener::bind(("127.0.0.1", 0)) {
        Ok(listener) => {
            if let Ok(address) = listener.local_addr() {
                Some(address.port())
            } else {
                None
            }
        }
        Err(_) => None,
    }
}
```

And then telling Substrate to start using that port.

I wonder whether the port isn't freed up quickly enough sometimes, and so Substrate picks another random port to start on or something like that, leading to an inability to connect to it?

In any case, in our tests we take a different approach; we start Substrate with a `--ws-port=0`, and then parse the `stdout` until we find the actual port that it picked. This may be a more reliable approach to take, since we'll always try connecting on the actual port that it used, and won't run the issue of providing a port that ends up being in use. So, let's update our build code to do the same thing.

**Comment by niklasad1** [comment]
It's probably a good idea but just a reminder I have opened https://github.com/paritytech/substrate/pull/13384 which will break things :P
