### ISSUE TITLE
jsonrpsee subscription WARN/ERROR

### ISSUE THREAD

**Issue by ascjones** [paritytech/subxt#94]
When submitting an extrinsic we occasionally get the following `UnknownSubscriptionId` WARN/ERROR from `jsonrpsee`:

![image](https://user-images.githubusercontent.com/75586/80340301-4edfa280-8858-11ea-961e-5a8657883059.png)

https://github.com/paritytech/jsonrpsee/blob/a0bea41c4f37125fa742ec48b12e11cf55c592b5/src/raw/client.rs#L457

This is from the subscription listening for block events. It doesn't stop it working but it is annoying for the user and potentially misleading.

**Comment by thiolliere** [comment]
It seems those error are also appearing when running `cargo test` which is indeed missleading

**Comment by DemiMarie** [comment]
I also sometimes get an infinite stream of error messages.
