### ISSUE TITLE
Can expose the ids in `BlockBody`?

### ISSUE THREAD

**Issue by alloctor** [paritytech/subxt#997]
```rust
pub struct BlockBody<T: Config, C> {
    details: ChainBlockResponse<T>,
    client: C,
    cached_events: CachedEvents<T>,
    ids: ExtrinsicPartTypeIds,
}
```
The above code holder `ids` filed from parsed block metadata, but it doesn't exposes.  Sometimes user want  access the `ids` filed, So I thought it could be made public and I could help fix it if necessary

**Comment by jsdw** [comment]
Those IDs are an internal detail used to help decode blocks; I'd prefer that they were only exposed via the Metadata, which is the correct place to look for these kidns of details. An upcoming metadata change will probably make them easier to get at, too :)

**Comment by alloctor** [comment]
> Those IDs are an internal detail used to help decode extrinsics in blocks; I'd prefer that they were only exposed via the Metadata, which is the correct place to look for these kinds of details (which they are, though right now you have to dig a little).
> 
> An upcoming metadata change will probably make them easier to get at, though!

Thanks for you reply, I was going deep into the internal implementation, and I had a question, how do I get the `(address + signature + extra)` information for signed extrinsic, which `ExtrinsicDetails`  doesn't seem to provide

**Comment by alloctor** [comment]
> Those IDs are an internal detail used to help decode extrinsics in blocks; I'd prefer that they were only exposed via the Metadata, which is the correct place to look for these kinds of details (which they are, though right now you have to dig a little).
> 
> An upcoming metadata change will probably make them easier to get at, though!

Thanks for you reply, I was going deep into the internal implementation, and I had a question, how do I get the `(address + signature + extra)` information for signed extrinsic, which `ExtrinsicDetails`  doesn't seem to provide

**Comment by lexnv** [comment]
The fields mentioned will be made available in the metadata-v15: https://github.com/paritytech/frame-metadata/pull/56/files#diff-b631a8358797082e1871375f34a6f6b405f4e0b93452db9b8067b343c442a7d5R173-R183.

For now, in metadata V14, Substrate does expose the type info in the `type_params` section of the extrinsic, and users would need to parse that information manually as we did in subxt: 
https://github.com/paritytech/subxt/blob/fdc0d09ca3fb1c8a22cb5a05ba8178f024d0cda3/subxt/src/blocks/extrinsic_types.rs#L488-L498

**Comment by jsdw** [comment]
Will close this, but hopefully the above code can be used as inspiration and possibly in the next release we'll have a much nicer way to get those type IDs :)
